### ISSUE TITLE
expand `/rosetta/v1/construction/preprocess` examples to include contract calls

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1000]
all of the current examples are about STX transfers, so we should add a contract call example and probably a token transfer example.

**Comment by MHassanTariq** [comment]
@rafaelcr I couldn't find any example for STX transfers in [/rosetta/v1/construction/preprocess](https://github.com/hirosystems/stacks-blockchain-api/blob/develop/docs/openapi.yaml#L2191-L2216). Can you clarify which examples are you talking about?
