### ISSUE TITLE
API Documentation has placeholders for API endpoints that haven't been implemented yet

### ISSUE THREAD

**Issue by saralab** [hirosystems/stacks-blockchain-api#1001]
API Documentation has references to endpoints that haven't been implemented yet. ex: https://docs.hiro.so/api#operation/get_all_subdomains

Sweep the documentation and clean up the content.

**Comment by zone117x** [comment]
Closed by https://github.com/hirosystems/stacks-blockchain-api/pull/1073
ty @saralab!
