### ISSUE TITLE
[Rosetta] include `dropped_replaced_by_fee` in operation_statuses

### ISSUE THREAD

**Issue by whoabuddy** [hirosystems/stacks-blockchain-api#1006]
**Is your feature request related to a problem? Please describe.**

While playing around with the Rosetta API I noticed the following when querying the network options:

```json
"allow": {
        "operation_statuses": [{
                "status": "success",
                "successful": true
            },
            {
                "status": "pending",
                "successful": true
            },
            {
                "status": "abort_by_response",
                "successful": false
            },
            {
                "status": "abort_by_post_condition",
                "successful": false
            }
        ],
```

Should this also include `dropped_replaced_by_fee`?

**Comment by zone117x** [comment]
Something to keep in mind is that all the existing statuses are for txs that are still _on chain_ even if they had an error condition, aside from "pending" which means it's in the mempool.

The `dropped_replaced_by_fee` status is much more ephemeral data reflecting historical mempool state. For example, if you synced a node from scratch, you won't have any of those.

**Comment by whoabuddy** [comment]
That makes sense, I have a node script that will query the transaction status for a given txid on an interval, and noticed that while the `dropped_replaced_by_fee` status is not shown in the explorer it does still give that response through the API, and wondered if that should be covered by these endpoints as well. Feel free to close the issue if this is not relevant.
