### ISSUE TITLE
only load relevant transaction in rosetta `/block/transaction`

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1008]
the current `/block/transaction` functionality queries (and parses) all transactions from the given block before selecting only the required one using a JS `find`: https://github.com/hirosystems/stacks-blockchain-api/blob/develop/src/api/controllers/db-controller.ts#L542-L554

we should only query the requested transaction from the database to speed up this endpoint.

**Comment by MHassanTariq** [comment]
@rafaelcr I'm a little confused regarding the miner rewards and unlocked addresses [here](https://github.com/hirosystems/stacks-blockchain-api/blob/aae6cc0c643a5c6056e596768080119e2c84bb21/src/api/controllers/db-controller.ts#L494-L502). We are required to run these queries for the block and not only for a specific transaction. Do you think that I check for the transaction type to be `CoinBase` before running these queries? Or do you have any other suggestions?

**Comment by rafaelcr** [comment]
@MHassanTariq checking for coinbase sounds like a good idea
