### ISSUE TITLE
rosetta return 400 on invalid requests

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1009]
similar to #854, we should return 400 errors on invalid Rosetta request parameters instead of 500 which may be marked as critical server errors on logs.

Example: https://github.com/hirosystems/stacks-blockchain-api/blob/develop/src/api/routes/rosetta/block.ts#L60-L64

**Comment by zone117x** [comment]
Added this to https://github.com/hirosystems/stacks-blockchain-api/issues/855

**Comment by zone117x** [comment]
Closed by https://github.com/hirosystems/stacks-blockchain-api/pull/1036
