### ISSUE TITLE
display chain tip info in the `/extended/v1/status` endpoint

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1015]
We currently display the API's `server_version` in `/extended/v1/status`:
```json
{
  "server_version": "stacks-blockchain-api v1.0.7 (master:6afaf39c)",
  "status": "ready"
}
```
However, it would be very useful to add entries with the current `block_height`, `block_hash`, `microblock_hash`, etc. that would give users a precise idea of the chain tip currently tracked by that API instance.

**Comment by MHassanTariq** [comment]
@rafaelcr does the approach of getting `block_height`, `block_hash`, and `index_block_hash` from [getChainTip](https://github.com/hirosystems/stacks-blockchain-api/blob/develop/src/datastore/postgres-store.ts#L981-L1007) and then using the `index_block_hash` to get the respective `microblock_hash` from `microblocks` sounds good to you?

**Comment by rafaelcr** [comment]
@MHassanTariq if you wait for #1028 to be merged, you could just query that view to get all that info very quickly

**Comment by rafaelcr** [comment]
@MHassanTariq due to some recent API outage events and the sudden urgency of this feature request, I'm taking this on myself so we can make it to next week's release. I know you have your hands full with other issues

**Comment by MHassanTariq** [comment]
Makes sense. No worries.
