### ISSUE TITLE
Adding microblocks_accepted txs count to /v1/block

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/stacks-blockchain-api#1048]
Currently, https://explorer.stacks.co/blocks?chain=mainnet performs a request for each microblock in the page just to fetch number of transactions. This causes ~150 requests per reload/pagination. We can eliminate these requests if `/v1/block` also returns number of transactions for each `microblocks_accepted `  (a list of {hash: string: transaction_count: number}) https://github.com/hirosystems/stacks-blockchain-api/blob/01d6e11b8e6f463585da9eb68ff91435d505850c/src/api/controllers/db-controller.ts#L472
A new endpoint would also work if we wanna keep this one backward compatible.

**Comment by rafaelcr** [comment]
@He1DAr is there anything the explorer might need besides tx count for every microblock? Maybe we could take this opportunity to add some extra info

**Comment by zone117x** [comment]
Note: assuming perf isn't an issue, it looks like we could just add a new pair of properties to the existing response (keeping things backwards-compat)

**Comment by He1DAr** [comment]
> ke this opportunity to add some extra info

Txs count is the only info needed for now.

**Comment by rafaelcr** [comment]
This is now ready @He1DAr , it will be available to you in the next release (v5, in a couple of weeks)
