### ISSUE TITLE
Add additional columns for sorting `principal_stx_txs` table

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1050]
A hotfix in PR https://github.com/hirosystems/stacks-blockchain-api/pull/1044/files had to move the LIMIT/OFFSET clauses to the outer sql query to fix an issue with out-of-order txs returned by the `getAddressTxs(...)` function:
https://github.com/hirosystems/stacks-blockchain-api/blob/c483485c9c9b632d9c1360dd6d347d9d2b83e57f/src/datastore/postgres-store.ts#L5469-L5487

This degrades the performance of endpoints using this query. The `principal_stx_txs` table needs a breaking change to add the additional columns so the more performant query can be restored.

**Comment by rafaelcr** [comment]
Related to #1039
