### ISSUE TITLE
Update /extended/v1/status to "syncing" if more than X blocks are missing 

### ISSUE THREAD

**Issue by mardi00** [hirosystems/stacks-blockchain-api#1055]
**Is your feature request related to a problem? Please describe.**
On the /extended/v1/status endpoint, the status is 'ready' even if a hundred blocks still need to be synced
`{
  "server_version": "stacks-blockchain-api v2.0.0 (master:8b95f1d9)",
  "status": "ready"
}`

**Describe the solution you'd like**
When more than X blocks (5, for example) still need to be synced, we would have the 'syncing' status
`{
  "server_version": "stacks-blockchain-api v2.0.0 (master:8b95f1d9)",
  "status": "syncing"
}`

**Comment by zone117x** [comment]
Related to existing issue https://github.com/hirosystems/stacks-blockchain-api/issues/698

The API does not have the information required for this feature. Once PR https://github.com/stacks-network/stacks-blockchain/pull/2768 exposes sync status / block percentage, then the API could potentially expose that info as well. Although, if the an RPC endpoint already exposes it, there's no real reason for the API to duplicate that in another endpoint.

**Comment by sabbyanandan** [comment]
Given the upstream's RPC endpoint already supports it, let's not duplicate this. Closing this for now.
