### ISSUE TITLE
nonce mismatch

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/stacks-blockchain-api#1057]
I'm having an issue where my local instance shows a different nonce to the public hiro instance. 
note that they're on same blockheight but my local api is 0.71.2 version.

see screenshot from [https://stacks-node-api.stacks.co/extended/v1/address/SP13R6D5P5TYE71D81GZQWSD9PGQMQQN54A2YT3BY/nonces?unanchored=true](https://stacks-node-api.stacks.co/extended/v1/address/SP13R6D5P5TYE71D81GZQWSD9PGQMQQN54A2YT3BY/nonces?unanchored=true)
vs command output from my local api on `blockstack/stacks-blockchain-api:0.71.2`

![image](https://user-images.githubusercontent.com/3731591/153687676-9972bf76-0b2d-4831-a776-b85ef531eef3.png)

> root@localhost:~/lnstxbridge# curl http://localhost:3999/extended/v1/address/SP13R6D5P5TYE71D81GZQWSD9PGQMQQN54A2YT3BY/nonces?unanchored=true
{
  "last_executed_tx_nonce": 308,
  "last_mempool_tx_nonce": null,
  "possible_next_nonce": 309,
  "detected_missing_nonces": []
}

* https://stacks-node-api.stacks.co/v2/info  
> {"peer_version":402653189,"pox_consensus":"c22f18576bc56290535acda09bfb2e98fa4986fd","burn_block_height":722838,"stable_pox_consensus":"baa6edb4790f665af175c0f0cbefcde1db33eb40","stable_burn_block_height":722831,"server_version":"stacks-node 2.05.0.1.0 (master:de541f9+, release build, linux [x86_64])","network_id":1,"parent_network_id":3652501241,"stacks_tip_height":48385,"stacks_tip":"b74569d8028fe3822d5d701dd4e58d001a35d4a75803e4e38354c3cb5fcb3a82","stacks_tip_consensus_hash":"75965f821409274586bd8d0a69facd910ea6cdc9","genesis_chainstate_hash":"74237aa39aa50a83de11a4f53e9d3bb7d43461d1de9873f402e5453ae60bc59b","unanchored_tip":null,"unanchored_seq":null,"exit_at_block_height":null}

* local instance  
> root@localhost:~/lnstxbridge# docker ps
CONTAINER ID   IMAGE                                     COMMAND                  CREATED        STATUS        PORTS                                                                                  NAMES
392e84c42e0b   blockstack/stacks-blockchain-api:0.71.2   "docker-entrypoint.s…"   8 weeks ago    Up 3 weeks    0.0.0.0:3700->3700/tcp, :::3700->3700/tcp, 0.0.0.0:3999->3999/tcp, :::3999->3999/tcp   stacks-blockchain-api
c6a64b59b54a   blockstack/stacks-blockchain:2.05.0.0.0   "/bin/stacks-node st…"   2 months ago   Up 6 weeks    0.0.0.0:20443-20444->20443-20444/tcp, :::20443-20444->20443-20444/tcp                  stacks-blockchain
6f0ffdf4b8a8   postgres:alpine                           "docker-entrypoint.s…"   2 months ago   Up 2 months   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                              postgres

> root@localhost:~/lnstxbridge# curl http://localhost:3999/v2/info  
{"peer_version":402653189,"pox_consensus":"75965f821409274586bd8d0a69facd910ea6cdc9","burn_block_height":722837,"stable_pox_consensus":"2a624b5d4f871aec15ebdd41bb6dead886bf96f3","stable_burn_block_height":722830,"server_version":"stacks-node 2.05.0.0.0 (master:a783b27, release build, linux [x86_64])","network_id":1,"parent_network_id":3652501241,"stacks_tip_height":48385,"stacks_tip":"b74569d8028fe3822d5d701dd4e58d001a35d4a75803e4e38354c3cb5fcb3a82","stacks_tip_consensus_hash":"75965f821409274586bd8d0a69facd910ea6cdc9","genesis_chainstate_hash":"74237aa39aa50a83de11a4f53e9d3bb7d43461d1de9873f402e5453ae60bc59b","unanchored_tip":"0000000000000000000000000000000000000000000000000000000000000000","unanchored_seq":0,"exit_at_block_height":null}

**Comment by zone117x** [comment]
Seems like a bug in the older API version (0.71.2) that you're running locally. Can you reproduce this when running with the latest?

Production looks correct:

`https://stacks-node-api.stacks.co/v2/accounts/SP13R6D5P5TYE71D81GZQWSD9PGQMQQN54A2YT3BY?proof=0`
```json
{
"balance": "0x000000000000000000000000289d9c2b",
"locked": "0x00000000000000000000000000000000",
"unlock_height": 0,
"nonce": 336
}
```

`https://stacks-node-api.stacks.co/extended/v1/address/SP13R6D5P5TYE71D81GZQWSD9PGQMQQN54A2YT3BY/nonces`
```json
{
"last_executed_tx_nonce": 335,
"last_mempool_tx_nonce": null,
"possible_next_nonce": 336,
"detected_missing_nonces": []
}
```

**Comment by pseudozach** [comment]
I agree this was due to old version. I've upgraded and issue is not seen anymore.
thanks.
