### ISSUE TITLE
Fix RPC proxy middleware errors showing up in logs

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1065]
Expected-looking http errors occurring inside the RPC proxy are showing up as `level: error` logs.

Example: 
`Response 400 during POST /v2/transaction to extra endpoint http://stacks-node-follower-events-blue-0.stacks-node-follower-events-blue.prod-stacks.svc.cluster.local:20443/v2/transactions`

**Comment by MHassanTariq** [comment]
@zone117x what is the required behavior for this issue? 
With the current approach, the [specified error](https://github.com/hirosystems/stacks-blockchain-api/blob/master/src/api/routes/core-node-rpc-proxy.ts#L209-L211) is logged [here](https://github.com/hirosystems/stacks-blockchain-api/blob/master/src/helpers.ts#L195). Are we supposed to ignore the http error even if the `p.value.ok` is not true? Or should such errors be shown as `level: warning` logs?

**Comment by zone117x** [comment]
These should probably be `warning` level logs.
