### ISSUE TITLE
Ability to list subdomains

### ISSUE THREAD

**Issue by pradel** [hirosystems/stacks-blockchain-api#1097]
**Is your feature request related to a problem? Please describe.**

I would like to list all the registered subdomains in the same way you can list the domains. In the code I saw a `getSubdomainsList ` function https://github.com/hirosystems/stacks-blockchain-api/blob/dbd5a49c6e3dab06cb080c8c2de7dcc07aeb6805/src/datastore/postgres-store.ts#L6859 but it doesn't seem to be exposed to the API.

What I tried:
- The get namespace names does not work with subdomains (or at least I didn't manage to make it work) https://hirosystems.github.io/stacks-blockchain-api/#operation/get_namespace_names
- The get all names API route does not seem to return usernames https://hirosystems.github.io/stacks-blockchain-api/#operation/get_all_names.

**Describe the solution you'd like**

An API route to list all the subdomains registered with pagination.

**Comment by hstove** [comment]
You can query the subdomain registrar directly - `/list/:iterator` (like `/list/0`)

https://github.com/stacks-network/subdomain-registrar/blob/master/src/http.js#L196

**Comment by pradel** [comment]
I just tried and seems like the iterator is not working, for example https://registrar.stacks.co/list/1 and https://registrar.stacks.co/list/2 return the same results.

**Comment by pradel** [comment]
This sounds good 👍
