### ISSUE TITLE
Documentation for `/v2/fees/transaction` is missing

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/stacks-blockchain-api#1099]
At the Stacks blockchain, there's an [`/v2/fees/transaction`](https://github.com/stacks-network/stacks-blockchain/blob/master/docs/rpc/openapi.yaml#L283) endpoint, which returns the current transaction fee, so as a Hiro API user, I can invoke `https://docs.hiro.so/api#operation/get_transaction_fee` (or similar) to get a fee estimate before proceeding to transact from my application.

Backstory:

_- With the fee estimate, I will have better insight into whether the metadata and/or payload (which is video files in our case) that I am about to transact with will impact the overall transaction cost. Knowing that we can optimize for and/or switch to different data structures._

_- With this information, I can determine how much of an overhead it would cause for our users using our Stacks project/application. Again, it will help with downstream optimizations in our project/application._

**Comment by unclemantis** [comment]
Please upgrade the stacks.co API to 4.0.0 please. Thought I was going nuts.

https://stacks-node-api.testnet.stacks.co/extended/v1/status

{
  "server_version": "stacks-blockchain-api v3.0.3 (master:cd0c8aef)",
  "status": "ready",
  "chain_tip": {
    "block_height": 57182,
    "block_hash": "0xe39e60e590daed929d8127d8abcf18f8cf5bf76be74bd41f75236685756b9452",
    "index_block_hash": "0xed7d583b62544edc843f7279ee0e4c078fd12189d312619effb12d1a54b71d8d"
  }
}

**Comment by unclemantis** [comment]
Maybe I am doing it wrong with mainnet too,
```
{ transaction_payload: `${raw_tx}` }
```
