### ISSUE TITLE
lint/validate openapi spec automatically with github actions

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1104]
Our current openapi spec has a few lint/validaton errors (https://apitools.dev/swagger-parser/online/). This is preventing developers from generating client libraries in other languages.

We should validate the spec automatically using github actions so we can catch these errors early.

**Comment by rc-xchains** [comment]
Thank you! We are having trouble with generating Java SDK using the current openapi.json. This feature will allow us to move from custom (incomplete and buggy) client to more complete implementation.

**Comment by sabbyanandan** [comment]
@rc-xchains: Thank you for the feedback! We will look into the automation and address the validation errors. Likewise, we are also open to engaging with the community, so feel free to submit a PR at any time.

**Comment by aulneau** [comment]
Any update on this -- it'd be really nice if the linting errors would be fixed, that way we can generate any client we might want to work.

**Comment by rafaelcr** [comment]
@aulneau fix incoming https://github.com/hirosystems/stacks-blockchain-api/pull/1170

**Comment by rafaelcr** [comment]
I tested the new schema with the swagger online generator and was able to generate a PHP client, but please let me know if you have any problems @aulneau @rc-xchains .

One important note is that you'll probably need to use the fully resolved spec for the generator. I recommend downloading the .json file from the generated Redoc site to do so (https://docs.hiro.so/api once this PR is released to production).
