### ISSUE TITLE
Missing/changed data from metadata endpoint

### ISSUE THREAD

**Issue by kyranjamie** [hirosystems/stacks-blockchain-api#1139]
Reported first on [#wallet channel on Discord](https://discord.com/channels/621759717756370964/745197302255321108/960842500879302750)

A user has reported that the wallet is no longer displaying names, or decimal places, for some FTs. Investigating this issue, it seems like this may be an API issue. 

Consider DIKO token.
- [Contract](https://explorer.stacks.co/txid/0x81ce000866e5a61ed46ced874ebb453cb9b4de8b9ba1e14ed810221a1dff238b?chain=mainnet)
- [Metadata response](https://stacks-node-api.stacks.co/extended/v1/tokens/SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-token/ft/metadata?unanchored=true)

The contract describes a name, and that there are 6 decimals. Yet, the API is responding with: 

```json
{
  "token_uri": "",
  "name": "",
  "description": "",
  "image_uri": "",
  "image_canonical_uri": "",
  "symbol": "",
  "decimals": 0,
  "tx_id": "0x81ce000866e5a61ed46ced874ebb453cb9b4de8b9ba1e14ed810221a1dff238b",
  "sender_address": "SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR"
}
```

@aulneau confirmed that this endpoint did in the past return correct metadata.

**Comment by markmhx** [comment]
cc @sabbyanandan @saralab @zone117x on possible API issue ☝️

**Comment by wbnns** [comment]
Hello, we are also seeing reports of this issue. At the moment, users are at a high risk of potentially losing funds because their available balance isn't being reported correctly -- decimals are being disregarded. 
![2022-04-07-09:47:14](https://user-images.githubusercontent.com/1130872/162180869-dde7427d-cc0f-4c75-8a67-cdd179fdbea3.png)

**Comment by zone117x** [comment]
We're looking into this right now. Will update when I have more details, but aiming to have a fix deployed today or tomorrow if possible.

**Comment by zone117x** [comment]
This should be fixed right now. We swapped to a db that was successfully able to resolve ft metadata. 

Still not clear why the previously live deployment had issues resolving the ft metadata -- we've never seen that before. We have an existing issue tracking improvements to ft resolving retrying: https://github.com/hirosystems/stacks-blockchain-api/issues/1007 and an in progress PR for it. 

Closing this issue. Please comment if anyone still sees missing data.

**Comment by wbnns** [comment]
Confirming we can see this is resolved. Thank you all so much for the quick assistance and help here!

**Comment by wbnns** [comment]
@zone117x @sabbyanandan @saralab Hello, it seems this issue has gotten reintroduced into production.

**Comment by wbnns** [comment]
Cc: @markmhx

**Comment by markmhx** [comment]
Thanks, yea this seems related to https://github.com/hirosystems/stacks-wallet-web/issues/2385#issuecomment-1118414926

**Comment by saralab** [comment]
@wbnns Whilst the long term fix [1007](https://github.com/hirosystems/stacks-blockchain-api/issues/1007) is in progress, we managed to force refresh the metadata across our environments for a quick fix.  You should the FT metadata now.

**Comment by saralab** [comment]
@wbnns Whilst the long term fix [1007](https://github.com/hirosystems/stacks-blockchain-api/issues/1007) is in progress, we managed to force refresh the metadata across our environments for a quick fix.  You should the FT metadata now. 

Thanks a tonne for quick turnaround @zone117x @rafaelcr @CharlieC3 !
