### ISSUE TITLE
ability to specify a FT whitelist in Rosetta to filter out irrelevant txs in results

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1147]
(All explanations will be based on [AVAX's implementation](https://github.com/ava-labs/avalanche-rosetta) for ERC20 support)

### Config
the Rosetta API should enable a ["token whitelist"](https://github.com/ava-labs/avalanche-rosetta/blob/2b309ff13b198940e0f62bea839d9ab1476f806d/cmd/server/config.go#L33) (included as a field in the Rosetta server config) to specify which token transfers [actually need to be indexed](https://github.com/ava-labs/avalanche-rosetta/blob/2b309ff13b198940e0f62bea839d9ab1476f806d/mapper/transaction.go#L85-L87).

### Data
To allow indexing of token transactions, Rosetta users need to track the following:
- Token currency
- Transfer amount
- From and To addresses
- The on-chain operation being performed

Token transfers should be represented by leveraging the `Amount` field of the Rosetta `Operation` type (see [example](https://github.com/ava-labs/avalanche-rosetta/blob/2b309ff13b198940e0f62bea839d9ab1476f806d/mapper/transaction.go#L474-L497)). The Amount field includes the subfields `Currency`, `Decimals` and `Value`. These should be populated with the token currency, the token’s decimal precision, and the amount of the token being transferred.

The `Type` field should indicate that a token transfer is being performed.

Just like for native currency transactions, Rosetta operations representing token transfers should be single-sided, meaning that for a single token transfer there should be _two_ operations––one representing the send and one the receive.

**Token transfer data should NOT be included exclusively in the Metadata field of the Operation.**

### Construction
Similarly to the Data API implementation, the Construction endpoints should allow transaction construction with a token currency and token transfer operation type to be passed in as parameters.

**Comment by smcclellan** [comment]
Will not be addressed due to decreased mainteinance on Rosetta.
