### ISSUE TITLE
Add block height to NFT holdings API

### ISSUE THREAD

**Issue by Jamil** [hirosystems/stacks-blockchain-api#1149]
**Is your feature request related to a problem? Please describe.**
A common use case is to sort NFT holdings by when you acquired them. For example, we use an API for our NFT holdings that provides the block height so we can sort by recency in the STXNFT profile view: https://stxnft.com/jamil.btc

**Describe the solution you'd like**
Adding a field for block height in the holdings API, for example:
```
{
      "asset_identifier": "SP2BE8TZATXEVPGZ8HAFZYE5GKZ02X0YDKAN7ZTGW.arties::arties",
      "value": {
        "hex": "0x0100000000000000000000000000000663",
        "repr": "u1635"
      },
      "block_height": 38749,
      "tx_id": "0x07965b79971bab960a731450ffbedb9879bdb91a2adf5e4631ae424cb77336b4"
    },
```

**Comment by Jamil** [comment]
Wow, this is wonderful and such a fast turnaround — thank you @rafaelcr and @MHassanTariq!

**Comment by MHassanTariq** [comment]
@Jamil you're very welcome. :)
