### ISSUE TITLE
Fix /v1/names/[NAME] from returning old owner addresses

### ISSUE THREAD

**Issue by markmhx** [hirosystems/stacks-blockchain-api#1158]
As originally reported with https://github.com/hirosystems/stacks-wallet-web/issues/2394#issuecomment-1114258999

**Comment by rafaelcr** [comment]
This could be a regression on `4.0.0-beta` cc @zone117x @saralab 
I'll investigate

**Comment by markmhx** [comment]
Note that it appears intermittent on refresh: https://github.com/hirosystems/stacks-wallet-web/issues/2394#issuecomment-1114264199

**Comment by rafaelcr** [comment]
I just disabled 4.0.0-beta canary traffic, which is what was causing the intermittent issue @markmhx

**Comment by rafaelcr** [comment]
Update: this is not a regression in 4.0.0-beta but a very old re-org bug that started to surface when .btc marketplaces started transferring names. Working on a quick fix to deploy.

**Comment by rafaelcr** [comment]
@pseudozach we were planning on shipping it this week, but we learned that unfortunately there is a breaking change in how we return `repr` strings that will affect marketplaces/apps so we are going to do more to communicate to other developers what is changing before releasing it. See: https://discord.com/channels/621759717756370964/909867922971820102/971419334171824128
