### ISSUE TITLE
Name transfer is not reflecting in the API

### ISSUE THREAD

**Issue by cryptocracy** [hirosystems/stacks-blockchain-api#1172]
**Describe the bug**
After users obtain a name by purchasing it through a smart contract, the api does not seem to update to indicate name transfer.

**To Reproduce**
Steps to verify the behavior:
You can analyze the recent `god.btc` being acquired via Byzantions BNS marketplace contract.

Analysis of the `god.btc` transfer is:

per tx: `0x1b9056a3c478b07ab988f59c37528f3aab4f0b1df39ce5605c66fad076d5871c` the accept-bid confirmed and invoked by `SP1XQMABWMVAMXCP2AW2EJQ1TGE95HPVZB84G63SD`

per that tx: `SP1XQMABWMVAMXCP2AW2EJQ1TGE95HPVZB84G63SD` was the original owner and they got paid the expected amount (after fee) 

per that tx: `SP1SPNA0B4RMNBY4HBG7K5GGB10BJ56NPNMBESM1Y` was the intended new owner/receiver of the name.

per api lookup of names owned by the *supposed new owner* address: `https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP1SPNA0B4RMNBY4HBG7K5GGB10BJ56NPNMBESM1Y`
returns: 
```json
{
  "names": []
}
```
per api lookup of names owned by the *supposed old owner* address:
`https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP1XQMABWMVAMXCP2AW2EJQ1TGE95HPVZB84G63SD`
returns:
```
{
  "names": [
    "god.btc"
  ]
}
```
Note: I realize these are reverse lookups(address to name), but the same is true for a direct lookup(name to address).

**Expected behavior**
API to pick up on name transfers instigated by smart contracts.

**Additional context**
You can confirm the transfer transaction is onchain via:
[https://stacksonchain.com/query?query=select%2520*%2520from%2520nft_events%2520where%2520recipient%2520%253D%2520%27SP1SPNA0B4RMNBY4HBG7K5GGB10BJ56NPNMBESM1Y%27%2520](https://stacksonchain.com/query?query=select%2520*%2520from%2520nft_events%2520where%2520recipient%2520%253D%2520%27SP1SPNA0B4RMNBY4HBG7K5GGB10BJ56NPNMBESM1Y%27%2520)

**Comment by friedger** [comment]
This looks like a P1 bug because assets can be lost by sending it to the wrong user

**Comment by friedger** [comment]
Same for this name transfer of a different namespace: https://explorer.stacks.co/txid/0xd3c4c17b11326f9c650d59a4a6049a3156cd940a4d0cfbed116f7002bde00123?chain=mainnet

**Comment by rafaelcr** [comment]
This seems to be a very similar issue to the one fixed here: https://github.com/hirosystems/stacks-blockchain-api/pull/1159
Basically, the endpoint does not correctly reflect BNS name transfers (the underlying NFT transfer events), only zonefile changes. We'll take a look ASAP

**Comment by rafaelcr** [comment]
@cryptocracy while we fix the issue, you can use the NFT holdings endpoint to get the correct response: https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/nft/holdings?principal=SP1SPNA0B4RMNBY4HBG7K5GGB10BJ56NPNMBESM1Y
The name will be returned as a hex clarity value, though, but it's there.
