### ISSUE TITLE
Address any remaining name resolution issues with BNS endpoints

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/stacks-blockchain-api#1177]
As we continue to resolve one-off issues reported on BNS name resolution (see: https://github.com/hirosystems/stacks-blockchain-api/pull/1159 / https://github.com/hirosystems/stacks-blockchain-api/pull/1175), it'd be helpful to review all the BNS endpoints to make sure the BNS names are resolved correctly for all of them.

discussion point:
There are V1 and V2 endpoints, and a transaction that spawns either or both the endpoints require a different strategy for name resolution.

**Comment by rafaelcr** [comment]
Relevant issues:

- [ ] https://github.com/hirosystems/stacks-blockchain-api/issues/1273
- [ ] https://github.com/hirosystems/stacks-blockchain-api/issues/1269
- [ ] https://github.com/hirosystems/stacks-blockchain-api/issues/1177
- [ ] https://github.com/hirosystems/stacks-blockchain-api/issues/1176
- [ ] https://github.com/hirosystems/stacks-blockchain-api/issues/1088

**Comment by friedger** [comment]
This one as well: #1291
