### ISSUE TITLE
Transactions API only shows first 96 events

### ISSUE THREAD

**Issue by Jamil** [hirosystems/stacks-blockchain-api#1178]
For transactions with > than 96 events, it seems only the first 96 events are returned in the tx endpoints.

For example: 
https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x85d84dc0214f5a72540a12984a37bc6b52089fe1d00db1b281c22cf47c926b65

`"event_count": 295`

but "events" is only an array of size `96`.

**Comment by zone117x** [comment]
Hi @Jamil, tx events are paginated. Please see the docs for this endpoint at https://hirosystems.github.io/stacks-blockchain-api/#operation/get_transaction_by_id
