### ISSUE TITLE
Empty zonefile after name-update

### ISSUE THREAD

**Issue by friedger** [hirosystems/stacks-blockchain-api#1189]
**Describe the bug**
A new registered bns name, that received a name-update call but now the api does not return a value for zonefile, e.g. https://stacks-node-api.mainnet.stacks.co/v1/names/web3.id
There are lots of rows with empty values for column `zonefile` in the zonefiles db, however the names has the correct zonefile hash value.

**To Reproduce**
1. Go to https://stacks-node-api.mainnet.stacks.co/v1/names/web3.id
2. See the empty zonefile
3. query the data base `select * from zonefiles z where zonefile_hash = '1ccb4f2eb8105b91c4f843c13a5ab24f029e0bbc'
order by id desc`
4. See empty column

**Expected behavior**
The zonefile property should be filled with the content of the zonefile 
``` 
$ORIGIN web3.id.
$TTL 3600
_http._tcp	IN	URI	10	1	"https://gaia.blockstack.org/hub/16EopwQq3YdDZaT8fNe4FCQgyY55WRt32N/profile.json"

```

**Additional context**
While investigating with @pradel how to fix the blog on sigle for web3.id

**Comment by asimm241** [comment]
@friedger how do you make the call to `name-update`. I can't reproduce the bug on my end. 
The zone file is updating locally. We are also making a `name-update` call in the subdomain-registrar which is also successfully updating the zone file. 


here is how I make name update call: 

`async function nameUpdate(name: string,attachment: string) {
  const txOptions = {
    contractAddress: deployedTo,
    contractName: deployedName,
    functionName: 'name-update',
    functionArgs: [
      bufferCV(namespace),
      bufferCVFromString(name),
      bufferCV(hash160(Buffer.from(attachment))),
    ],
    senderKey: pkey,
    validateWithAbi: true,
    network,
    anchorMode: AnchorMode.OnChainOnly
  };

  const transaction = await makeContractCall(txOptions);

  const txHex = transaction.serialize().toString('hex');
  const aHex = Buffer.from(attachment).toString('hex');
  console.log(
    `curl -v -H "content-type: application/json" --request POST --data '{"attachment": "${aHex}", "tx": "${txHex}"}' http://localhost:20443/v2/transactions`
  );
}`

`curl -v -H "content-type: application/json" --request POST --data '{"attachment": "", "tx": "8080000000040062b0e91cc557e583c3d1f9dfe468ace76d2f0374000000000000000700000000000000cf000070e1c38331d57fdc96953f49daf14b340a950f3997ab9e9f648dda369a679ee418f011e504d3a245fca0169c4704777beee74cc55c2d12c14e7b62af9f810d69010200000000021a000000000000000000000000000000000000000003626e730b6e616d652d757064617465000000030200000007746573745f69640200000008746573745f73747802000000149cf30b12fb01f6431443521d24438e95cc2cdbf7"}' http://localhost:20443/v2/transactions `

**Comment by friedger** [comment]
@asimm241 
I use Hiro wallet like this
```
const ZONEFILE_TEMPLATE =
        "{$origin}\n{$ttl}\n{uri}\n{a}\n{aaaa}\n{cname}\n{mx}\n{srv}\n{txt}\n";
      const zoneFileOptions = {
        $origin: "web3.id.",
        $ttl: 3600,
        uri: [],
      };

      const token = decodeToken(stacksUser.authResponseToken);
      const profile_url = token.payload.profile_url;
      console.log(stacksUser, userSession);
      zoneFileOptions.uri.push({
        name: "_http._tcp",
        priority: 10,
        target: profile_url,
        weight: 1,
      });

      const zonefile = makeZoneFile(zoneFileOptions, ZONEFILE_TEMPLATE);
      console.log(zonefile, zonefileHash(zonefile).toString("hex"), parseZoneFile(zonefile));
      const hash = zonefileHash(zonefile);
      doContractCall({
        contractAddress: BNS_CONTRACT.address,
        contractName: BNS_CONTRACT.name,
        functionName: "name-update",
        functionArgs: [
          bufferCVFromString("id"),
          bufferCVFromString("web3"),
          bufferCV(hash),
        ],
        attachment: zonefile,
        network: new StacksMainnet(),
        onFinish: (data) => {
          console.log(data);
        },
      });
```

**Comment by asimm241** [comment]
@friedger, I debugged it locally, and the only way I could reproduce is if I don't provide the attachment while broadcasting the transaction to `v2/transactions`. 

```
  const txOptions = {
    contractAddress: deployedTo,
    contractName: deployedName,
    functionName: 'name-update',
    functionArgs: [
      bufferCV(namespace),
      bufferCVFromString(name),
      bufferCV(hash160(Buffer.from(attachment))),
    ],
    senderKey: pkey,
    validateWithAbi: true,
    network,
    anchorMode: AnchorMode.OnChainOnly
  };

  const transaction = await makeContractCall(txOptions);

  console.log(`use curl for name-update: ${name}`);
  const txHex = transaction.serialize().toString('hex');
  const aHex = Buffer.from(attachment).toString('hex');
  console.log(
    `curl -v -H "content-type: application/json" --request POST --data '{"attachment": "", "tx": "${txHex}"}' http://localhost:20443/v2/transactions`
  );
```


```
curl -v -H "content-type: application/json" --request POST --data '{"attachment": "", "tx": "8080000000040062b0e91cc557e583c3d1f9dfe468ace76d2f0374000000000000000d00000000000000cf0001dca3a5b903ff2969bbd1ad6de7efc048c29242ddf35740e0be26b3504b4add6650984dc4d97405a52549f8fed77c42609fc8fe4862709e5816bf2f94176849d7010200000000021a000000000000000000000000000000000000000003626e730b6e616d652d757064617465000000030200000007746573745f69640200000008746573745f7374780200000014aa9089575d54ff03c1bc18b7e0dad605e9067599"}' http://localhost:20443/v2/transactions
```

 I think the bug is in the [connect](https://github.com/hirosystems/connect/blob/main/packages/connect/src/transactions/index.ts#L156) code. I have been dry running code there but couldn’t say for sure as I don't have much grip on the front end. 
 if someone from wallet can confirm the request payload that would be helpful here.

**Comment by friedger** [comment]
This is the code used for broadcasting tx with attachement: https://github.com/hirosystems/stacks.js/blob/ee8eb8c138f91ac3264a75a4e05a27721f749153/packages/transactions/src/builders.ts#L420

**Comment by friedger** [comment]
@asimm241 Do you still get the empty entry in the database ?

**Comment by friedger** [comment]
Updating the zonefile manually works. The problem is more in the wallet or stacks.js
