### ISSUE TITLE
NFT Metadata processing is not enabled on this server

### ISSUE THREAD

**Issue by albydeca** [hirosystems/stacks-blockchain-api#1199]
**Describe the bug**
When accessing
 ```
https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/SP3PN1GRGNNV6KKS47XN34TJZ6MGBGC40G7KFEGMW.cool-ape::cool-ape/nft/metadata/
```

The following error (HTTP 500) is shown:

```
{
    "error": "NFT metadata processing is not enabled on this server"
}
```
Trying a few different contract IDs result in the same error.

**To Reproduce**
Self-explanatory from description above. In my specific case I use Postman on Mac.

**Expected behavior**
A list of JSON objects should be returned, of the following type:

```

{
  "token_uri": "https://pool.friedger.de/nft.json",
  "name": "Friedger Pool",
  "description": "Enjoying the stacking pool.",
  "image_uri": "https://pool.friedger.de/nft.webp",
  "image_canonical_uri": "https://pool.friedger.de/nft.webp",
  "tx_id": "0xef2ac1126e16f46843228b1dk4830e19eb7599129e4jf392cab9e65ae83a45c0",
  "sender_address": "ST399W7Z9WS0GMSNQGJGME5JAENKN56D65VGMGKGA"
}
```

**Comment by rafaelcr** [comment]
@albydeca the Hiro API doesn't support NFT metadata yet, as the SIP that standardizes this has not been ratified https://github.com/stacksgov/sips/pull/44
