### ISSUE TITLE
Refactor the Token Metadata Processor into an independent service

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1222]
### Background

Our Stacks API currently exposes [a few endpoints](https://docs.hiro.so/api#tag/Fungible-Tokens/operation/get_contract_ft_metadata) that attempt to serve FT metadata. This data is pulled by a background queue that listens to new contracts as they are deployed to the blockchain, but it does not handle token metadata update notifications, NFTs or SFTs. It currently is a complex part of the API that we’re looking to compartmentalize as an external system.

The goal of this issue is to track the process in building a new metadata micro-service, an independent system that manages its own internal logic separately from the API and that can be deployed and scaled separately.

### Features

The new Token Metadata Service will support the following token metadata standards:

1. NFTs ([SIP-009](https://github.com/stacksgov/sips/blob/main/sips/sip-009/sip-009-nft-standard.md))
2. FTs ([SIP-010](https://github.com/stacksgov/sips/blob/main/sips/sip-010/sip-010-fungible-token-standard.md))
3. SFTs ([SIP-013](https://github.com/stacksgov/sips/pull/42))
4. Token metadata update notifications (https://github.com/stacksgov/sips/pull/72)

NOTE: This service will only process and consume token metadata that follows the guidelines set by SIP-016: https://github.com/stacksgov/sips/pull/44

After processing, all data will be exposed through REST endpoints for external services to consume (endpoint specification TBD).

**Comment by saralab** [comment]
This has been release in alpha and not yet deployed, closing this.
