### ISSUE TITLE
expose mempool data onto Prometheus

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1224]
During high blockchain traffic, we'd like to be able to quickly determine some details about the mempool:

* Current size, divided by tx type
* Current fee stats (P95, P50, etc.)
* Current tx age stats (P95, P50, etc.)
* etc.

There's an open issue (https://github.com/hirosystems/stacks-blockchain-api/issues/982) about exposing this data as a new endpoint in the API, but in the meantime, adding to Prometheus would be a win because we could generate dashboards quickly and we'd be able to debug what's going on much faster. cc @gregorycoppola

**Comment by gregorycoppola** [comment]
Also important to know "nonce status" -- correct/too-low/too-hight.
