### ISSUE TITLE
feat: Return list of mempool tuples, not just ID's

### ISSUE THREAD

**Issue by gregorycoppola** [hirosystems/stacks-blockchain-api#1226]
**Is your feature request related to a problem? Please describe.**
Right now, it is not efficient to get the entire contents of the mempool from the API.

We first have to query for the list of `txid`'s, and then, *for each* `txid`, we have to query for the transaction data. This leads to more queries than can be done in one minute for basic user with rate limiting.

Definitely, I want to be able to query for all this data, and to know the entire mempool contents, e.g., to do offline analysis. But, I could use a backend.

However, for regular users, if the want the contents of the mempool, maybe they want the full list of transactions?

**Describe the solution you'd like**
Make an endpoint where the list of _tuples_ characterizing the mempool is returned. 

I.e. each tuple being like:

```
{
    tx_id: '0x00c17c069179e489cff273d29b41b2393b3480a207d151c66486db68a6dbf2d7',
    nonce: 2631,
    fee_rate: '3881',
    sender_address: 'SP3Z7511VWR5WG9J3MAKER3NRZYKWT83K2XTP36EV',
    sponsored: false,
    post_condition_mode: 'deny',
    post_conditions: [ [Object], [Object] ],
    anchor_mode: 'any',
    tx_status: 'pending',
    receipt_time: 1657031382,
    receipt_time_iso: '2022-07-05T14:29:42.000Z',
    tx_type: 'contract_call',
    contract_call: {
      contract_id: 'SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.swap-helper-v1-03',
      function_name: 'swap-helper',
      function_signature: '(define-public (swap-helper (token-x-trait trait_reference) (token-y-trait trait_reference) (dx uint) (min-dy (optional uint))))',
      function_args: [Array]
    }
  }
```

**Describe alternatives you've considered**
This could be done through a backend query instead of through the API.

**Comment by sabbyanandan** [comment]
Just wanted to document that the https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/mempool endpoint returns the required information.
