### ISSUE TITLE
re-orgd transactions return 404 if they weren't in the mempool before

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1231]
When a transaction is re-orgd because a new block came by which made it non-canonical, it is normally thrown back into the mempool so we show it again as `pending`. However, if there is a case when that same transaction wasn't seen in the mempool before being seen in the block, that same re-org makes it disappear from the API.

This is because the re-org calls `restoreMempoolTxs` which only `UPDATE`s the `mempool_txs` table, but in that case there is no row that can be updated. We should make it so that if this happens, we somehow try to `INSERT` it into the mempool table even when we didn't see it before.

**Comment by BLuEScioN** [comment]
https://github.com/hirosystems/stacks-blockchain-api/pull/1429
