### ISSUE TITLE
`/v1/names/{name}` does not reflect buying usernames from bids on marketplaces

### ISSUE THREAD

**Issue by pradel** [hirosystems/stacks-blockchain-api#1236]
**Describe the bug**

I am not sure if this is a bug or intended behaviour. Creating the issue to open discussion regarding the behavior of the `/v1/names/{name}` endpoint.

Problem: When buying a new .btc domain via a bid from a marketplace, the `/v1/names/{name}` seems to return outdated data.

The https://stacks-node-api.mainnet.stacks.co/v1/names/dayslikewater.btc endpoint, return the `last_txid` field with the transaction that registered the name. In the payload, we can see that `SP1TY00PDWJVNVEX7H7KJGS2K2YXHTQMY8C0G1NVP` is the current owner of this name (which is correct), but the `last_txid` [explorer link](https://explorer.stacks.co/txid/0x1316b570d85db81792b7fc18e7d7ec502ec886008e9b9be1f4bf891b4ab8380a?chain=mainnet) point to a transaction made by `SPP117ENNNDQVQ1G3E0N1AP178GXBTC2YNQ3H7J`. `SPP117ENNNDQVQ1G3E0N1AP178GXBTC2YNQ3H7J` is the account that bought the username at the beginning and then sold it to `SP1TY00PDWJVNVEX7H7KJGS2K2YXHTQMY8C0G1NVP`.

Shouldn't this endpoint reference the bid transaction in the `last_txid` result as the owner changed in this process?

**Expected behavior**

The https://stacks-node-api.mainnet.stacks.co/v1/names/dayslikewater.btc endpoint should return the last `last_txid` when the name was transferred to the new account.

**Comment by rafaelcr** [comment]
This looks to be related to https://github.com/hirosystems/stacks-blockchain-api/issues/1176 which is blocked by an issue on the Stacks blockchain itself

**Comment by rafaelcr** [comment]
Related to #1287

**Comment by rafaelcr** [comment]
@pradel can you share the explorer link for the transaction that transferred this name via marketplace bid?

I think what's happening is that the API is only programmed to detect `name-transfer` events initiated by calling the BNS contract directly as opposed to those made to BNS by other contracts. It could be a simple fix but I'd need to see the original tx.

Thanks

**Comment by pradel** [comment]
@rafaelcr I think this is the transaction https://explorer.stacks.co/txid/0xa75ebee2c824c4943bf8494b101ea7ee7d44191b4a8f761582ce99ef28befb19?chain=mainnet

**Comment by rafaelcr** [comment]
Thanks for the quick response @pradel
