### ISSUE TITLE
Include `index_block_hash` in the /block endpoint

### ISSUE THREAD

**Issue by philipdesmedt** [hirosystems/stacks-blockchain-api#1238]
**Describe the bug**

When using the `tip` parameter on the read-only function call (https://hirosystems.github.io/stacks-blockchain-api/#tag/Smart-Contracts/operation/call_read_only_function), it is not clear which tip (hash) it expects. For example, the hash `ab61ba097c33eba57863249d82ce4e082e33d6b8c72f9279ae175536ed9da93c` on https://stacks-node-api.mainnet.stacks.co/extended/v1/block/0xab61ba097c33eba57863249d82ce4e082e33d6b8c72f9279ae175536ed9da93c returns `Chain tip not found`.

With some help on Discord, we figured out it expects `index_block_hash`, but this is not exposed anywhere through the API.

**To Reproduce**

```
curl "https://stacks-node-api.mainnet.stacks.co/v2/contracts/call-read/SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR/arkadiko-governance-v3-1/get-proposals?tip=ab61ba097c33eba57863249d82ce4e082e33d6b8c72f9279ae175536ed9da93c" \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'pragma: no-cache' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-gpc: 1' \
  --data-raw '{"sender":"SPX8T06E8FJQ33CX8YVR9CC6D9DSTF6JE0Y8R7DS","arguments":[]}' \
  --compressed
```

The above returns `Chain tip not found`. Without the tip parameter the call works (but we need to query in the past). I suppose passing the `index_block_hash` would work, but it's not clear where this hash can be found.

Hope that helps!

**Comment by zone117x** [comment]
IMO this is an oddity (potentially a bug / oversight) in the `?tip=<value>` parameter used in the [`/v2/...` endpoints](https://github.com/stacks-network/stacks-blockchain/blob/master/docs/rpc-endpoints.md). 

The `tip` parameter supports `microblock_hash` but not `block_hash`, and I think it's the only area in the RPC endpoints or API endpoints that use the `index_block_hash`. The `index_block_hash` value is otherwise only used internally within the stacks-node event emitter interface and db re-org code, and not exposed publicly anywhere except for `/v2/info` where the value is named `stacks_tip_consensus_hash`, e.g.:

https://stacks-node-api.mainnet.stacks.co/v2/info
```json
{
  "peer_version": 402653189,
  "pox_consensus": "7df022c03e5d33dfe45a3ec9a80d9404c4e88527",
  "burn_block_height": 745603,
  "stable_pox_consensus": "46b4e1e77dfa75c2044cd8698d327bb7947fefd4",
  "stable_burn_block_height": 745596,
  "network_id": 1,
  "parent_network_id": 3652501241,
  "stacks_tip_height": 68258,
  "stacks_tip": "179b0297b06733a96549ff4216816997fd6bb680e7dc3bf351fa7f4634708923",
  "stacks_tip_consensus_hash": "7df022c03e5d33dfe45a3ec9a80d9404c4e88527", <----
  "genesis_chainstate_hash": "74237aa39aa50a83de11a4f53e9d3bb7d43461d1de9873f402e5453ae60bc59b",
  "unanchored_tip": "edf4245dd100815e72d1c53a0121072a055cd824b89f4bbf506ee75fd7f9c9c4",
  "unanchored_seq": 0,
  "exit_at_block_height": null,
  "node_public_key": "0291949a58fe5f331f272fed3830f7b45e7e23157e933f1e109e96b6fb7489085d",
  "node_public_key_hash": "e9af2766ab040b9eca56730876e12d280192f187"
}
```

I think an issue should be opened in https://github.com/stacks-network/stacks-blockchain to improve/fix the `tip` param. 

In the mean time, we could add this value to the block response bodies, but the name `index_block_hash` is confusing, and inconsistent with the `/v2/info` naming. So if we add it, we should probably name it `stacks_tip_consensus_hash`.

**Comment by philipdesmedt** [comment]
@zone117x I opened an issue on the `stacks-blockchain` repo, but if you could include the `stacks_tip_consensus_hash` in the `/block` endpoint, that would help as well, even to use this as a temporary fix?

Issue URL: https://github.com/stacks-network/stacks-blockchain/issues/3205

**Comment by talhasch** [comment]
It's a killer feature of Stacks to read historical data from smart contract using tip query. A temporary fix could be so useful.

**Comment by jcnelson** [comment]
> @zone117x IMO this is an oddity (potentially a bug / oversight) in the ?tip=<value> parameter used in the /v2/... endpoints.

No, it's intentional.  The index block hash is the only hash that can uniquely identify an anchored block or an unconfirmed state trie.  A block can be valid in two or more PoX histories, which is why the block hash alone is not good enough for identifying a particular chain tip.


> @zone117x The tip parameter supports microblock_hash but not block_hash, and I think it's the only area in the RPC endpoints or API endpoints that use the index_block_hash. The index_block_hash value is otherwise only used internally within the stacks-node event emitter interface and db re-org code, and not exposed publicly anywhere except for /v2/info where the value is named stacks_tip_consensus_hash, e.g.:

The `tip=` parameter is _always_ one of these two things:

* An index block hash of a Stacks block that the node knows about
* The identifier of the unconfirmed state trie (which itself is derived from the canonical chain tip's index block hash)

No RPC endpoint uses the block hash on the node for identifying blocks.  It's _always_ the index block hash.  Also, confirmed microblock streams are identified by the index block hash of their parent anchored blocks.

**Comment by jcnelson** [comment]
The index block hash is derived from state given in `/v2/info` -- it's the SHA512/256 hash of the `stacks_tip_consensus_hash` value (a `ConsensusHash`) concatenated with the `stacks_tip` value (a `BlockHeaderHash`).  You can derive the `StacksBlockId` as follows:

```
#!/bin/sh

CONSENSUS_HASH="$1"
BLOCK_HASH="$2"

if [ -z "$BLOCK_HASH" ] || [ -z "$CONSENSUS_HASH" ]; then
   echo >&2 "Usage: $0 CONSENSUS_HASH BLOCK_HASH"
   exit 1
fi

echo -n "${BLOCK_HASH}${CONSENSUS_HASH}" | xxd -r -p | openssl dgst -sha512-256 - | cut -f 2 -d ' '
```

**Comment by philipdesmedt** [comment]
@jcnelson thanks for that!

How would we build the index block hash using a historical `/block` endpoint? For instance which two fields should we concatenate from https://stacks-node-api.mainnet.stacks.co/extended/v1/block/by_height/60000?

**Comment by jcnelson** [comment]
You'd need to know the consensus hash for the associated Bitcoin block.  It doesn't look like `/block` supplies this.

**Comment by jcnelson** [comment]
What you can do right now is walk the header history on the node.  It gives the index block hash for each parent block:

```bash
$ curl -sL http://seed-0.mainnet.stacks.co:20443/v2/headers/10 | jq
[
  {
    "consensus_hash": "b5834867ec9c8bdf8e282d5a4a8198a6a6018673",
    "header": "000000003089a106930000000000010c2ed02db32f257392fc7dd1bde7df3e5dbd99be7f904cc54d159f98e5ec86c16759d2641a4cfee17e31370ca8eff65c45109bc6a068708b2fcc7f67223493827c59702962bfc5f8794d4451fa8765af690180fb66bb2b1173bc2b9ad37a453ee43014edd8e524f9d799dcfc3d35623e02ef00000000000000000000000000000000000000000000000000000000000000000000477b25a40cf260aad36334d8c2d73e29ca63ca866807ef2fde88227048296f8e82cb99c2c63e82e11908c69751812d408a9f01badc9a47069e1cc26cdf314c26c80aa0a7d8c53699b5211f37a9a369b61221b97a",
    "parent_block_id": "9d4cab5845754e89818c2081938d86afb9b99ef3f3360bb6ba34b4d0a4248106"
  },
  {
    "consensus_hash": "5efd5f4eca1e218e1bcba5504f22fa50cbe081b8",
    "header": "000000003089828fc90000000000010c2d5716a894d32123f935b9eaa3da6a6bdf8c191718016293a840e8927dced0ba14a4bed3aa373944d818637fd7bcd4a42aa289c33765056155ec60b4336316b8d868a8ebb099e69d2d8a8e3ef39f4e960d57dc295466079c9842d07523d0a24f0f0d4a030a79509ae31f384e78db603ab3c357c62498d767df57ace30a5eba8c4a22b93c6feddc785bf7d27cc7ba9c409e0004a92ae4bb0ae336a8f879d712b7745ae0fe52f27549084cbe3198af4e693348ce48136b2a74f0662b1cc169f20173bb50605949412a5167d20339d5042b8007da0f54d5263d5ef2f27256d93ba060294645f7db8a",
    "parent_block_id": "6e2cc97e242d272cefa4ec0527e991c499b879085ce4a074c6106293b3b521eb"
  },
  {
    "consensus_hash": "3a4bdfd5f071f382c23a6b9791c299b9b84d22c4",
    "header": "0000000030896418ff0000000000010c2c5eaeb62126b0576f93fd5cbbbe0365789bc88690fc34378bd1f130984a528f0cee57a766d12002f805c982e2261d5166d248e6da987285b2b6b70c3f2c5120eb5d152cbef97d7088e8a640e50302de0ffdd068bcee27ef1ea604a6c39f2f1f69a8a79049f42d613e33584ec77c4779d900000000000000000000000000000000000000000000000000000000000000000000faed64e344191f568e9e8571b1b7874afd2449069c83370a198c76a25bca3265e638282022b9f04d0d1d99208b975a2f95c6e222fa6701bef21cc20dd394d2777ce85c88452063c0e64fd75ff1c89c988f3334d0",
    "parent_block_id": "ecc670a30d1aba947166a0db78eb26b6c60acf91319b28203beee8f7a4e0db77"
  },
  {
    "consensus_hash": "89bbe2585bb3b319bf4f92ecd0998b79d36e24b4",
    "header": "00000000308945a2350000000000010c2be04ad4e57146f438dd6fa930696e0be4b7e1546d3fd45dfe4c8710b98162a54b568ff30fcc7aa0e49b09cb3cfa40ad525a718c48b2a12a950053ceb5dde3e920b1e0c27dea81f25866b9d17cad584c0368afb73db0d4f520d7827b5eafb92f05a80fdc48cf77370cca26179d68b2321eeeecee6e08e4902aeacbedca0e48b9f2f62dd1f6144960c6b3496afcbe95617d0000bbde65f0f3bb28e8de2edcd8959612c02cbcbde87f85eb5943e17a23596adeabaf74680bfedd9d1ab93f5dcc7a5b9ad841f1039f65f538ce2e4b86217df31643aad507819e3215d34a23ccf138c81838c21b8b72",
    "parent_block_id": "0d5853f089b153ac42c243b600a1070f8919e915e21eae438c2edbf4fa2c862e"
  },
  {
    "consensus_hash": "702cb544afd74b1ce354e23ed5cf2e8e0a36682f",
    "header": "0000000030892a119b0000000000010c2a128f047074a105bc3ff0f7414c2f587aa25ceaa452fa1ffbca29c0e64758f4350876d904ed7c70cacb391d7805c25014821ac8ba8f4aaf09588d88404a0da5a76d10c7b4a3f53b11c2d66d8befbdb20d78efabdd2825e167711f2bd665e8863399e93c1b7900457cb9d58b1d4e95ccbf000000000000000000000000000000000000000000000000000000000000000000002643f2156980f6068dcfef96ca92eb443f55027eb799e69c805f04b77079f8c84567a83f45ae56a41e7687e42caa0ff2217c1320a427085a047e93d6412fb8e5a7e196c114a0c12f39fa127dba7eabce107e2a1c",
    "parent_block_id": "f5e290b913851671707afbc2afe4c16509df27117ba2da9e3f372923fa133d9f"
  },
  {
    "consensus_hash": "17dc5105d6622a45f027a244715cb745dcc9cce4",
    "header": "0000000030890b9ad10000000000010c29b1c97f80255dd2a87dc218f95133abd9092bf3e1674a9129c673342bda03ce1e5d9b05ed9c55a5201e1c11f55943e7bd05de809ce3810f0b9672f01781dbcc56d517b954e027ea1450e9248e4a34020f00f4f2b9d7577bd47dec22611215eb01a00cf945020640785e4b4545071874f5b9a91671f423879a036dcf9243dc1e91437bf96b1b220922339b5a3c217d6a990008c749fd8b03d23589e9049f02e418ab5656944cd8f45ff31a026c518f9f238c003d72017fee19d93df277a16d646028bccf352838761b3c3207b99242dac5e40c533bfe2d6f01122434d05f857786a8a4ebf457d1",
    "parent_block_id": "aa3f637b31f44804b5aef26369e82e85616910574dfbc111515c36f4da4dc3ec"
  },
  {
    "consensus_hash": "cb640f4f435fc635e0f2117f1ccba18be6d9d66c",
    "header": "000000003088ed24070000000000010c28fe61013cbe5d41e9ff9e6c7254e46b0d15383a095bf845ecb3d24b13734a356cbdd61794d19cf9dff6cf4e92be51f5c1dcd4bd824d3f4228d895eeae405e99c146217df273118a1b0b946eae646ab20cb2e91630d8d312364f24a07e414a7afe666106297dd1b186b44386d72e00873b0000000000000000000000000000000000000000000000000000000000000000000037a4913d498c73784cee92a376b7731676e63d02edd271be6129d92db174dac385e037b45a0f7ef699f5363c280a33f426c4f3ec3d3366e1435daefba2d12a4451bc58dddc68652aaa0d500001f8d6fd3fe5f9a9",
    "parent_block_id": "2f233289a38a53c0d02d832b75b486a3b530ffa5a13cd869c01d80b4b464b206"
  },
  {
    "consensus_hash": "27c2cf6f04101e9754713c0d873c17be9782a3f1",
    "header": "000000003088cead3d0000000000010c2767cdddecbb02d3549650059a06969be49ae01eb66ec890c097f24e860c51dd8615a2d07102d425d9034475536f3a3a60463be303098840e90f7fd2d0552be63df3f0ed00a1d6c3b33a4203cb9ec6da033b5f8c7d6d6648e7abe1737f46f12d1ee131bf73534228c762dae9ebbdbbcc5bb07b4b6a948ad4c5730f8014d7f27464238c2bafc8939fb413e7b59db61dc34500038a8cd6ea9a77e4cd37d9dbfcb34d551de6670e93088e1ad0de09cedfa5db719e836fc7f87fece6beee1819b6ce862ac89e1b9862d66ba060dabd66126726bd61cec4c976ce92b32cd12dde2530033b63846f37c4",
    "parent_block_id": "c991cfef9e810ca6389ec1a8f8877ca0b8217ed912370b3e8b36884efcc78b7c"
  },
  {
    "consensus_hash": "46425142863d123cf5e1a20438d2765189383ae7",
    "header": "000000003088b036730000000000010c26a42c0872f1854710088055c054eefc7e1e79600f6e5156e029512d2bf0f603f274919d4aafef5e7a2b2ab0a2b9cdd5c924040c521b5e08f4eb3ff1ab9bf61aed2682dabf39ba651ef62a563a216c0102972c09c4cc7cf011c6695081bf323a7d7c45e0fdc083c24de760d3decd31ee76000000000000000000000000000000000000000000000000000000000000000000008160ebc223cf0ea6e78d35f34ff8e68eb3bf76fbcdafef015135539164a26627d778718102222eb29dc8a99f1f8da440ca6b68e24e7accdd547cc3365f32db3e3adac5046facf60090e46047c1ad96db3f05a31f",
    "parent_block_id": "ae292400debf52787960292860f7e248252581add185c40a70376f4bc6d7820b"
  },
  {
    "consensus_hash": "15876b92d1b0036cb4ac245f5841d8af5ee875bd",
    "header": "00000000308891bfa90000000000010c255f70f2c03c95a686b93eee09423e908efb1585cc4c114023d178405927811c610d74f1a7e0e53ba1acf1738c2ec76a44e2dc44ea7801639b01a87e7e404d1d19468115693d0797e96bdd285a30e2260da81bc26345cc598ac7f55b3c8b3f7b264b8b5a011e5871b4fe3248ba28c72c2f7f1e93f7b7b57cb0c6b11a39ec5b92a4dfb89ff01c4393b5c033b1f286e1425c00013931a6ee97fd7bc5b2afb13ceb92710a38f206c120f7b3d20814f28331ef0eeca489ed9a80590ec79a3a9d57fe7548b5b1e26119202fa8dc65b49a10aa86328fe11f0a06090e41795b9066a81f679ab6295f4810",
    "parent_block_id": "cdc356a50befc3d9a45bea632c61d7a70c15af0706abdec480dec8995f6d4709"
  }
]
```

I'm not sure `/v2/headers` is documented yet.  Its API endpoint is `/v2/headers/:num_headers`, where `:num_headers` can be between 1 and 2100.  It returns the last `:num_headers` block headers that are ancestors of the given `tip=` value, as well as the associated `consensus_hash` and parent block's index block hash (if `tip=` is omitted, then the canonical chain tip's index block hash is used).  You could walk the entire blockchain's canonical headers back to genesis by using the last `parent_block_id` as the `tip=` parameter in the next query.  In doing so, you can load all of the index block hashes for all blocks on the canonical fork.

**Comment by sabbyanandan** [comment]
Great bit of details here in this discussion.

@zone117x: To help unblock @philipdesmedt and @talhasch, could we go ahead and add the `stacks_tip_consensus_hash` as part of all the `/block` responses? From the surface, it appears to be more beneficial for developers and perhaps also readily accessible information to assemble on the backend.

**Comment by talhasch** [comment]
> Great bit of details here in this discussion.
> 
> @zone117x: To help unblock @philipdesmedt and @talhasch, could we go ahead and add the `stacks_tip_consensus_hash` as part of all the `/block` responses? From the surface, it appears to be more beneficial for developers and perhaps also readily accessible information to assemble on the backend.

Can we also add `stacks_tip` in the block responses along with `stacks_tip_consensus_hash`? So it would allow us to produce `index_block_hash` using them seamlessly according to @jcnelson 's explanation in [here](https://github.com/hirosystems/stacks-blockchain-api/issues/1238#issuecomment-1191604128).

**Comment by philipdesmedt** [comment]
Thanks all!
