### ISSUE TITLE
Refactor the WebSockets/Socket.IO servers into a separate microservice

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1244]
Since we want to expand the capabilities of our websocket events, it would be a better idea to spin them off into a separate service that can handle its own connection logic and also its own postgres database replication configs.

The new service will support all of our current WebSockets/Socket.IO events but also start including new ones as we need them.

**Comment by rafaelcr** [comment]
Related to https://github.com/hirosystems/devops/issues/976

**Comment by smcclellan** [comment]
Closing this ticket due to inactivity & decision on other ticket. Please file a new ticket if still needed.
