### ISSUE TITLE
Do not use the API for the RPC /v2 proxy in Hiro's deployment

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1245]
This would be handled only by nginx reverse proxy configs: https://github.com/hirosystems/devops/issues/983
Nginx will also handle any necessary logging for transaction tracing

**Comment by CharlieC3** [comment]
Attempted this with Istio. It seemed to work for the most part, but the stacks-node has trouble when dealing with CORS in requests. Specifically "pre-flight" CORS requests. Until a more comprehensive HTTP server is implemented in the stacks-node, this may not be possible.

**Comment by saralab** [comment]
Related issue on Blockchain: https://github.com/stacks-network/stacks-blockchain/issues/3312

**Comment by zone117x** [comment]
Based off @CharlieC3's comment here https://github.com/hirosystems/stacks-rpc-proxy/pull/1#discussion_r1230231573 it sounds like we are in the process of testing a new /v2 proxy setup that removes this responsibility for the Hiro deployed API

**Comment by zone117x** [comment]
This is done
