### ISSUE TITLE
Add mode to write to TSV only

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#1249]
I'd like a new mode added to the API which would allow it to write incoming events to a TSV file only, with no database configured. This would allow us to measure the impact a Postgres database has on the stacks-node when syncing from genesis.

If there is a significant impact caused by having a database, we may find it's faster to sync from gensis _without_ a database and to replay events later, than it is to sync from genesis with a database.

**Comment by zone117x** [comment]
@CharlieC3 do you want this feature on the develop branch or master?

**Comment by CharlieC3** [comment]
@zone117x I think it might be a good idea to have this sooner than later, so probably `master`. Though at some point it will need to be available in v5 as well.

**Comment by rafaelcr** [comment]
This could be a new repo with a Fastify handler that does this translation

**Comment by zone117x** [comment]
This was implemented in a separate project: https://github.com/hirosystems/stacks-node-event-consumer

It was used successfully by a couple parties to generate full genesis sync TSVs during the Stacks 2.1 upgrade.

Are we good to close this issue?

**Comment by CharlieC3** [comment]
Yup!
