### ISSUE TITLE
rosetta/v1/mempool/transaction returns 500

### ISSUE THREAD

**Issue by LakshmiLavanyaKasturi** [hirosystems/stacks-blockchain-api#1271]
**Describe the bug**
Invoke `rosetta/v1/mempool` to find a txnid to call `rosetta/v1/mempool/transaction`. The call to fetch the transaction details results in 500.

**To Reproduce**
1. Invoke `rosetta/v1/mempool`  on mainnet
2. From the results pick any transaction.
3. Invoke `rosetta/v1/mempool/transaction` with the transaction id from step 2

**Expected behavior**
Should return transaction details.

**Screenshots**
<img width="994" alt="Screen Shot 2022-08-16 at 7 58 40 AM" src="https://user-images.githubusercontent.com/55154433/184912205-c0988fba-f8b5-4aed-92f7-b3a9b00c4653.png">
<img width="976" alt="Screen Shot 2022-08-16 at 7 58 48 AM" src="https://user-images.githubusercontent.com/55154433/184912293-76deaa78-19ee-4dba-99a3-e5977ff9d4e2.png">

**Console log**
N/A
**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**

**Additional context**
For get all mempool transactions:
`{
    "transaction_identifiers": [
        {
            "hash": "0xb03f47e7b1fe3bed49eb8b3509e6a729116623df7c537740bdde32c3bedcc49e"
        },
        {
            "hash": "0x9001bcf1ab8d33ea086474275103a5934d7b3cd0ecef1f509bab7e08eb08620c"
        },
        {
            "hash": "0x7f8b69f22103bc2c2040b1c59768ab7226670214834f2a2b357665c47eff736a"
        },`

For get mempool transaction:
`{
    "error": "Error: unexpected tx not found -- could not get contract from data store",
    "stack": "Error: unexpected tx not found -- could not get contract from data store\n    at makeCallContractOperation (/app/src/rosetta-helpers.ts:580:11)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at getOperations (/app/src/rosetta-helpers.ts:138:23)\n    at /app/src/api/routes/rosetta/mempool.ts:72:26",
    "errorTag": "e84121ab-aced-461e-848d-1266b1baec4a"
}`

**Comment by LakshmiLavanyaKasturi** [comment]
Relates to https://github.com/hirosystems/docs/issues/130

**Comment by smcclellan** [comment]
Closing this ticket due to inactivity. Please file a new ticket if still needed.
