### ISSUE TITLE
[Rosetta] add metadata to transfer amounts to identify token types

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1302]
To avoid confusion between STX transfers and other fungible token transfers in block or transaction responses, we should add an entry to the amount metadata, like so:
```
"amount": {
  "value": "9076708051",
  "currency": {
    "decimals": 6,
    "symbol": "DIKO"
  },
  "metadata": {
    "token_type": "ft"
  }
},
```
This way, users can identify token types when processing JSON responses

**Comment by saralab** [comment]
Whilst P4, this is an XS, can we prioritize this for the next release?

**Comment by rafaelcr** [comment]
@saralab sure, let me see if it can be slipped in
