### ISSUE TITLE
reduce max allowed page size for requests

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1330]
To avoid and/or reduce OOM errors, we should consider reducing the maximum page size we allow in all of our requests.

We don't have a standardized page size across all of our endpoints (some allow 200, others 50, etc.) so we should first make a quick inventory on what we have and then provide one single number we can enforce across all endpoints. We could even make it configurable via an ENV var in case users want to increase these limits in their API nodes.

**Comment by BLuEScioN** [comment]
https://github.com/hirosystems/stacks-blockchain-api/pull/1401/files
