### ISSUE TITLE
Wrong owner of bns name

### ISSUE THREAD

**Issue by friedger** [hirosystems/stacks-blockchain-api#1333]
**Describe the bug**
The endpoint https://stacks-node-api.mainnet.stacks.co/v1/names/ape.mega shows SPC0KWNBJ61BDZRPF3W2GHGK3G3GKS8WZ7ND33PS as owner. However, the nft is owned by SPV48Q8E5WP4TCQ63E9TV6KF9R4HP01Z8WS3FBTG through tx https://explorer.stacks.co/txid/0xf9f9144793f6d4da9aba92a54ab601eb23bfe7f44c1edb29c2920bf5e7d2ac16?chain=mainnet

**To Reproduce**
Compare the two links provided

**Expected behavior**
the endpoint should show SPV48Q8E5WP4TCQ63E9TV6KF9R4HP01Z8WS3FBTG as owner

**Comment by rafaelcr** [comment]
Thanks @friedger ... this looks like it's caused by the API not handling a `name-register` and `name-transfer` in the same transaction. I'll take a further look.

**Comment by 0xBabo** [comment]
The endpoint is not consistently showing the correct address still. Oddly it is switching back and forth when I fetch the endpoint a few times.

**Comment by rafaelcr** [comment]
@0xBabo that behavior is part of our normal release process... we're deploying the API v6 right now (which contains the fix) but we do a rollout so we can slowly send traffic into the new env. If everything looks good we do the full switch, which as far as I can see is going along fine and will happen perhaps tomorrow.

**Comment by 0xBabo** [comment]
Thanks for the update. Probably worth noting that this actually resulted in 2 erroneous NFT transfers just last night, but I think I can contact the Ryder address owners to sort it out.

**Comment by rafaelcr** [comment]
FYI @0xBabo v6 is now live in production with this fix

**Comment by 0xBabo** [comment]
I am only seeing the wrong result now, and old version at https://stacks-node-api.mainnet.stacks.co/extended/v1/status

```
"server_version": "stacks-blockchain-api v5.0.1 (master:499065fb)"
```

**Comment by Morguf** [comment]
Hi! I have this issue: 
1. During last month I had juice.btc replaced by SP3CFGFXW243Z2E3736HQJV2K5C3RF288WV6E0ARY (rob.btc). All nfts from surveys, giveaways, with juice,btc name participated, was sent to this wallet. Can we get them out ?
2. https://stacks-node-api.mainnet.stacks.co/v1/names/juice.btc
now shows SP252Z93VEGQ5TKY5RMCETHEXG6CF215GGT1EVS2T as owner. However, the bns is owned by SP3QC4R6M7M0DAZBXSZCW4FWGDCNDD05FV8Y0AY8C.

**Comment by rafaelcr** [comment]
Hi @0xBabo @Morguf apologies for the setback, we had to rollback to v5 temporarily while we fix an unrelated bug, we'll re-deploy v6 ASAP which will fix the name owners and display them correctly again

**Comment by Morguf** [comment]
Hi! The issue was met once again a month ago. NFT was transferred to SP3CFGFXW243Z2E3736HQJV2K5C3RF288WV6E0ARY instead of SP3QC4R6M7M0DAZBXSZCW4FWGDCNDD05FV8Y0AY8C
https://explorer.stacks.co/txid/0x821e10c720e21250145853f0e514da9721cf3005de2c014f845c30b965ae6951?chain=mainnet

**Comment by rafaelcr** [comment]
hi @Morguf the tx you shared is a contract deploy. Could you share the tx where the name was transferred between those addresses so we can take a look?

**Comment by Morguf** [comment]
https://explorer.stacks.co/address/SP3CFGFXW243Z2E3736HQJV2K5C3RF288WV6E0ARY?chain=mainnet
https://gamma.io/rob.btc

**Comment by rafaelcr** [comment]
@Morguf the transaction you shared did not emit a `name-transfer` BNS event. This event is necessary for a name to go from one owner to the next. Perhaps there's still another step you need to take with that contract to make the transfer happen?

**Comment by 0xbabo** [comment]
> https://stacks-node-api.mainnet.stacks.co/v1/names/juice.btc

@Morguf the API shows the address SP3QC4R6M7M0DAZBXSZCW4FWGDCNDD05FV8Y0AY8C for the name `juice.btc`. Does not seem like an API issue. In this case you should contact the sender to figure out why they sent to the wrong address.
