### ISSUE TITLE
send API release updates to new #tech-updates Discord channel

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1338]
We need to change the Discord message [CI action](https://github.com/hirosystems/stacks-blockchain-api/blob/master/.github/workflows/ci.yml#L573-L586) to point to the new channel

**Comment by sleepiJoe** [comment]
Thanks for opening this @rafaelcr 
You could just add me as collaborator and I do the rest 🙏 
https://github.com/hirosystems/stacks-blockchain-api/settings/access
In the "Manage access" section of the sidebar, click "Add People" => sleepiJoe
I just need access to add webhooks. Appreciate it.

**Comment by CharlieC3** [comment]
@sleepiJoe Thanks, we should be able to manage adding the webhook. I'm assuming you want this sent to the #tech-updates channel, right? What events do you want to trigger this notification?

**Comment by rafaelcr** [comment]
@CharlieC3 is it possible to add the release's CHANGELOG inside the Discord message sent by this webhook?

**Comment by CharlieC3** [comment]
@rafaelcr I don't believe this would be possible through the GH webhooks, those only send summarized event metadata to a destination. For detailed info and formatting, it would be better to have to go through the CI action instead.

**Comment by CharlieC3** [comment]
In the interest of time, I've added a webhook to this repo to report on `release` events. Let me know if it should be modified @sleepiJoe !
