### ISSUE TITLE
add a mempool_nonces entry to the `/address/:address/nonces` endpoint

### ISSUE THREAD

**Issue by fbwoolf** [hirosystems/stacks-blockchain-api#1342]
User in Discord reported nonce issues with this address:
https://explorer.stacks.co/address/SP14W78Q821B3HQ3ED30624Z1F13X4JMFZY3N5SK4?chain=mainnet

Endpoint is returning this:
https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP14W78Q821B3HQ3ED30624Z1F13X4JMFZY3N5SK4/nonces

<img width="298" alt="Screen Shot 2022-10-05 at 4 49 30 PM" src="https://user-images.githubusercontent.com/6493321/194170452-2b255cbe-554a-471c-84e2-abe8ad19b6bd.png">

Why is the the api not detecting missing nonces b/w `153-158` and `158-167`? Shouldn't all those be detected as missing?

The wallet is having a hard time during congestion suggesting the right nonce when the endpoint returns data that is so off. When the user reported the issue, the detected missing nonces array did not even include `158`, `167` or `168`.

We are trying to figure out how the wallet can better suggest the right nonce for the user during times of congestion.

cc @markmhx @hero-gamer

**Comment by rafaelcr** [comment]
@fbwoolf @markmhx 

> Why is the the api not detecting missing nonces b/w 153-158 and 158-167? Shouldn't all those be detected as missing?

In the current endpoint logic, those nonces are not reported as missing because they exist in the mempool i.e. at that point in time there is a tx in the mempool with the nonce 154 (either by the address or sponsored), another with 155 and so on.

We could add another entry to that JSON response that reports which nonces are currently in the mempool for that address. Would that be helpful?

**Comment by fbwoolf** [comment]
time there is a tx in the mempool with the nonce 154 (either by the address or sponsored), another with 155 and so on.
>
Hard to say what the prob was at the time bc I didn't record what the pending txs were when the user reported the issue. For some reason I believe they reported the wallet was suggesting `154` as the next nonce instead of `144` (which might be why there is one pending now). We do check against pending tx nonces. I will revisit our logic and double check it. I am pretty confident the detected missing nonces array is slow to update when users are performing txs quickly during congestion.
>
> We could add another entry to that JSON response that reports which nonces are currently in the mempool for that address. Would that be helpful?
>
That would be extremely helpful bc right now we are running thru logic in the wallet which checks against confirmed and pending tx nonces. If the api could give us that information, that would be fantastic. Thanks for your help!

**Comment by fbwoolf** [comment]
If there are any suggestions about how the wallet can better handle this, please let me know. If this data is slow to update (theoretically), what can the wallet do to suggest the nonce or let the user know the nonce is something they should double check before sending the next transaction? Any thoughts?

**Comment by fbwoolf** [comment]
Just dropping this here as a ref if interested, this is the logic I wrote in the wallet for determining the nonce after we get data from the endpoint:
https://github.com/hirosystems/stacks-wallet-web/blob/e094c5948d8b80b1d12de81d4e6492a07e40aeb3/src/app/query/stacks/nonce/account-nonces.utils.ts#L51

**Comment by fbwoolf** [comment]
@rafaelcr perfect, thanks again for your help on this.

**Comment by markmhx** [comment]
> then recommend users to try to "fill that gap" in their next transactions?

I'm thinking we should warn the user if there is a gap detected, but I'm not sure we can advise them to fill in the gap themselves, since what information would they use to do so (given that other sources for them to reference e.g. explorer are presumably also suffering from the same gap)?

**Comment by rafaelcr** [comment]
@markmhx 
> I'm thinking we should warn the user if there is a gap detected, but I'm not sure we can advise them to fill in the gap themselves, since what information would they use to do so (given that other sources for them to reference e.g. explorer are presumably also suffering from the same gap)?

You're right, agreed. Also, we should keep in mind these gaps are not 100% correct all the time because they depend on mempool messages which are unreliable.

> As such, the advice here may simply be to wait until the warning clears and/or pending transactions stop pending.

Sounds good. We should also try to explain to the user that increased activity causes this problem or something to that effect IMO
