### ISSUE TITLE
reject API requests correctly during shutdown (v6)

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1347]
The API v6 seems to have a bug in the shutdown sequence that causes errors like these to appear:

```
Error: write CONNECTION_ENDED postgres-green-all.prod-stacks.svc.cluster.local:5432
    at Promise.handler (/app/node_modules/postgres/cjs/src/index.js:282:34)
    at Promise.handle (/app/node_modules/postgres/cjs/src/query.js:136:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

unhandledRejection terminating connection due to administrator command terminating connection due to administrator command

Shutting down... received unhandledRejection
```

From the [docs](https://github.com/porsager/postgres#connection_ended), this error means the `PgStore` class is attempting to run queries after `close()` was called. This means something is wrong with how the API shuts down e.g. it should stop accepting any network requests before closing the DB connection.

**Comment by CharlieC3** [comment]
For some context and posterity from our API Weekly:

> I think our cron which kills long-running PG queries over 5 minutes could be affecting v6/green. v6 may be encountering an error emitted by the new pg client lib that the API isn’t handling properly.

So to replicate this locally, the API will have to initiate a SQL query that runs long enough that it could be forcibly killed to see how the API responds.
