### ISSUE TITLE
Importing the API .tsv : \"mempool_txs\" violates not-null constraint

### ISSUE THREAD

**Issue by BowTiedIronman** [hirosystems/stacks-blockchain-api#1392]
**Describe the bug**
stacks blockchain tip stops progressing at height 137. Checking the api logs i get this message:
{"code":"23502","column":"receipt_block_height","detail":"Failing row contains (482824, f, \\xb8675b0ee3024210aecef4433fee5050b333c217fc4265d0ecfc3762c26ff4..., 0, 3, 0, \\x0200000000, 18, 72000, f, null, null, SPR4HRCH26K4M6DP3V7HMFV82T2CTDA150D6NS8B, 0, \\x000000000104003048e19111a64a19b61ecf1a3f681684cd35412800000000..., 1666904870, null, SP1F1X05DRV9PRD0PZ66WMXVVX2KB5X8AZ6ZMS0EC, 3000000, \\x00000000000000000000000000000000000000000000000000000000000000..., null, null, null, null, null, null, null, null).","file":"execMain.c","length":666,"level":"error","line":"1953","message":"Error processing core node mempool message null value in column \"receipt_block_height\" of relation \"mempool_txs\" violates not-null constraint","name":"error","routine":"ExecConstraints","schema":"stacks_mainnet","severity":"ERROR","stack":"error: null value in column \"receipt_block_height\" of relation \"mempool_txs\" violates not-null constraint\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","table":"mempool_txs","timestamp":"2022-10-27T21:07:50.430Z"}`

**To Reproduce**
folliwing the docs to run a node-api from snapshot here https://docs.hiro.so/references/hiro-archiver.

```
curl -O  https://storage.googleapis.com/hirosystems-archive/mainnet/postgres/mainnet-postgres-14-20221027.tar.gz
curl -O  https://storage.googleapis.com/hirosystems-archive/mainnet/blockchain/mainnet-blockchain-2.05.0.5.0-rc1-latest.tar.gz
curl -O  https://storage.googleapis.com/hirosystems-archive/mainnet/api/mainnet-blockchain-api-5.0.0-latest.tar.gz
```
**Expected behavior**
Node-api to run from Hiro's backup

**Comment by rafaelcr** [comment]
Closing as stale
