### ISSUE TITLE
Can not get sip-010-ft-standard token on stacks-node-api

### ISSUE THREAD

**Issue by agangdi** [hirosystems/stacks-blockchain-api#1402]
**Describe the bug**

**To Reproduce**
1. Go to stacks sandbox deploy contract: "https://explorer.stacks.co/txid/0x1ef81b617682de1f9b876eba399efc39cc0696c358cab4bf1cdf881873df0b8b?chain=mainnet" and  "https://explorer.stacks.co/txid/SP3VFN286CGN9N7D1R5M5D4VPDAYCJHCZSSM98BVS.ABC-Token?chain=mainnet"
2. 
3. Search contract with stacks-node-api  "https://stacks-node-api.stacks.co/extended/v1/contract/SP3VFN286CGN9N7D1R5M5D4VPDAYCJHCZSSM98BVS.SBC-Token" and "https://stacks-node-api.stacks.co/extended/v1/contract/SP3VFN286CGN9N7D1R5M5D4VPDAYCJHCZSSM98BVS.ABC-Token", we can get return data.
4. Search token with stacks-node-api "https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/SP3VFN286CGN9N7D1R5M5D4VPDAYCJHCZSSM98BVS.SBC-Token" and "https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/SP3VFN286CGN9N7D1R5M5D4VPDAYCJHCZSSM98BVS.ABC-Token" returns token not found
5. Hiro doesn't treat SBC-Token and ABC-Token as ft token, can not transfer and has no decimals and image icon.

**Expected behavior**
Get token metadata and show correct info in Hiro Wallet, and can transfer with the wallet.

**Screenshots**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/4308725/198772640-36b268b3-e898-4bf6-b018-0156ea4d00ac.png">
<img width="394" alt="image" src="https://user-images.githubusercontent.com/4308725/198772728-c10a0f8c-1987-47af-9746-df87f566a264.png">

**Additional context**
Here is the same code, but hiro can transfer this token:
https://explorer.stacks.co/txid/0x22d5609a3998c6582310479f0aa3d2925989c64d258eab367ea83634a4661c0a?chain=mainnet

**Comment by rafaelcr** [comment]
Completed from migration to Metadata API
