### ISSUE TITLE
Add endpoint for retrieving principal’s NFTs and their metadata

### ISSUE THREAD

**Issue by markmhx** [hirosystems/stacks-blockchain-api#1422]
The wallet team needs an ability to query for a principal's NFTs and their metadata for https://github.com/hirosystems/stacks-wallet-web/issues/1028.

- **Option 1:** New endpoint
    
    Suggested endpoint path,
    
    `/extended/v1/address/{principal}/nfts`
    
    Response,
    
    ```jsx
    {
      "limit": 1,
      "offset": 0,
      "total": 500,
      "results": [
        {
          "token_uri": "https://pool.friedger.de/nft.json",
          "name": "Friedger Pool",
          "description": "Enjoying the stacking pool.",
          "image_uri": "https://pool.friedger.de/nft.webp",
          "image_canonical_uri": "https://pool.friedger.de/nft.webp",
          "tx_id": "0xef2ac1126e16f46843228b1dk4830e19eb7599129e4jf392cab9e65ae83a45c0",
          "sender_address": "ST399W7Z9WS0GMSNQGJGME5JAENKN56D65VGMGKGA"
        }
      ]
    }
    ```
    

- **Option 2:** Add param to return NFT metadata to existing “Non-Fungible Token holdings”
    
    The Non-Fungible Token holdings endpoint returns NFTs held by a principal. However, it only returns the NFT’s `hex` and `repr`. Would be great to have an additional param to request the NFTs’ metadata too.

cc @edu-stx

**Comment by zone117x** [comment]
Hey @markmhx! An NFT metadata indexing service has been deemed out-of-scope as a responsibility of the API, and is being implemented as a separate service. See issue https://github.com/hirosystems/stacks-blockchain-api/issues/1222

The current WIP code for this service is in this repo: https://github.com/hirosystems/token-metadata-service
As Sarala mentioned, it's not yet production tested or deployed in Hiro infra. However, nothing stops someone else from running the service themselves.

**Comment by rafaelcr** [comment]
This is now resolved
