### ISSUE TITLE
Add new endpoint to retrieve an NFT’s metadata

### ISSUE THREAD

**Issue by markmhx** [hirosystems/stacks-blockchain-api#1423]
The wallet team needs an ability to query for a given NFT's metadata for https://github.com/hirosystems/stacks-wallet-web/issues/1028.

The endpoint could be similar to non fungible tokens metadata list, except that it returns metadata only for a specific NFT, provided its “contract_id”.

cc @edu-stx

**Comment by zone117x** [comment]
Same comment from this issue: https://github.com/hirosystems/stacks-blockchain-api/issues/1422#issuecomment-1307335112

**Comment by rafaelcr** [comment]
This is now resolved
