### ISSUE TITLE
Inaccurate/changing FT metadata list count

### ISSUE THREAD

**Issue by kyranjamie** [hirosystems/stacks-blockchain-api#1434]
When fetching [`https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/ft/metadata`](https://stacks-node-api.mainnet.stacks.co/extended/v1/tokens/ft/metadata) multiple times the total count varies between requests. Currently jumping between `{ total: 369 }` and `{ total: 540 }`.

**Comment by rafaelcr** [comment]
@kyranjamie this is due to a traffic split we're currently doing in our production enviroments. One of them has indexed less tokens than the other (which is wrong of course) but we're working on moving to the new Token Metadata Service soon which will fix this.
