### ISSUE TITLE
BTC API migrate endpoints

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/stacks-blockchain-api#1443]
Migrating BTC endpoints from here https://stx-btc-api.vercel.app/documentation/static/index.html

Migrating these endpoints:

[Utils](https://stx-btc-api.vercel.app/documentation/static/index.html#/Utils)
Converter / helpers

GET
[/addr/{address}]
Convert between a Stacks or Bitcoin address
[Bitcoin info](https://stx-btc-api.vercel.app/documentation/static/index.html#/Bitcoin%20info)
Get Bitcoin information related to Stacks information and vice versa

GET
[/addr/{address}/balances]
Get the STX and BTC balance for an address

GET
[/miner-participants/{block}]
Get miners that participated for a Stacks block

GET
[/btc-block-stx-ops/{block}]
Get Stacks operations contained in a Bitcoin block

GET
[/btc-info-from-stx-tx/{txid}]
Get Bitcoin information for a Stacks tx

GET
[/btc-info-from-stx-block/{block}]
Get Bitcoin information for a Stacks block

GET
[/stx-block]
Get the Stacks block associated with a Bitcoin block

**Comment by rafaelcr** [comment]
Closing this in favor of https://github.com/hirosystems/stx-btc-api/issues/2
