### ISSUE TITLE
log level is always "http"

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#1452]
**Describe the bug**
The log level printed by the API always reads "http".
e.g. `{"level":"http","message":"HTTP GET /extended/v1/tx/0x7756798e9f6a0f1104c56b82d232b5ed9e0de950191a84953f29e96657ccfaf4","req":{"headers":{"accept":"application/json, text/plain,...`

**Expected behavior**
Instead, the log level should represent different severity scopes, like debug, info, warning, error, etc.
Ideally, the scopes would be compatible with what Grafana Loki recognizes here: https://grafana.com/docs/grafana/latest/explore/logs-integration/#log-level

Correcting the log level would greatly help with debugging and log searches.

**Comment by csgui** [comment]
Hey @CharlieC3 !

Have you tried to setup the `STACKS_API_LOG_LEVEL` environment variable?

```
```

**Comment by csgui** [comment]
Hey @CharlieC3 !

Have you tried to setup the `STACKS_API_LOG_LEVEL` environment variable before calling the API?

It can be set to the following values:
- error
- warn
- info
- http (default)
- verbose
- debug
- silly

Please let me know if this work? Cheers!

**Comment by CharlieC3** [comment]
Hey @csgui, while related I don't think that's the same thing I'm referring to.

For example, as a user it's not possible to tell if this log is an info, warn, error, etc:
`{"level":"http","message":"HTTP GET /extended/v1/tx/0x7756798e9f6a0f1104c56b82d232b5ed9e0de950191a84953f29e96657ccfaf4","req":{"headers":{"accept":"application/json, text/plain,..`

From your allowed values list, `http` and `silly` is not a valid log level [that Grafana can use](https://grafana.com/docs/grafana/latest/explore/logs-integration/#log-level). So I would expect the valid values the API to use are:
* error
* warn
* info (default)
* verbose
* debug

**Comment by rafaelcr** [comment]
@csgui you could start by looking at these lines where `winston` is configured to run with `express`: https://github.com/hirosystems/stacks-blockchain-api/blob/master/src/api/init.ts#L153-L164
