### ISSUE TITLE
[Stacks 2.1] Fix STX faucet fee bug

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1455]
The STX faucet is running into an error on the Stacks 2.1 testnet due to a fee estimate endpoint failure:
```
Error: Error estimating transaction fee. Response 400: Bad Request. Attempted to fetch <redacted>:20443/v2/fees/transaction and failed with the message: \"{\"error\":\"Estimation could not be performed\",\"reason\":\"NoEstimateAvailable\",\"reason_data\":{\"message\":\"No estimate available for the provided payload.\"}
```

The faucet should fallback to the legacy fee estimate endpoint when this happens.

**Comment by diwakergupta** [comment]
Thanks! BTW I'd imagine this is a desirable pattern / best-practice for anyone using fee estimates. Would it make sense to have a helper method in stacks.js for this cc/ @janniks @saralab ?

**Comment by janniks** [comment]
Stacks.js has this problem as well. Fees were always estimated, now the estimation may fail.

If the "legacy" fee estimation is still maintained, we could default to that (on the NoEstimateAvailable error).
