### ISSUE TITLE
[testnet] port 3999 fails to open when STACKS_API_ENABLE_FT_METADATA is set to 1 

### ISSUE THREAD

**Issue by deantchi** [hirosystems/stacks-blockchain-api#1482]
As the title states, the testnet api fails to open port 3999 when the `STACKS_API_ENABLE_FT_METADATA` env var is set to `1`.  This is occurring in `testnet` running api v6.2.2.  

some additional information for thought:
- the `token_metadata_queue` is empty inside the database, so the issue is not with the replay
- v5.x.x has an empty `token_metadata_queue` table and the host proxy serving 3999 starts up fine, this is not the case with v6.2.2
- workaround is to remove the `STACKS_API_ENABLE_FT_METADATA` env var from the deployment, this will also cause metadata to be unavailable for users

**Comment by TensionCoding** [comment]
I have a similar problem. I am running a node on DO and just updated to API 6.2.1 from 3.x. After the event replay and upgrade I was unable to access the API via port 3999. I saw this issue and disabled FT and NFT metadata, and now the port is exposed and nginx is properly routing
