### ISSUE TITLE
"Get approximate fees for a given transaction" API endpoint returns empty response and 400 bad request

### ISSUE THREAD

**Issue by TensionCoding** [hirosystems/stacks-blockchain-api#1490]
**Describe the bug**
The [documentation](https://docs.hiro.so/api#tag/Fees/operation/post_fee_transaction) describes a POST request with a required argument "transaction_payload." This argument is explained as "a hex-encoded serialization of the TransactionPayload for the transaction." I have been unable to receive a meaningful response from this endpoint. Initially I tried using a standard "tx_id" from either the "[Get recent transactions](https://docs.hiro.so/api#tag/Transactions/operation/get_transaction_list)" or "[Get mempool transactions](https://docs.hiro.so/api#tag/Transactions/operation/get_mempool_transaction_list)". This results in no response data and a 400 bad request.
I then tried using the result of the "[Get Raw Transaction](https://docs.hiro.so/api#tag/Transactions/operation/get_raw_transaction_by_id)." The response of this endpoint is described as "a hex encoded serialized transaction for a given ID." Upon entering the raw transaction as the argument to the [fee transaction endpoint](https://docs.hiro.so/api#tag/Fees/operation/post_fee_transaction), I again receive an empty response and a 400 bad request.

So far this endpoint has only responded with 400 bad requests

**To Reproduce**

Grab a transaction of your choice. I will be using tx_id: "0x5afcd106f1aa45b1beea43eec4f9cf4a8a847eadb7d987249551a58da6e53e53" from Stacks block 87279 as my example.

Get the hex encoded serialized transaction:
`curl https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x5afcd106f1aa45b1beea43eec4f9cf4a8a847eadb7d987249551a58da6e53e53/raw`

Pass the raw transaction as the transaction_payload:
`curl -X POST -d '{"transaction_payload": "0x00000000010400993ddfac9b51a068b4eb983a512f10d9d5049ae900000000000002b00000000000000000000153a3e85df95b6eab8b7e5d2cfa89719541ab24fdfe112c3e0499393e06b0946f1347a44567db3ee002577072e90679c2677295e30585e877919ae360b98ef16c010200000000040000000000000000000000000000000000000000000000000000000000000000"}' -H "Content-Type: application/json" https://stacks-node-api.mainnet.stacks.co/v2/fees/transaction`

I receive no response.

It is also important to note that this is the same result for transactions in the mempool and mined transactions.

See attached screenshots for Postman response

**Expected behavior**
I expect that I could use information provided by other API endpoints as arguments to the this [endpoint](https://docs.hiro.so/api#tag/Fees/operation/post_fee_transaction) and receive a meaningful response

**Screenshots**

![Screenshot 2022-12-15 at 9 43 36 AM](https://user-images.githubusercontent.com/103322358/207889989-7548763a-18aa-42f1-9327-ca2961a14f76.png)

**Desktop (please complete the following information):**
MacOS Ventura

**Comment by rafaelcr** [comment]
Hi @TensionCoding , the `/v2/fees/transaction` endpoint is meant for when you're building a *new* transaction (with stacks.js, for example) and you'd like to get an estimate of the fees necessary to execute that transaction if the user chooses to broadcast it. See more info here: https://docs.hiro.so/api#tag/Fees/operation/post_fee_transaction

To get the fee rate for a transaction that has already been executed in the past, you can look directly at the `fee_rate` on a transaction like https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x7089820e16e95ebf093882dfce77d6039eb6c1b5bbe3c23155781125e02953d3
You'll also get execution details in that response.

**Comment by rafaelcr** [comment]
I'm going to close this as it doesn't seem to be an API issue, but feel free to reopen if you have any further requests
