### ISSUE TITLE
Add execution costs and size when querying mempool transactions. Remove limit on current mempool transaction endpoint 

### ISSUE THREAD

**Issue by TensionCoding** [hirosystems/stacks-blockchain-api#1492]
**Is your feature request related to a problem? Please describe.**
I am working on the [stxmempool Grant](https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/662). One of the major roadblocks to visualize mempool transactions and construct meaningful approximations of the next Stacks block is the availability of 6 dimensions of a mempool transaction. 

**Describe the solution you'd like**
I would like to see the following changes:
1. Additional data for the [Get mempool transactions](https://docs.hiro.so/api#tag/Transactions/operation/get_mempool_transaction_list) endpoint
2. Additional data for the [Get transaction](https://docs.hiro.so/api#tag/Transactions/operation/get_transaction_by_id) endpoint when querying a mempool transaction
3. Removal of the 200 transaction limit on the [Get mempool transactions](https://docs.hiro.so/api#tag/Transactions/operation/get_mempool_transaction_list) endpoint.

**Additional Data**
If I query a given Stacks block, I can find the total execution costs of that block and each transaction mined in that block. If I query a mined transaction via this [endpoint](https://docs.hiro.so/api#tag/Transactions/operation/get_transaction_by_id) I will receive the 5 execution costs. However, if I query a transaction in the current mempool, via the same endpoint, I will not receive the 5 dimensions of execution costs. As of right now, I am unable to acquire the 5 dimension of a mempool transaction and thus unable to determine if a mempool block is full as a result execution limits.

Ideally I would like to receive a response from the [Get transaction](https://docs.hiro.so/api#tag/Transactions/operation/get_transaction_by_id) endpoint and the [Get mempool transactions](https://docs.hiro.so/api#tag/Transactions/operation/get_mempool_transaction_list) to include:
1. The size, in bytes, of the transaction (the length of the raw transaction / 2)
2. The 5 execution costs

By adding the above data I could retrieve all of the necessary data to visualize the mempool in one query.

**Transaction Limit**
Lastly, I would like to remove the limit of two hundred transactions from the [Get mempool transactions](https://docs.hiro.so/api#tag/Transactions/operation/get_mempool_transaction_list) endpoint. My hope is that eventually the Stacks mempool will regularly contain more than 200 transactions.

**Describe alternatives you've considered**
To determine the size of a transaction I have to grab the transaction id and then query the raw transaction and then divide its length by 2. This becomes extremely onerous when determining the size of mined block or detemining the size of mempool block. The proposed enhancements would greatly reduce api calls.
Also, I have tried querying the [Get approximate fees for a given transaction](https://docs.hiro.so/api#tag/Fees/operation/post_fee_transaction) endpoint, but as of right now I am unable to receive a meaningful response from that endpoint. See GitHub issue #1490

**Comment by rafaelcr** [comment]
Hi @TensionCoding 

> Ideally I would like to receive a response from the [Get transaction](https://docs.hiro.so/api#tag/Transactions/operation/get_transaction_by_id) endpoint and the [Get mempool transactions](https://docs.hiro.so/api#tag/Transactions/operation/get_mempool_transaction_list) to include:
> The size, in bytes, of the transaction (the length of the raw transaction / 2)
> The 5 execution costs

Unfortunately there's no way for us to give you that information for mempool transactions because we are only able to return what the Stacks node sends us via its node RPC events when a new mempool tx is found, and it does not currently send this info.

AFAIK the reason for this is that this info is calculated when miners are actually checking whether or not transactions fit in the next block for execution (i.e. at a later time, not when txs are broadcasted to the mempool). Maybe @obycode or @gregorycoppola can correct me if I'm wrong here, though.

> Lastly, I would like to remove the limit of two hundred transactions from the [Get mempool transactions](https://docs.hiro.so/api#tag/Transactions/operation/get_mempool_transaction_list) endpoint. My hope is that eventually the Stacks mempool will regularly contain more than 200 transactions.

I think this would also be a very hard thing for us to do. The main reason we place the 200 page size limit is to control the DB CPU load and node.js memory when building API responses. Removing this limit would leave us very vulnerable to abuse on that endpoint and it would reduce our API availability in cases where the mempool is very full (we've seen it go as high as ~4500 txs pending).

I suggest two alternatives:
1. Subscribe to mempool WebSocket events so you can get every new mempool transaction in real time, just as the API receives them from the Stacks node: https://github.com/hirosystems/stacks-blockchain-api/tree/master/client#mempool-updates
2. You could run your own stacks API and either remove the page size limits OR query the postgres DB directly for mempool transactions when you need them. This repo is very useful for running your own node/API: https://github.com/stacks-network/stacks-blockchain-docker

**Comment by TensionCoding** [comment]
Hey @rafaelcr, 
Thanks for getting back to me.

> AFAIK the reason for this is that this info is calculated when miners are actually checking whether or not transactions fit in the next block for execution (i.e. at a later time, not when txs are broadcasted to the mempool).
>
I am trying mimic that calculation. Apparently the API cannot expose the runtime costs, so this may be a dead end. Could I use a node to run those projections as if I am the current leader? Right now, I am only able to acquire the size of a transaction and its fee. Unfortunately, the 2MB block size limit is rarely reached. It is more likely that the maximum read count is the limit of the next mined block.  Is there a way to locally calculate the next potential block without competing for leadership?

>You could run your own stacks API and either remove the page size limits OR query the postgres DB directly for mempool transactions when you need them. This repo is very useful for running your own node/API: https://github.com/stacks-network/stacks-blockchain-docker
>
Unfortunately I am on a M1 Mac and I have been unsuccessful in running a node with an API. Like insanely unsuccessful. I have tried the Hiro snapshots with zero success. I am running into the "parent block is not found in DB" error. I may have to launch a DO droplet.

**Comment by rafaelcr** [comment]
I'm closing this given that there are no action items on the API side. Feel free to reopen if you think this is not the case.

**Comment by gandalf77** [comment]
@obycode thank you for your reply and the helpful pointers.

Our project (stxmempool.space) aims to replicate [mempool.space](https://mempool.space) for the Stacks blockchain. And a key component of the app is to visualize the whole mempool. 

While the `mock-mining` flag solution will give us access to the next block, will it also allow us to to access the ordering of all transactions in the mempool (not just the next block)?

If the answer is only the next block, can you think of any other way for us to access either the ordering or the `execution_costs` of all mempool transactions?

We have to explore the Clarinet solution further but right now it seems unfeasible to integrate the command line tool into our web app.

Thanks so much
