### ISSUE TITLE
[testnet] High CPU usage at all times

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#1494]
Testnet writer APIs use a huge amount of CPU at all times, even when it’s not seemingly doing anything and just idling.
I haven't seen this happen with mainnet writer APIs, or in the 2.1 testnet writer API, only 2.0 testnet writer APIs. Although this bug may still be possible in those networks too.

Possibly related to https://github.com/hirosystems/stacks-blockchain-api/issues/1482

**Comment by rafaelcr** [comment]
Should use the CPU profiler endpoints to get a flame graph from the pod running this config to debug

**Comment by smcclellan** [comment]
Not seeing anymore.
