### ISSUE TITLE
Revoked BNS Names resolves

### ISSUE THREAD

**Issue by dartman10** [hirosystems/stacks-blockchain-api#1502]
[Get Names Owned by Address](https://hirosystems.github.io/stacks-blockchain-api/#tag/Names/operation/get_names_owned_by_address) endpoint still resolves revoked BNS names.  I'm thinking revoked BNS names should no longer resolved.

**https://stacks-node-api.mainnet.stacks.co/v1/names/101-test-a-0002.stx**

<img width="702" alt="2" src="https://user-images.githubusercontent.com/34408740/209438805-58d4b959-0c33-47d4-b3b0-2d32b5ace48f.png">

**https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP38QTNQXVK68A98PSYVY5G28WDNF188H8P0Q0256**

<img width="283" alt="1" src="https://user-images.githubusercontent.com/34408740/209438828-1157d14e-2976-4b7c-968f-621586a69b43.png">

**Comment by dartman10** [comment]
For additional info, using the Explorer, the BNS functions properly identify the revoked name:

<img width="751" alt="Screen Shot 2022-12-25 at 10 43 29 PM" src="https://user-images.githubusercontent.com/34408740/209497393-71a88941-ebd2-4e61-b3ce-3e594eb479cf.png">


<img width="750" alt="Screen Shot 2022-12-25 at 10 45 10 PM" src="https://user-images.githubusercontent.com/34408740/209497399-c19965e0-973d-49a3-ad98-de420cf44830.png">

<img width="753" alt="Screen Shot 2022-12-25 at 10 45 50 PM" src="https://user-images.githubusercontent.com/34408740/209497404-d4fbd510-585f-4a5c-983a-31ded52a1765.png">

<img width="753" alt="Screen Shot 2022-12-25 at 10 46 28 PM" src="https://user-images.githubusercontent.com/34408740/209497413-eb0ccce2-fa19-4b2e-ae0d-81d741978398.png">

**Comment by zone117x** [comment]
@rafaelcr any idea if revoked status is supposed to be working right now?

**Comment by rafaelcr** [comment]
Nice find, @dartman10. I think this is indeed a bug and the API has never treated revoked names correctly.

What would the correct behavior be here @zone117x ? Should we simply stop resolving these names? Or is the last owner's info or revoke `last_txid` info relevant somehow?

**Comment by rafaelcr** [comment]
Just confirmed with the blockchain team that these names should stop resolving. I'll implement this fix.

**Comment by dartman10** [comment]
Thank you @rafaelcr !  :)

**Comment by dartman10** [comment]
@rafaelcr @zone117x  - hi there!  Thank you both for the release!  🙏  May I ask how to confirm the result?

Both `101-test-a-0002.stx` and `thx_dartman007.btc` were revoked.  However, each still shows up under their respective addresses:
https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP38QTNQXVK68A98PSYVY5G28WDNF188H8P0Q0256
https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP2FBVA0ACPZDNCHR8Q7Z91S0C28RYGS3K7W835B2

Thanks!

**Comment by rafaelcr** [comment]
Hi @dartman10 , we still need to update our production deployments to reflect API v6.3.1 so this change is reflected. I'll try to get that going ASAP.
