### ISSUE TITLE
(2.1) event_limit is not backward compatible

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/stacks-blockchain-api#1507]
In `v1/tx/`, explorer uses `event_limit=100`. In 2.1 this is no longer supported, using same limit results in an error
```
{
error: "'limit' must be equal to or less than 50"
}
```
Example: [https://2-1-api.testnet.hiro.so/extended/v1/tx/0xd22fe43371f71569f1cb11ddac9ca004a715e2a[…]3595d53ad2?event_offset=0&event_limit=100&unanchored=true](https://2-1-api.testnet.hiro.so/extended/v1/tx/0xd22fe43371f71569f1cb11ddac9ca004a715e2aea24c6e749082223595d53ad2?event_offset=0&event_limit=100&unanchored=true)
Ideally, we need all query params to be backward compatible to avoid breaking changes.

**Comment by zone117x** [comment]
This unintentional breaking change was introduced in https://github.com/hirosystems/stacks-blockchain-api/pull/1401

@BLuEScioN can you take a look at this? The limits should be the same or greater than they were prior to that PR.

**Comment by BLuEScioN** [comment]
> This unintentional breaking change was introduced in #1401
> 
> @BLuEScioN can you take a look at this? The limits should be the same or greater than they were prior to that PR.

Yes, I'll take this one
