### ISSUE TITLE
Canonical tx in websocket payload not yet confirmed on chain

### ISSUE THREAD

**Issue by friedger** [hirosystems/stacks-blockchain-api#1518]
**Describe the bug**
The websocket client receives txs with properties `canonical = true` and `microblock_canonical = true`. However, the tx is shown as "in microblock" on the explorer and not yet confirmed.

**To Reproduce**
1. Subscribe using `client.subscribeAddressTransactions`
2. Wait for tx
3. Check state on explorer

**Expected behavior**
canonical should be true iff the block was confirmed in an anchor block.

**Comment by rafaelcr** [comment]
Hi @friedger , the canonical flags track a transaction's re-org status, not its "anchored" status.

A transaction that is confirmed in a microblock **which is the canonical chain tip** will have both `canonical` and `microblock_canonical` as true, but this does not necessarily mean it is confirmed in an anchor block. To determine that, you should look at the `is_unanchored` property in the transaction you get (it will be true until it is confirmed in an anchor block).

Let me know if you have any more questions.
