### ISSUE TITLE
Incorrect locked amount returned by the API

### ISSUE THREAD

**Issue by edu-stx** [hirosystems/stacks-blockchain-api#1520]
**Describe the bug**
This endpoint isn't correctly returning the amount of STX stacked,

Request URL: https://stacks-node-api.testnet.stacks.co/v2/accounts/ST1Q38DQ4EAXEP1YDSAV4C0PBPZF34TTK5MAKCQQN?proof=0

This account currently has 6M stacks locked, yet the reported number by the endpoint above is 0.

**To Reproduce**
1. Start stacking
2. Compare results from these two endpoints,

```
https://stacks-node-api.testnet.stacks.co/v2/accounts/ST1Q38DQ4EAXEP1YDSAV4C0PBPZF34TTK5MAKCQQN?proof=0
```

```
https://stacks-node-api.testnet.stacks.co/extended/v1/address/ST1Q38DQ4EAXEP1YDSAV4C0PBPZF34TTK5MAKCQQN/balances
```

The amount of `locked` STX doesn't match.

**Expected behavior**
The `https://stacks-node-api.testnet.stacks.co/v2/accounts/ST1Q38DQ4EAXEP1YDSAV4C0PBPZF34TTK5MAKCQQN?proof=0` endpoint should correctly return the amount of STX stacked

**Additional context**
Payloads from the two endpoints, respectively,

```json
{
    "balance":"0x0000000000000000000005a749fb9dc0",
    "locked":"0x00000000000000000000000000000000",
    "unlock_height":0,
    "nonce":34
}
```

```json
{
  "stx": {
    "balance": "6216058800000",
    "total_sent": "1341000000",
    "total_received": "6217402000000",
    "total_fees_sent": "2200000",
    "total_miner_rewards_received": "0",
    "lock_tx_id": "0x60ca37bf8f02239dd7cbdad6aa22ae5a54ae0c8cb62b8357ad107f047b8430a8",
    "locked": "6000000000000",
    "lock_height": 93666,
    "burnchain_lock_height": 2416152,
    "burnchain_unlock_height": 2417900
  },
  "fungible_tokens": {},
  "non_fungible_tokens": {
    "ST000000000000000000002AMW42H.bns::names": {
      "count": "1",
      "total_sent": "0",
      "total_received": "1"
    }
  }
}
```

**Comment by diwakergupta** [comment]
@edu-stx so the API response is what you would expect but the `/v2/...` (which comes from the blockchain node directly) is not?

Also, the node RPC response is different now, and matches the API:

```json
{"balance":"0x0000000000000000000000324e1ba780","locked":"0x000000000000000000000574fbde6000","unlock_height":2417900,"nonce":35}
```

So, is this still an issue?

**Comment by edu-stx** [comment]
> API response is what you would expect but the /v2/... (which comes from the blockchain node directly) is not?

That's right. 

It does seem to still be an issue. I just created another blank account on testnet and went through the same process, and the amount locked by both endpoints is different. As before, one is reporting 0, the other the correct amount.

Although, given enough time, they may both be returning the same locked amount, the amount of time it takes for both to report correct values is significant, causing UIs that use these endpoints to display conflicting information to users.

**Comment by edu-stx** [comment]
The balance also seems to be incorrectly reported by the v2 endpoint with this test account, `ST3XCT52NJS4417ECXS542QKPEG75JNXNZ2YHA0D7`, I just created,

[Screencast from 2023-01-14 22-40-50.webm](https://user-images.githubusercontent.com/116000646/212500306-26cf9f0a-1139-4824-baad-085cb131235f.webm)

**Comment by zone117x** [comment]
Can you test again and include the Stacks chain tip height for both the stacks-node and API? 
* `stacks_tip_height ` from `https://stacks-node-api.testnet.stacks.co/v2/info` and
* `block_height ` from `https://stacks-node-api.testnet.stacks.co/extended/v1/status`

Right now, it looks like the stacks-node RPC at `https://stacks-node-api.testnet.stacks.co/v2/info` is 9 blocks behind the API.

This is an issue with the peering or deployment for the stacks-node(s) serving the RPC requests -- they are not keeping up with the chain tip. @CharlieC3 any ideas?

**Comment by CharlieC3** [comment]
@zone117x For the way this particular testnet environment is set up, I don't believe it's possible for those two endpoints to be out of sync unless the Stacks Blockchain node went back 9 blocks after discovering it wasn't following the main chain. Although in this event, I would expect the API to backtrack 9 blocks as well.

According to our internal metrics, none of our testnet Stacks Blockchain nodes were out of sync during the time you observed the 9-block difference. It's possible you may have been viewing old cached data in the browser or Cloudflare, though I'm not sure.

**Comment by zone117x** [comment]
`https://stacks-node-api.testnet.stacks.co/v2/info` shouldn't be cached at all should it? 

I just checked again, and it's at `94232`, while the API is at `94242`

**Comment by CharlieC3** [comment]
@zone117x Yes `v2/info` should be getting cached for 10 seconds, however I don't see the `cache-control` header appearing in requests to that testnet environment, while it is present for mainnet. I suspect this is what's causing the delay in updating that endpoint.
I'll investigate and let you know when it's resolved.

**Comment by CharlieC3** [comment]
The cache settings have been fixed, and the `cache-control` header is now appearing in the `v2/info` endpoint. I think this issue can be closed, but will wait for @edu-stx to confirm that on their end first.

**Comment by markmhx** [comment]
@314159265359879 says that the wallet-side problem is still getting reported (https://github.com/hirosystems/desktop-wallet/issues/1155). Is there anything we need to do on the client to support this API fix or should it resolve this behavior there automatically without any changes?

cc @edu-stx

**Comment by zone117x** [comment]
Is there an example address that's being reported incorrectly that I can take a look at?

**Comment by edu-stx** [comment]
Yes, this one just now,

```
Request URL: https://stacks-node-api.testnet.stacks.co/v2/accounts/ST1DBN5D84A1DW6W69TN7Y6HZACG6PFTZ7QZYXD5M?proof=0
```

Response,

```json
{
    "balance":"0x00000000000000000000000000000000",
    "locked":"0x00000000000000000000000000000000",
    "unlock_height":0,
    "nonce":3
}
```
