### ISSUE TITLE
Interact with Fungible token

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/stacks-blockchain-api#1545]

**Comment by smcclellan** [comment]
@timstackblock Could you add more detail here about what's needed?

**Comment by timstackblock** [comment]
Sure this issue is closed by PR https://github.com/hirosystems/stacks-blockchain-api/issues/1545 verify user can interact with non STX fungible tokens

We are calling the faucet for a fungible token that is not STX on our chain and getting those fungible tokens sent to our wallet.

**Comment by timstackblock** [comment]
This issue is closed by 
https://github.com/hirosystems/apiTest/pull/9
