### ISSUE TITLE
Rosetta cli construction fails while trying to run stacks-blockchain-api with mocknet

### ISSUE THREAD

**Issue by HassanAmed** [hirosystems/stacks-blockchain-api#1555]
## Describe the bug
I tried to run stacks-api-blockchain api as mocknet using this command 
`npm run dev:integrated` which failed
I guess the problem is this, in `docker/docker-compose.dev.rosetta.cli.yaml`
`command: ${CMD}` 
`volume: ${OUTPUT}` 
`${CMD}` and `${OUTPUT}` are undefined
 I get this output 
 ```
WARN[0000] The "OUTPUT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CMD" variable is not set. Defaulting to a blank string. 
1 error(s) decoding:

* error decoding 'Volumes[0]': invalid empty volume spec
 ```
## Steps To Reproduce

1. `git clone https://github.com/hirosystems/stacks-blockchain-api.git`
2. `npm run dev:integrated`

## Expected behavior

should successfully run stacks-blockchain-api with mocknet

## Environment

 - OS: macOS Monterey M1
 - Rust version: rustc 1.64.0

## Additional context
When i set 
`command: /bin/rosetta-cli --configuration-file /app/rosetta-config-docker.json check:construction`
`volume: - ./rosetta-output-construction:/app/rosetta-output`
 in `docker/docker-compose.dev.rosetta.cli.yaml` it runs successfully

**Comment by rafaelcr** [comment]
Hi @HassanAmed we will update documentation and tooling because this is a very old command that should be removed in favor of using Clarinet

**Comment by neilmehta31** [comment]
Hi @rafaelcr, I would like to fix this. Does changing the command and volume to 
`command: /bin/rosetta-cli --configuration-file /app/rosetta-config-docker.json check:construction`
`volume: - ./rosetta-output-construction:/app/rosetta-output`
fix the issue. I was able to run the stacks-blockchain-api successfully after the change. Let me know if anything else needs to be modified. I'll make a PR with the updates

**Comment by rafaelcr** [comment]
Hi @neilmehta31 that's great! Please send the PR so we can review, thanks

**Comment by neilmehta31** [comment]
@rafaelcr Please review the PR : https://github.com/hirosystems/stacks-blockchain-api/pull/1647

**Comment by neilmehta31** [comment]
@rafaelcr Please review the PR, I rebased with `develop` branch. Had problems in the earlier PR, hence created a new PR : https://github.com/hirosystems/stacks-blockchain-api/pull/1652. Let me know if any other changes need to be made. Thanks
Sorry for the inconvenience

**Comment by zone117x** [comment]
Looks like https://github.com/hirosystems/stacks-blockchain-api/issues/1666 closes this issue
