### ISSUE TITLE
create a test that finds confirmed transactions that are still returned in the mempool API endpoint

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/stacks-blockchain-api#1556]
Work with @zone117x and @rafaelcr to help create a test that will notify us of a regression around this recurring error
https://github.com/hirosystems/stacks-blockchain-api/issues/1428

**Comment by timstackblock** [comment]
@zone117x @rafaelcr 

Hey guys I wanted to run a few questions pass you on this test and get your feed back.

I will hit the mempool endpoint and bring back the transactions in the mempool I have a limit of 50 here so I will try to get the 50 txids.

<img width="757" alt="Screen Shot 2023-02-21 at 10 05 41 AM" src="https://user-images.githubusercontent.com/49165468/220382186-98c03402-a0ec-4358-9b2b-377741c539b4.png">


Once I get those txid's I will hit the block endpoint and pull back the last 6 blocks since the script will run every hour this will get the latest blocks over the last hour. Then I can compare the to list and find any txid's that are in both list if there are none we can pass the test if there are duplicates present we will raise an error.

<img width="788" alt="Screen Shot 2023-02-21 at 10 08 46 AM" src="https://user-images.githubusercontent.com/49165468/220382970-86ebf102-93aa-4c39-b97a-d32d5b5f7b08.png">

**Comment by rafaelcr** [comment]
@timstackblock that sounds like a good start, but I think I'd just tweak the order of the calls i.e. first check the last N blocks to get all confirmed `tx_id`s and then look for those in `/extended/v1/tx/:tx_id`. If any of them come back as `pending` then you've identified the bug

**Comment by timstackblock** [comment]
Thanks for the input I have created the script https://github.com/hirosystems/apiTest/pull/8 and will close this issue
