### ISSUE TITLE
Transactions are showing twice, same nonce, same fee, same tx hash... one confirmed, one pending

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/stacks-blockchain-api#1557]
Not yet sure how this is happening but I have seen at least 5 cases like this with seemingly duplicate transactions. The ones with nonce 1, 2, 3 are calling the same function/making the same transfer, with the same fee and nonce twice. That shouldn't be possible and I am not sure how this is happening. 
Since the transaction hashes are the same... perhaps they are not even different instances. an API issue? if they were RBF'ed transactions I would expect them to have different fees yet same nonce. 

![image](https://user-images.githubusercontent.com/33360391/219475527-1187c66a-f7ac-45af-a927-00e4c6b0450f.png)

Is this an API issue?

**Comment by rafaelcr** [comment]
I believe this is a symptom of https://github.com/hirosystems/stacks-blockchain-api/issues/1428

**Comment by 314159265359879** [comment]
This is causing the weirdest things, it looks like it is affecting more protocols such as ALEX:

Here is a swap that actually goes through succesfully:
![image](https://user-images.githubusercontent.com/33360391/220665759-53f5e33e-d5fa-4e8c-ac2c-8402f32d50f6.png)

Then on the address it also shows as pending (note same nonce, same tx hash)
![image](https://user-images.githubusercontent.com/33360391/220665920-1d082695-3a45-46a5-830d-0a49203e40b3.png)

In the wallet we do not see it:
it just shows all the anchored transactions
![image](https://user-images.githubusercontent.com/33360391/220666894-dc5d35c4-6edb-4ae8-bfcd-70457e2bd91b.png)

Then on ALEX a users sees "pending"
![image (5)](https://user-images.githubusercontent.com/33360391/220667138-4001c453-64fb-4ae3-93a8-3274bc9f56c5.png)

**Comment by zone117x** [comment]
@314159265359879 can you verify if this issue is fixed for you now?

**Comment by 314159265359879** [comment]
> @314159265359879 can you verify if this issue is fixed for you now?

Looks fixed to me. Thanks! 
I will reopen if it does pop up again.
