### ISSUE TITLE
Transactions with the same nonce send by exchange: one is shown succesful the other without status or failed. 

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/stacks-blockchain-api#1563]
**Describe the bug**
First of all we do not expect exchanges to use the same nonce twice of course. Secondly we can improve how we display these transactions. Lets call them expired or impossible to process. To help both the exchange and a user affected by this problem to understand what is going on. 

**To Reproduce**
I am not sure how the exchange does this. Fees are the same as well as the nonce. Lagging API? or they would get conflicting nonce in mempool error, right? Or two people using the same account on two different locations?

**Expected behavior**
I expect that an _expired_ or _impossible to mine_ transaction can be identified on the explorer as such. For example like this: 

**Screenshots**
From Binance
nonce 12251
Confirmed transaction: 
https://explorer.stacks.co/txid/0xc90231342be8eba0194d43ceac4e879b79b0e9faafc523f24e8b569201cf26bc?chain=mainnet
![image](https://user-images.githubusercontent.com/33360391/220893164-cc48beb9-2948-4d08-9f11-658c646c0692.png)

User who didn't get funds (send with same nonce) sees this in search preview
nonce 12251
![image](https://user-images.githubusercontent.com/33360391/220892129-64247245-1215-4b76-80f9-320496f0ab36.png)

![image](https://user-images.githubusercontent.com/33360391/220893514-5b6fcc17-e1a5-42d4-9ab6-09d9da0b69d2.png)

Marked green are missing details about the status of the transaction. Suggestions to improve have been made in https://github.com/hirosystems/explorer/issues/988#issuecomment-1439728679 and in https://github.com/hirosystems/stacks-wallet-web/issues/1899#issuecomment-1439803407

Transaction view

**Console log**
n.a.

**Desktop (please complete the following information):**
n.a.]

**Smartphone (please complete the following information):**
n.a.

**Additional context**
Related issues: https://github.com/hirosystems/stacks-blockchain-api/issues/1428 
https://github.com/hirosystems/stacks-blockchain-api/issues/1557#issuecomment-1440243864
(temp) fix? https://github.com/hirosystems/stacks-blockchain-api/pull/1561

**Comment by 314159265359879** [comment]
I have handled three cases so far with this issue. 

Some details:
Tx hash, note nonce (12153) and hash failed/expired:
0xafd2bb19589b35f5278c8a7daccfca50f5b6fbf62696d68ecb8f8a1c765f76ee

The transaction that did get mined same nonce different hash
https://explorer.stacks.co/txid/0x04c3f4f63feb954eb330864167360d37f950971c35db8c84d230d662cdb3e00a?chain=mainnet

**Comment by babanait** [comment]
I have same problem. 
plese help me 
transaction : https://explorer.stacks.co/txid/0x151b4fcf1681328a1f4a7f82e709728733e3d8e44e8a4f30fdb3cf2180597c89?chain=mainnet

<img width="1259" alt="Screenshot 2566-02-23 at 19 14 48" src="https://user-images.githubusercontent.com/55784330/220902744-e84a66b5-b593-44ed-aa7f-c1855037fe5f.png">

**Comment by 314159265359879** [comment]
> I have same problem. plese help me Tx hash, note nonce (12149) and hash failed/expired: 0x151b4fcf1681328a1f4a7f82e709728733e3d8e44e8a4f30fdb3cf2180597c89 transaction : https://explorer.stacks.co/txid/0x151b4fcf1681328a1f4a7f82e709728733e3d8e44e8a4f30fdb3cf2180597c89?chain=mainnet
> 
> <img alt="Screenshot 2566-02-23 at 19 14 48" width="1259" src="https://user-images.githubusercontent.com/55784330/220902744-e84a66b5-b593-44ed-aa7f-c1855037fe5f.png">

Hi again!
I have found the twin (same nonce different hash) of this transaction too. That is this one with nonce 12149 that did get mined. In this case it failed because the transaction is sending to the sender (u2). 
https://explorer.stacks.co/txid/0xaacd2d2fad35c6fd6345473f1e02b9aff37d83c466badab75f8b9363319c9ea5?chain=mainnet

**Comment by zone117x** [comment]
This is should be fixed by https://github.com/hirosystems/stacks-blockchain-api/pull/1561

Please let me know if you continue to see mempool and/or nonce related issues. Thanks!
