### ISSUE TITLE
Log output cleanup

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1566]
* [x] `[socket.io] ...` messages should include a property to easily filter by, and most of them should be changed from `info` to `verbose` level
* [x] `[stacks-node event] ...` messages should include a property to easily filter by
* [x] `getPagingQueryLimit` error messages like `'limit' must be equal to or less than 50` are logged without any error level, these should be http-400 messages

**Comment by zone117x** [comment]
@csgui is this something you can take on? The migration from winston to pino that Rafael mentioned above can be done in a follow-up PR.

**Comment by csgui** [comment]
@zone117x Sure. I'll have a look. Assigning it to me.

**Comment by csgui** [comment]
Hello @zone117x and @rafaelcr !

> * `[socket.io] ...` messages should include a property to easily filter by

Does `socket.io` text can't be used as a filter? I.e.: if the property `message` contains `socket.io` filter by that.

> * `[stacks-node event] ...` messages should include a property to easily filter by

Does `stacks-node event` text can't be used as a filter? I.e.: if the property `message` contains `stacks-node event` filter by that.
