### ISSUE TITLE
SPIKE: BNS `get-name` query is creating DB bottleneck (2 days)

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1580]
The following query is reporting very high load times, even though indexes are complete and local tests show a healthy query plan. I suspect there is something else blocking the execution of this query, probably a bug with how queries are run inside the postgres transaction that envelops this query.

```
SELECT n.*, z.zonefile
        FROM names AS n
        LEFT JOIN zonefiles AS z USING (name, tx_id, index_block_hash)
        WHERE n.name = $1
          AND n.registered_at <= $2
          AND n.canonical = $3
          AND n.microblock_canonical = $4
        ORDER BY n.registered_at DESC,
          n.microblock_sequence DESC,
          n.tx_index DESC,
          n.event_index DESC
        LIMIT $5
```

**Acceptance Criteria**: Create an Issue for all work that needs to be done to resolve this issue.

**Comment by smcclellan** [comment]
Do we have a way to see the query plan on some realistic data locally? Or better yet, to see it on a clone of production?

**Comment by rafaelcr** [comment]
I checked the query plan thoroughly a few weeks ago and it looked correct (using the right indexes and returning in very short time).

However, during that time @timstackblock also helped me run a few load tests on this query in our dev server and it returned interesting results... I'll let him provide more detail but the TL;DR: was that the query performs perfectly well 95-97% of the time resolving in 1-2 seconds but there are some calls that take a couple minutes to resolve (3-5 minutes).

I think what's happening is that there is some sort of locking going on with rows required by this query. Maybe a transaction in the API writer creates this lock and the reader is not able to retrieve the rows within a reasonable time. I need to investigate this further.
