### ISSUE TITLE
remove the old token metadata processor

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1582]
now that we have the [Token Metadata API](https://github.com/hirosystems/token-metadata-api) in place and that we are redirecting all FT metadata endpoints to it, we should get rid of the token metadata processor completely

**Comment by rafaelcr** [comment]
we should, however, make sure we do not disrupt Rosetta's functionality when returning token operations (symbol, decimals, etc.)

**Comment by rafaelcr** [comment]
For Rosetta, we could fetch token contract decimals and symbols using read-only contract calls that follow SIP-010 (`get-decimals`, `get-symbol`) and use an in-memory cache for performance optimization

**Comment by smcclellan** [comment]
@rafaelcr Given that we can't get rid of this processor completely, is this still worth doing?
