### ISSUE TITLE
Slow endpoint: stx_supply

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#1590]
This endpoint is rather slow compared to the others: https://api.hiro.so/extended/v1/stx_supply?unanchored=true

It ends up making some data on the front page of the Explorer lag a bit. Is there any way we can speed this endpoint up? Either through an optimized SQL query, or via caching?

**Comment by rafaelcr** [comment]
I think a materialized view would give us the most gains and we actually wouldn't need to create a major release to do this, I believe, just a new migration that adds the view 👍🏻

**Comment by zone117x** [comment]
Etag caching for this endpoint has been merged into develop. Next steps:
1. Once this makes it into a stable release and deployment, determine if the etag caching improvements are good enough.
2. If not good enough, we probably need to add this as to a materialized view.
