### ISSUE TITLE
Enable NPM publish again

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#1593]
Revert this commit to do so:
https://github.com/hirosystems/stacks-blockchain-api/commit/b56cc82144e9fc33ffaf565e3f9a5ef0e57c0120

However, [there may be build failures](https://github.com/hirosystems/stacks-blockchain-api/actions/runs/4493354066/jobs/7904566509).

**Comment by zone117x** [comment]
@csgui this is another good issue to tackle. We need to do something like
1) replicate that failing CI npm build process in a local environment
2) test fix in github CI with something like a NPM publish dry-run

**Comment by csgui** [comment]
Hey @zone117x @CharlieC3 @rafaelcr ,

The issue seems to be related with the `rimraf` package in the `@stacks/blockchain-api-client` module.

```
> npm run build
> @stacks/blockchain-api-client@7.1.2 build /home/runner/work/stacks-blockchain-api/stacks-blockchain-api/client
> rimraf ./lib && npm run generate-openapi && npm run build:node && npm run build:browser
```

Follow a snipet of the stack trace error containg the `rimraf` package reference.

```
at Object.<anonymous> (/home/runner/work/stacks-blockchain-api/stacks-blockchain-api/client/node_modules/rimraf/node_modules/glob/dist/cjs/glob.js:5:23)
```

Maybe a fix pass by removing the `rimraf` package from the dependencies and change it's usage by a `rm -rf` command. But my concern is related with Windows users of the API. Probably `rm -rf` would break on their systems when running the `npm run build` command. Should we take that into consideration? 

Thanks!

**Comment by rafaelcr** [comment]
Is there a newer version of `rimraf` we could use that gets rid of these issues by any chance?

**Comment by csgui** [comment]
> Is there a newer version of `rimraf` we could use that gets rid of these issues by any chance?

Latest is `5.0.0`. I'll check that.

**Comment by zone117x** [comment]
Reopening the issue since we seem to be running into the same problem again
https://github.com/hirosystems/stacks-blockchain-api/actions/runs/4729882097/jobs/8392996896

@csgui any idea on this one?

**Comment by csgui** [comment]
Humm.... 🤔 ... seems to be a different issue. The library is breaking in another part. Smells like a `node` issue compatibility.

We can try to lock the `Semantic Release` step to a specific node version in the CI configuration [file](https://github.com/hirosystems/stacks-blockchain-api/blob/master/.github/workflows/ci.yml).

**Comment by rafaelcr** [comment]
I think this might be fixed if we upgrade `cycjimmy/semantic-release-action` @zone117x @csgui I'll give it a shot

**Comment by csgui** [comment]
Yes @rafaelcr ! As we saw, this PR is a complement for the `cycjimmy/semantic-release-action` upgrade.

Thanks for the discussion. Closing this issue. 🙏
