### ISSUE TITLE
Domain migration `stacks.co` to `hiro.so`

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1595]
Update url references from `stacks.co` to `hiro.so` for seed nodes, API url references, and Explorer url reference.

https://github.com/search?q=repo%3Ahirosystems%2Fstacks-blockchain-api+.stacks.co&type=code

**Comment by zone117x** [comment]
Can we close this or should we wait until those docs endpoints are updated? @CharlieC3 @LakshmiLavanyaKasturi ?

**Comment by CharlieC3** [comment]
@zone117x I think this is done. I talked to Lavanya about it last week and it seems any stacks.co docs references left leads to content that has no plan to be migrated to hiro.so.
