### ISSUE TITLE
subnet block sync doesn't start when BNS enabled

### ISSUE THREAD

**Issue by deantchi** [hirosystems/stacks-blockchain-api#1602]
It was discovered that BNS data needs to be disabled in the api in order for the sync to start.  I'm not sure if BNS is needed or supported in the context of subnets but I had to [disable it](https://github.com/hirosystems/k8s/commit/50d8b1946d0c5f4af0060de3122255ec3295d777) to get the subnet node syncing.

**Comment by deantchi** [comment]
That's a good idea. As the bns setting is stated to be optional in the docs. We should mention the possibility of conflicting flags.

**Comment by smcclellan** [comment]
Next: Add env variable (or lookup) to determine subnet, then throw error if this comes up.
