### ISSUE TITLE
Custom Errors are not being handled properly by the logging system

### ISSUE THREAD

**Issue by csgui** [hirosystems/stacks-blockchain-api#1615]
`getPagingQueryLimit` [function](https://github.com/hirosystems/stacks-blockchain-api/blob/master/src/api/pagination.ts#L74)  throws an error which is supposed to indicate to the rest of the route handling that it's a 400. That exception should be handled, automatically, by the logging framework component. I.e.: no need of this [code](https://github.com/hirosystems/stacks-blockchain-api/blob/develop/src/api/routes/address.ts#L583).

Comment for reference: https://github.com/hirosystems/stacks-blockchain-api/pull/1613#discussion_r1168947146

**Comment by smcclellan** [comment]
Porting to Fastify in the future may be helpful, but let's just patch this one for now.

**Comment by csgui** [comment]
Fixed by #1630 ... new logging library.
