### ISSUE TITLE
Error "incorrect function argument" when arguments look good

### ISSUE THREAD

**Issue by markmhx** [hirosystems/stacks-blockchain-api#1637]
Users are reporting that they can't execute contracts with what appear to be properly formatted arguments.

Originally reported with https://github.com/hirosystems/wallet/issues/3620 in the wallet repo, but our team suspects the issue may be API or node-based.

**Comment by zone117x** [comment]
Seems like a node issue. Looks like an issue has also been opened on that repo https://github.com/stacks-network/stacks-blockchain/issues/3690
