### ISSUE TITLE
Add cooldown to rate limiting page

### ISSUE THREAD

**Issue by smcclellan** [hirosystems/stacks-blockchain-api#1665]
The [current rate limiting doc](https://docs.hiro.so/stacks-blockchain-api/feature-guides/rate-limiting) does not include the cooldown time. This has been asked for and would be helpful to share with users.

**Comment by LakshmiLavanyaKasturi** [comment]
PR: https://github.com/hirosystems/stacks-blockchain-api/pull/1698
