### ISSUE TITLE
Deprecated Command for Local Setup and Alternative Workflow

### ISSUE THREAD

**Issue by abhinavk9757** [hirosystems/stacks-blockchain-api#1666]
The only intended purpose of this dockerfile is for integration tests, which this change appears will break: https://github.com/hirosystems/stacks-blockchain-api/blob/9dc72488bff40de008d4245172259185840fc670/src/tests-rosetta-cli-construction/validate-construction.ts#L45

It sounds like from issue https://github.com/hirosystems/stacks-blockchain-api/issues/1555 that you're trying to get `npm run dev:integrated` to work? As Rafael mentioned, this is a very old command that should be removed. 

Can you give more context into what you are trying to achieve? Then we can point you towards the intended workflow, or more appropriate areas to modify.

_Originally posted by @zone117x in https://github.com/hirosystems/stacks-blockchain-api/pull/1652#discussion_r1189719472_
            

In the documentation, it is written to run the above command to get started locally.
As I understand this command should be deprecated, but How do people who are new to this repository get started?

**Comment by abhinavk9757** [comment]
In the documentation, it is written to run the command `npm run dev:integrated` to get started locally.
As @zone117x  mentioned this command should be removed.

Can you tell us how to get started, I can try that and raise a PR for doc change as well.

**Comment by abhinavk9757** [comment]
Could you give me a quick rundown of the steps or changes I need to make to set up the project locally? I'll document the process  and submit a pull request to update the documentation

**Comment by zone117x** [comment]
The API requires several docker containers to spin up with the right configuration: postgres, stacks-node, (bitcoind in some cases). The startup and teardown can be tedious to manage during development -- the typical workflow that the maintainers use the the one configured for vscode: https://github.com/hirosystems/stacks-blockchain-api/blob/1c6e35a2dc0b5c161d35f291220a0bef6c6f5d28/.vscode/launch.json#L52-L69
I.e. the run configs here:
<img width="412" alt="image" src="https://github.com/hirosystems/stacks-blockchain-api/assets/1447546/4c4bb09e-35c3-45eb-9dcd-c1631d7685e4">

This is configured to start the docker containers, API project, and teardown on stop/restart. As bonus you also have proper breakpoint debugging available.


However, if you want to do perform the setup from the command line only, you can do something like the following:
1. Start container dependencies (run this in a separate terminal):
   ```shell
   docker compose -f docker/docker-compose.dev.postgres.yml \
   -f docker/docker-compose.dev.stacks-krypton.yml \
   -f docker/docker-compose.dev.bitcoind.yml up --force-recreate -V
   ```
1. Run the API project:
   ```shell
   npm run dev
   ```
1. When finished or restarting, tear down the docker environment:
   ```shell
   docker compose -f docker/docker-compose.dev.postgres.yml \
   -f docker/docker-compose.dev.stacks-krypton.yml \
   -f docker/docker-compose.dev.bitcoind.yml down -v -t 0
   ```


Note that the dockerfile paths and config are somewhat of an internal implementation detail and are subject to change. Feel free to document these, but we will have to keep them in mind when making future changes.

**Comment by abhinavk9757** [comment]
Thank you @zone117x !

I will attempt to execute and revise the documentation.
