### ISSUE TITLE
link apiTest repo test to run on changes to the stacks-blockchain-api

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/stacks-blockchain-api#1670]
Update the apiTest repo test yaml file, env variable and test to run on changes to the stacks-blockchain-api. Add yaml file, env variable and logic to send the test URL to the apiTest repo to execute all test against this dynamic URL.

ricosandyca/convert-env-json
peter-evans/repository-dispatch

@zone117x @CharlieC3

**Comment by CharlieC3** [comment]
Would require a new GH workflow in stacks blockchain api repo to manually trigger the workflow in the apiTest repo.

**Comment by timstackblock** [comment]
This issue is complete, the apiTest now point to the devApi which is updated with the release branch code. I was able to run my test against this URL before the last api deployment so I can close this ticket.

Thanks for the help!
