### ISSUE TITLE
transactions_with_transfers response is too large in some cases

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#1673]
Despite pagination in place, for some smart contracts the `/transactions_with_transfers` endpoint can return a huge amount of `ft_transfers` ([example](https://api.hiro.so/extended/v1/address/SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.trade-and-earn-helper/transactions_with_transfers?limit=30&offset=0&unanchored=true)). This can cause availability & performance issues on the API, like when the smart contract is view in the Explorer or other clients.

Let's explore what can be done to perhaps further paginate the `ft_transfers` data or otherwise limit the data that comes through on the `/transactions_with_transfers` endpoint, while still maintaining the ability for clients to extract that data through other means (e.g. multiple page calls, different page calls).

**Comment by zone117x** [comment]
We need to evaluate priority on this

**Comment by rafaelcr** [comment]
Fixed by https://github.com/hirosystems/stacks-blockchain-api/pull/1876
