### ISSUE TITLE
add additional chain_ids for subnets

### ISSUE THREAD

**Issue by deantchi** [hirosystems/stacks-blockchain-api#1674]
we will need additional CHAIN_IDs added to support various subnet networks.
currently `0x55005500` == `dev`
can we add the following:
```
0x55005501
0x55005502
```

In addition, lets plan for mainnet as well.
```
0x55005510
0x55005511
0x55005512
```

**Comment by zone117x** [comment]
Hey @deantchi, support for configuring chain IDs was implemented [here](https://github.com/hirosystems/stacks-blockchain-api/pull/1669) and is available in the latest beta release.

It sounds like you want to use the following environment variables:
```env
# subnet chain IDs for testnet: 0x55005501, 0x55005502
# subnet chain IDs for mainnet: 0x55005510, 0x55005511, 0x55005512
CUSTOM_CHAIN_IDS=testnet=0x55005501,testnet=0x55005502,mainnet=0x55005510,mainnet=0x55005511,mainnet=0x55005512
```

Then specify `STACKS_CHAIN_ID` to match whatever network you are deploying, e.g. for a testnet deployment with `0x55005501`:
```env
STACKS_CHAIN_ID=0x55005501
```
