### ISSUE TITLE
[TESTNET BUG] Stacks 2.4 - faucet

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/stacks-blockchain-api#1675]
## Describe the bug

Faucet is not working, it looks like it is sending with nonces that are incorrect (already used) and then transactions do not get processed. Some transactions are still getting processed. 

## Steps To Reproduce

1. Start explorer **sandbox**
2. login
3. use faucet
4. see error on page

Additionally
A. Use desktop wallet for testnet
B. Click button for testnet tokens
C. See error

On the faucet page (exporer) I also see some succesfull calls so perhaps the errors do not always get displayed. On the faucet address I also see. There was definitely increased activity this past weekend because of velar.co's testnet promotion. 

https://explorer.hiro.so/address/ST319CF5WV77KYR1H3GT0GZ7B8Q4AQPY42ETP1VPF?chain=testnet
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/33360391/743836ef-6168-4164-be30-17286aac73d8)
see the current account nonce? 36770 but there are pending transactions with nonces much lower. 

![image](https://github.com/hirosystems/stacks-blockchain-api/assets/33360391/55e0f4ab-21f6-4bf3-8b44-78fb1f7318f4)

## Expected behavior

We expect the faucet to work 100% of the time ;-)
- The page to load normally on the explorer sandbox
This box should not be blank, 
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/33360391/5d018643-2962-4943-843c-dd6afa8393ef)
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/33360391/2d2e7279-d78a-4492-95a0-0587584ab22a)

- And the button to work on the desktop testnet wallet, instead of:
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/33360391/7476a9bf-53e3-4c50-b5f9-f56f4400e88c)

## Environment

 - Any OS

## Additional context

Some images: https://github.com/hirosystems/explorer/issues/1179
Please include any relevant stack traces, error messages and logs.

Nonce issues likely related to the issue described here:
https://github.com/hirosystems/wallet/issues/3584 (reuse of nonces)

We have been seeing other cases where wallets and other dapps/contracts send transactions with nonces that have already been used. This will also be discussed in upcoming "state of nonces" meeting on juni 28th. 

----

### Critical, Launch Blocking Bugs
**Consensus critical bugs**
- [ ] Can cause a chain split
- [ ] Can cause an invalid transaction to get mined
- [ ] Can cause an invalid block to get accepted
- [ ] Can cause a node to stall

**State corruption**
- [ ] Can modify a smart contract’s data maps and data vars without a `contract-call?

**Stolen funds**
- [ ] Any address losing STX without a corresponding transfer
- [ ] Modify token balances and NFT ownership in other contracts without a `contract-call?`

**Take control and/or bring network to a halt**
- [ ] Take control and/or bring network to a halt

### Major, Launch Blocking Bugs
**Major bugs**
- [ ] Performance or correctness bugs that don’t rise to P0 level
- [ ] Stress test or DoS attacks that slow things down enough
- [ ] Resource exhaustion
- [ ] Expected functionality doesn’t work in obvious ways (important to be super specific with this wording)

### Minor, Non-launch blocking bugs
**Minor bugs**
- [ x ] Bugs in non-critical software (CLI, UI, etc) that doesn’t impact critical functionality

**Comment by smcclellan** [comment]
@314159265359879 This is being worked on, thank you for filing.

**Comment by smcclellan** [comment]
@314159265359879 This should be resolved, let me know if you see any further issues.
