### ISSUE TITLE
"@stacks/blockchain-api-client" is actively monitoring certain transactions, but is not capturing all subscribed transactions

### ISSUE THREAD

**Issue by mefrem** [hirosystems/stacks-blockchain-api#1693]
**Describe the bug**
[This is a repost from [zeroauthority-dao Issue #28](https://github.com/zeroauthority-dao/za-website/issues/28) posted by @Sushilbro]

Problem:
"In our attempt to listen to real-time transactions using websockets, we receive a response from the called function and update our off-chain database only if the transaction ID (txid) is confirmed in the anchor block. However, we are experiencing a limitation where not all subscribed transactions are being captured."

**To Reproduce**
"The code to listen to WebSocket connections is housed in the upsertGig.js file, accessible through this GitHub link: https://github.com/zeroauthority-dao/za-website/blob/Sushil-branch-master/pages/api/upsertGig.js. "

**Additional context**
I personally think that a Hiro [Chainhook](https://github.com/hirosystems/chainhook) solution would serve the zeroauthority-dao team well, however I wanted to make sure there wasn't a lingering error or missing coverage in our API.

**Comment by xyzerobtc** [comment]
If someone could help us that would be much appreciated. Reply here or https://github.com/zeroauthority-dao/za-website/issues/28 posted by @SushilBro
you can email us as well dao@zeroauthority.xyz

**Comment by xyzerobtc** [comment]
Hi @lgalabru - Jude said you may be able to help us resolve this issue for the webhook. @sushilbro

**Comment by xyzerobtc** [comment]
cc: @HodlSTX

**Comment by sabbyanandan** [comment]
Also, as an FYI @xyzerobtc, when clicking "LEARN" top-nav link at https://zeroauthority.xyz/, it results in 404.

**Comment by sabbyanandan** [comment]
> Do we need to set up our own Bitcoin and stacks node to use Chainhook with stacks.?

Hi, @SushilBro! If you're using the Chainhooks support in the Hiro Platform, no, you don't have to. However, you also have the option to run Chainhooks in your infrastructure. To that extent, you can override the Stacks and Bitcoin node/ports if you'd prefer managing them independently, pointing to your custom deployed services in your infra. We have a few [how-to guides](https://docs.hiro.so/chainhook/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind) on custom deployments as a service.

@lgalabru: Feel free to correct me if my interpretation is wrong with the above.

**Comment by xyzerobtc** [comment]
@sabbyanandan thank you for the note on the 404 error. 
Really appreciate the guidance and giving us feedback on how to implement chainhooks in the zero authority cerulean marketplace. Here is the link to testnet to give you an idea how the marketplace works. 
site: https://za-website-staging.vercel.app/

instructions: 
(1) connect wallet
(2) make an offer to someone 
(3) web3 creator accept the offer. 
(4) clarity contract deposits reward
(5) clarity contract releases reward
(6) both creators earn reputation on-chain & emissions 

what is zero authority & what is the cerulean marketplace? 
https://www.canva.com/design/DAFoj8ydBhM/qQBzWijW2QGw398QDUU0RQ/view?utm_content=DAFoj8ydBhM&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by smcclellan** [comment]
I'll close this ticket as it looks like @SushilBro (and @xyzerobtc) have received guidance here. Feel free to reopen if there's a further need.

**Comment by SushilBro** [comment]
> > Do we need to set up our own Bitcoin and stacks node to use Chainhook with stacks.?
> 
> Hi, @SushilBro! If you're using the Chainhooks support in the Hiro Platform, no, you don't have to. However, you also have the option to run Chainhooks in your infrastructure. To that extent, you can override the Stacks and Bitcoin node/ports if you'd prefer managing them independently, pointing to your custom deployed services in your infra. We have a few [how-to guides](https://docs.hiro.so/chainhook/how-to-guides/how-to-run-chainhook-as-a-service-using-bitcoind) on custom deployments as a service.
> 
> @lgalabru: Feel free to correct me if my interpretation is wrong with the above.

**Comment by SushilBro** [comment]
hey, @sabbyanandan can you explain how can i create Chainhooks in Hiro Platform, i could not see any options to create Chainhooks there.

**Comment by sabbyanandan** [comment]
> hey, @sabbyanandan can you explain how can i create Chainhooks in Hiro Platform, i could not see any options to create Chainhooks there.

Hello, @SushilBro! We aim to release the Chainhooks support in the Hiro Platform by ~ the 2nd week of August, so it is coming soon! In the meantime, if you're up for it, I can work with you to have you try it out in a non-prod environment and engage on any feedback loops. 

Please feel free to find a slot that works best for you: https://calendly.com/sabbyanandan/platform-office-hours
