### ISSUE TITLE
Get list of holders for FT token

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/stacks-blockchain-api#1701]
Hello team,
We are planning to add a new tab "Holders" to the [FT page](https://explorer.dev.hiro.so/token/SP2C2YFP12AJZB4MABJBAJ55XECVS7E4PMMZ89YZR.arkadiko-token?chain=mainnet) in Explorer. This tab will display a list of addresses that hold this specific FT token. Ideally, we will need a new endpoint that accepts the token contract address as input and returns a paginated list of holder addresses along with token quantity and percentage of the total supply. Please let me know if you would like to discuss this further.
Best,
Heidar

**Comment by smcclellan** [comment]
@chresko Can you confirm the priority here?

**Comment by zone117x** [comment]
@He1DAr and I discussed this, and given the amount of time implementing this would take, it's not currently a priority.

**Comment by andresgalante** [comment]
closing this in favor of [#1643](https://github.com/hirosystems/explorer/issues/1643)
