### ISSUE TITLE
Refundstx increase fee problem

### ISSUE THREAD

**Issue by gemarti** [hirosystems/stacks-blockchain-api#1705]
I had been waiting for over 20hrs for a lnswap to complete. I decided to request a refund. After sometime waiting for the refund I initiated a fee increase to speed up the refund process. Shortly after increasing the fee my original refund came through: https://explorer.hiro.so/txid/0x2a5b4e2fe1ee4a3d08e403f4fc9b489e12f637df141cccafc5bff23d40d7cdb5?chain=mainnet

But now there is another refundstx showing in my wallet for the same refund that I believe is locking my STX in my wallet: https://explorer.hiro.so/txid/0xee814b82d127b6477229ebdacd3fd0096a16c2a9dede5050d2888692859fb7cb?chain=mainnet

I don't know what to do. Wait? Any help would be appreciated. 

Thank You!

**Comment by zone117x** [comment]
Hi, both of these transactions where created with the same nonce of `9`, so only one can be mined.

In this case, it looks like `0x2a5b4e2fe1ee4a3d08e403f4fc9b489e12f637df141cccafc5bff23d40d7cdb5` has been confirmed, and `0xee814b82d127b6477229ebdacd3fd0096a16c2a9dede5050d2888692859fb7cb` will be dropped.
