### ISSUE TITLE
Filter Mint, Burn, Peg-in, and Peg-out sBTC transactions

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/stacks-blockchain-api#1709]
The ability to filter Mint, Burn, Peg-in, and Peg-out sBTC transactions. Discussion summary:
- Search for events would be more appropriate.
- Peg in/out are not 1st class stacks transactions (burn chain transactions, not currently supported by stacks API. However, it is possible to add support for them)
(cc: @zone117x feel free to edit/add more details)

**Comment by smcclellan** [comment]
Related: https://github.com/hirosystems/stacks-blockchain-api/issues/1532

The "Search for events would be more appropriate" sounds like an additional piece. Let's use this ticket to track that work.

**Comment by He1DAr** [comment]
I think issue is outdated. AFAIK peg-in/out are no longer being implemented (@zone117x please correct me if I'm wrong).

**Comment by smcclellan** [comment]
We will track the sBTC + API integration on [this ticket](https://github.com/hirosystems/stacks-blockchain-api/issues/1532). @He1DAr please reopen or re-scope if any additional work outside of that ticket is needed.
