### ISSUE TITLE
/v2/info endpoint returning burn_block_height: null

### ISSUE THREAD

**Issue by teebszet** [hirosystems/stacks-blockchain-api#1749]
**Describe the bug**
There were intermittent occurrences of the `/v2/info` endpoint returning `burn_block_height: null`

**To Reproduce**
There were a total of five occurrences on November 10th and 11th, where we have logs of the burning_block_height field returning null.

for example around this timestamp: 2023-11-11 02:38:06

**Expected behavior**
Is this field supposed to be nullable? I couldn't find any documentation on the expected response shape, other than the postman collection .json

**Comment by andresgalante** [comment]
Hi, this is an issue for the the Stacks repo: https://github.com/stacks-network/stacks-core

I can't transfer it since it's on another organization, would you mind reopening there, please? 🙏
