### ISSUE TITLE
Get STX blocks by BTC block

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/stacks-blockchain-api#1755]
Hello team,
We are currently working on a new feature in the explorer to display a list of STX blocks associated with a specific BTC block. For this, we need a new endpoint that accepts either the BTC block hash or height and returns a paginated list of STX blocks.
Suggested interface:
GET `/blocks/by_burn_block_hash/{burn_block_hash}?limit={limit}&offset={offset}`
Response:
```
{
    limit: number;
    offset: number;
    total: number;
    results: Array<Block>;
}
```

**Comment by zone117x** [comment]
I don't think we should change the endpoint naming convention (`block` to `blocks`) just to avoid a naming collision. I'm learning towards either a version bump like `/v2/blocks/by_burn_block_hash` or creating a new name like `/v1/blocks/many_by_burn_block_hash`.

@rafaelcr what do you think?

**Comment by zone117x** [comment]
@rafaelcr I like that approach. A new endpoint that uses filter query params makes sense.

For post-Nakamoto behavior, I think we should only return HTTP 400 for the endpoints that actually break / don't make sense. That will limit the amount of breaking changes to the couple `/extended/v1/block/by_burn_block*` endpoints. We can mark the others as deprecated though so we are more prepared to remove them later on.

**Comment by zone117x** [comment]
Note: this new endpoint should also allow returning blocks from the latest tenure (as requested in https://github.com/hirosystems/stacks-blockchain-api/issues/1755), this could be done by allowing the key `latest` in the `burn_block` filter.
