### ISSUE TITLE
Get unsettled STX blocks

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/stacks-blockchain-api#1757]
Similar to #1755
We also need to retrieve STX blocks that have not yet been settled in a BTC block.
Suggested interface:
GET `/blocks/unsettled?limit={limit}&offset={offset}`
Response:
```
{
    limit: number;
    offset: number;
    total: number;
    results: Array<Block>;
}
```

**Comment by zone117x** [comment]
Is `unsettled` the correct terminology here? It sounds like this request is asking for blocks in the current/latest tenure.

**Comment by He1DAr** [comment]
I'm not sure about the term. But the idea is correct (getting blocks in the current/latest tenure).

**Comment by zone117x** [comment]
Implementation note:
This can be implemented by querying the `blocks` table to return the latest rows that have the same `burn_block_hash` value. Query would look something like:
```sql
SELECT *
FROM blocks
WHERE burn_block_hash = (
    SELECT burn_block_hash
    FROM blocks
    WHERE canonical = true
    ORDER BY block_height DESC
    LIMIT 1
)
AND canonical = true
ORDER BY block_height DESC;
LIMIT ${limit}
OFFSET ${offset}
```

**Comment by zone117x** [comment]
@He1DAr this endpoint is looking a bit redundant given how similar the current `/extended/v1/block` endpoint is. Fetching blocks from the latest tenure is already very straightforward, and cache-friendly for both the server and client:
```js
const endpoint = 'https://api.hiro.so/extended/v1/block';
const response = await fetch(endpoint);
const blocks = await response.json();

// Extract the latest burn_block_hash from the first entry
const latestBurnBlockHash = blocks.results[0].burn_block_hash;

// Filter results to only include items with the latest burn_block_hash
const latestTenureBlocks = blocks.results.filter(item => item.burn_block_hash === latestBurnBlockHash);
```

Does this approach work for you?

**Comment by zone117x** [comment]
The endpoint described in this issue would provide that: https://github.com/hirosystems/stacks-blockchain-api/issues/1755

In fact, it might make sense to expand that endpoint so that you could pass the string `latest`, e.g.:
* `/v1/blocks/many_by_burn_block/{hash}`
* `/v1/blocks/many_by_burn_block/latest`

That would pretty much be the functionality requested in this issue. Thoughts?

**Comment by He1DAr** [comment]
This is a great idea!

**Comment by zone117x** [comment]
Closing this issue in favor of https://github.com/hirosystems/stacks-blockchain-api/issues/1755, and left a note in that issue as well
