### ISSUE TITLE
Implement parsing for `revoke-delegate-stx` pox event

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1761]
PR https://github.com/stacks-network/stacks-core/pull/4094 adds a new pox event for the `revoke-delegate-stx` action. This should be parsed and stored in the pox events table similar to the other synthetic pox events.

**Comment by zone117x** [comment]
These changes are now in PR https://github.com/stacks-network/stacks-core/pull/4157

**Comment by janniks** [comment]
fixed by https://github.com/hirosystems/stacks-blockchain-api/pull/1829
