### ISSUE TITLE
testnet tx propagation delay

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/stacks-blockchain-api#1770]
I'm having stability issues on testnet. Running a stacks node and api instance for lnswap but I'm noticing some transactions not being propagated even though leather wallet logs that they've been published.

for instance
my wallet broadcasted this transaction but it's not visible on the explorer or node/api.
eb4e51bb459288c000437f1af05351c0ca892a57831f8ac79c07110fcfb73d4a

After a few days I just checked this tx again and now it's visible so maybe this is some sort of propagation delay?
https://explorer.hiro.so/txid/0xeb4e51bb459288c000437f1af05351c0ca892a57831f8ac79c07110fcfb73d4a?chain=testnet

I'm still opening this issue to understand if this can be mitigated? is there something I can do to reduce this delay? Because if we show the user the tx and user is not able to see it on hiro explorer that's not a great UX.

**To Reproduce**
1. go to testnet.lnswap.org 
2. create a swap, lock some funds OR do any other testnet tx to ** a different node other than hiro's own nodes **
3. click the explorer link to visit explorer
4. tx is not there for a prolonged period of time

**Comment by smcclellan** [comment]
@pseudozach This looks to be fixed now. Please verify on your end and reopen if needed.
