### ISSUE TITLE
Make batch api endpoints. Eg, a batch endpoint for contract information

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/stacks-blockchain-api#1780]
Several apps, leather and platform, are hitting api limits. Creating batch endpoints could help reduce the number of requests these apps are making to the api dramatically

**Comment by rafaelcr** [comment]
@BLuEScioN could you enumerate some of the batch endpoints that would be most useful to you in the short term?

**Comment by BLuEScioN** [comment]
@rafaelcr 
One batch endpoint would be for contracts
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/20312835/1464cb37-5076-42a2-ae70-ed82144a63af)
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/20312835/2643365e-deb9-414d-8ae6-4a56dacd44e5)
Here I have to query the contract endpoint for each address in a project to see if its deployed. It would be helpful to be able to send along an array of contracts I want information on

**Comment by zone117x** [comment]
Isn't there already an endpoint for this? https://docs.hiro.so/api/get-list-of-details-for-transactions

**Comment by BLuEScioN** [comment]
@zone117x I am trying to determine if the contracts have been deployed. So in this case, I do not have a list of tx ids. Platform is not storing teh deployment status of user contracts either. We have to check whether project contracts have been deployed by name.

**Comment by BLuEScioN** [comment]
For this, I only need contract metadata:
txId
txStatus
blockHeight

**Comment by zone117x** [comment]
I can take this one @rafaelcr, I'm kinda in the area right now
