### ISSUE TITLE
Nonce api should detect nonce gaps and fill them with suggested/next nonce

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/stacks-blockchain-api#1788]
**Is your feature request related to a problem? Please describe.**
Nonce gaps are a situation when an address has pending transactions but the nonces do not line up, there are gaps. 
Example: an address' last confirmed transaction nonce is 2, (next possible nonce is 3 in this case). But there are only pending transactions with nonce 4 and 5 for this address. The API will report the next nonce as being "6" (going off the highest pending nonce). 

**Describe the solution you'd like**
The nonce API should realize there is no transaction with nonce 3, and suggest that instead in a situation like this. 

**Describe alternatives you've considered**
An alternative considered is to manage this locally in the wallet by keeping track of nonces used, and to keep track of expiring transactions. Expiring transactions are an important reason for nonce gaps, user error at manual setting of nonces is another common reason. Tracking this locally in the wallet has proved difficult. By adding this enhancement to the API all wallets can benefit from it. It would actually make local tracking more reliable.

**Comment by rafaelcr** [comment]
Hi @314159265359879 , we already have an endpoint that shows you possible missing nonces, etc: https://docs.hiro.so/api/get-the-latest-nonce-used-by-an-account

Can you check if this would work for your needs?

**Comment by smcclellan** [comment]
Marking this one as complete -- please reopen if more is needed here.
