### ISSUE TITLE
Backport fix for `Problematic` status in `/drop_mempool_tx`

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1803]
This was fixed in the Nakamoto pre-release branch: https://github.com/hirosystems/stacks-blockchain-api/pull/1790

We're seeing this happen in epoch2.4 so we need to backport the fix to a stable release.

**Comment by friedger** [comment]
Is there a workaround? Can I clean the mempool manually or something like that?

**Comment by zone117x** [comment]
@friedger release [v7.6.0](https://github.com/hirosystems/stacks-blockchain-api/releases/tag/v7.6.0) includes a fix for this. We currently have it deployed to staging and everything is looking good: https://explorer.hiro.so/?chain=mainnet&api=https://api.stg.hiro.so

We'll be updating our production deployment soon, this issue can be closed
