### ISSUE TITLE
Tx Multiple API documentation is broken

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/stacks-blockchain-api#1806]
This endpoint does not adequately explain how to structure the query. Additionally, the website incorrectly structures the query when adding multiple txs - https://docs.hiro.so/api/get-list-of-details-for-transactions

**Comment by zone117x** [comment]
Thanks for the report @BLuEScioN, the docs issue should be fixed with https://github.com/hirosystems/stacks-blockchain-api/pull/1807 and support for comma-separated arrays will be added in https://github.com/hirosystems/stacks-blockchain-api/pull/1809

**Comment by zone117x** [comment]
Docs are fixed. Support for comma-separated array values are in the /multiple endpoint is deployed to staging, and going to production soon.
