### ISSUE TITLE
Dose "subscribeMempool " function have bugs?

### ISSUE THREAD

**Issue by ZeUSDDev** [hirosystems/stacks-blockchain-api#1822]
When using subscribeMempool, data suddenly stops receiving at some point.
In the previous version, it was received without stopping.
Is there a way to continue receiving without stopping the subscribeMempool function in the current version?

**Comment by zone117x** [comment]
Hello, can you gives some more details? How long after creating the subscription does it stop? Can you share the client code you're using?

**Comment by zone117x** [comment]
I've tested with the following code and not able to reproduce:
```js
let s = document.createElement('script');
s.src = "https://www.unpkg.com/@stacks/blockchain-api-client@7.7.2/lib/index.umd.js";
document.head.appendChild(s);
s.onload = () => {
  let client = new StacksBlockchainApiClient.StacksApiSocketClient({url: 'https://api.hiro.so/'});
  client.subscribeBlocks(block => console.log('block', block));
  client.subscribeMempool(tx => console.log('mempool', tx));
};
```

Please feel free to re-open or comment with more info
