### ISSUE TITLE
API does not return results sorted correctly on testnet

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/stacks-blockchain-api#1856]
I am seeing an API error where it returns the same results no matter the order arguments supplied. I just ran this query https://api.testnet.hiro.so/extended/v1/tx/mempool?order_by=age&order=asc&limit=30&offset=0&unanchored=true with order set to asc and desc and compared the json and got the exact same result. 

This seems to only be happening on testnet. 

Repro:
Go to https://explorer.hiro.so/address/ST319CF5WV77KYR1H3GT0GZ7B8Q4AQPY42ETP1VPF?chain=testnet
Checkout pending transactions
Use the filter dropdown to sort the txs
The tx list always comes back the same

**Comment by smcclellan** [comment]
This could be that the wrong version is deployed on testnet. @rafaelcr to investigate.

**Comment by smcclellan** [comment]
This is updated on testnet, please check out @BLuEScioN.
