### ISSUE TITLE
nft_custody table index crashes

### ISSUE THREAD

**Issue by bestmike007** [hirosystems/stacks-blockchain-api#1881]
**Describe the bug**
api process crashes with error: `duplicate key value violates unique constraint nft_custody_unique` or `table tid from new index tuple (13373,41) overlaps with invalid duplicate tuple at offset 4 of block 6211 in index nft_custody_recipient_asset_identifier_index`

@rafaelcr @CharlieC3 

**To Reproduce**
1. Clone https://github.com/alexgo-io/stacks-node-mainnet and run `setup.sh`, and restore the backup from https://github.com/alexgo-io/stacks-node-mainnet/releases/tag/block-140976
2. Start the postgres: `docker-compose up -d stacks-blockchain-postgres`
3. Run the sql to check if there is duplicates: `select asset_identifier, value, count(*) from nft_custody group by 1,2 having count(*) > 1;`
4. Replace the stacks-blockchain-api image in docker-compose.yml using hirosystems/stacks-blockchain-api:7.8.2
5. run `./start.sh`
6. `watch 'curl -s http://127.0.0.1:3999/extended/v1/status'`
7. the api crashes at block height 141038: `docker logs -f --tail=100 stacks_api`
8. and then it restore by itself and crashes again at block height around 141064 and keeps crashing

You might possibly run into another issue described in https://github.com/hirosystems/stacks-blockchain-api/pull/1878

**Expected behavior**
Stacks node sync until it reaches tip.

**Screenshots**

Screenshot from step 3:
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/432106/c9826c01-45d3-4e67-b31a-930b5374bd4b)

Screenshot from step 7:
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/432106/7171a28e-0ddf-471b-92dd-5913d3e5aede)

Screenshot from step 8:
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/432106/8427dd33-b3b8-4ee7-b51b-5a878321e3f8)

**Console log**
N/A

**Additional context**
The vm I'm using to run the steps: 4vCPU, 16G memory, 320GB disk

**Comment by CharlieC3** [comment]
@bestmike007 It looks like there are some special considerations to take into account when performing a pg backup directly from a data dir [as you're doing here](https://github.com/alexgo-io/stacks-node-mainnet/wiki) that can cause problems in restorations, such as certain files and directories to omit from the backup.
https://www.postgresql.org/docs/current/continuous-archiving.html#BACKUP-LOWLEVEL-BASE-BACKUP-DATA

Are you able to try restoring your data using one of Hiro's archives via `pg_restore` [as documented here](https://docs.hiro.so/hiro-archive)? If you see the same problem occurring there, then it would provide something more for us to go off of.

**Comment by bestmike007** [comment]
What's wrong with the cold backup? https://www.postgresql.org/docs/current/backup-file.html#BACKUP-FILE

**Comment by bestmike007** [comment]
update: after applying those 2 PRs and redo the steps, there were still those similar errors but it went through.

Let me redo it again with the official image.

**Comment by bestmike007** [comment]
And again it crashes at block height 141064:

<img width="1436" alt="image" src="https://github.com/hirosystems/stacks-blockchain-api/assets/432106/fa038da4-5e79-42d0-a772-b36af4c67329">

**Comment by smcclellan** [comment]
I understand that this is an issue with setup rather than the API. Closing for now. Please reach out on Discord if this is still an issue.
