### ISSUE TITLE
subscribeBlocks & subscribeMempool Not Working

### ISSUE THREAD

**Issue by Kye0001** [hirosystems/stacks-blockchain-api#1885]
Hi! dev teams.

I am making code with your api.
Here is my computer info.
Mac OS Sonoma14.4
Node 18.19.1
NPM 10.2.4
Your API version: 7.8.2

Here is the typescript code

`
import * as stacks from '@stacks/blockchain-api-client';

const socket = io("https://api.mainnet.hiro.so/");
const sc = new stacks.StacksApiSocketClient(socket);

const client = await stacks.connectWebSocketClient('wss://api.mainnet.hiro.so/');

sub = await sc.subscribeBlocks(async(event) =>{})
sub = await sc.subscribeMempool(async(event) => {})
sub = await client.subscribeBlocks(async(event) =>{})
sub = await sc.subscribeMempool(async(event) => {})
`

All four types of codes automatically terminate after a maximum of 3 to 4 hours.

I look the prev solution? code your team provided.
`
let s = document.createElement('script');
s.src = "https://www.unpkg.com/@stacks/blockchain-api-client@7.7.2/lib/index.umd.js";
document.head.appendChild(s);
s.onload = () => {
  let client = new StacksBlockchainApiClient.StacksApiSocketClient({url: 'https://api.hiro.so/'});
  client.subscribeBlocks(block => console.log('block', block));
  client.subscribeMempool(tx => console.log('mempool', tx));
};
`

What is "StacksBlockchainApiClient"?
How to implement that library?
And Is there any other example code or documentation that might be relevant?

**Comment by zone117x** [comment]
@Kye0001 if you specify the `transports` option explicitly then the code works, here's an example:

```js
let s = document.createElement('script');
s.src = "https://www.unpkg.com/@stacks/blockchain-api-client@7.10.0/lib/index.umd.js";
document.head.appendChild(s);
s.onload = () => {
  let client = new StacksBlockchainApiClient.StacksApiSocketClient({
      url: 'https://api.mainnet.hiro.so/',
      socketOpts: {
          transports: ['websocket'], // <-- workaround
      }
  });
  client.subscribeBlocks(block => console.log('block', block));
  client.subscribeMempool(tx => console.log('mempool', tx));
};
```

We'll look into making this the default behavior, but for now it must be specified.
