### ISSUE TITLE
Can not connect localhost:3999 when run " docker run -p 3999:3999 hirosystems/stacks-blockchain-api-standalone "

### ISSUE THREAD

**Issue by louisdangw3** [hirosystems/stacks-blockchain-api#1902]
i do 
- git clone : https://github.com/hirosystems](https://github.com/hirosystems/stacks-blockchain-api.git
- cd with stack-blockchains-api
- run npm install 
- run : docker run -p 3999:3999 hirosystems/stacks-blockchain-api-standalone
but i can not connect with port 3999 in localhost  .
this is logs with docker . pleaze check with me 
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/79962567/2ac686ed-d7c0-4de5-a38a-7f3c381f066d)
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/79962567/f77e7ce7-9b63-4a67-b08d-524572f7264b)
![image](https://github.com/hirosystems/stacks-blockchain-api/assets/79962567/82fa95fb-d9b3-47d6-b339-94e50f28a1bf)

**Comment by zone117x** [comment]
This workflow is no longer supported, and we should remove this from the readme (unless we decide to repair this workflow).
