### ISSUE TITLE
Add number of stackers to `/pox/cycles/{cycle_number}` endpoint

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/stacks-blockchain-api#1953]
Slack context: https://hiropbc.slack.com/archives/C03UFUA5Q65/p1713303894476729

I am trying to build this UI. From inspecting the new api endpoints, it seems the data available looks like this:
{
  "signing_key": "0x0343b909be3379621d5e68a883e6c74c2222666f4bf6cc38fade2c9d1c57d92213",
  "weight": 2,
  "stacked_amount": "3286590000000000",
  "weight_percent": 66.66666666666666,
  "stacked_amount_percent": 66.66666666666667
}
This enables me to fill out some of the information in the design but not all of it. The data I am missing is:

- [X] Signer key associated address
- [ ] ~Last vote slot~
- [ ] The number of addresses stacking

![Image](https://github.com/hirosystems/stacks-blockchain-api/assets/20312835/47819fb2-477e-4a0f-b9bd-977d8e51ef8e)

Regarding signer key associated addresses:
From Matt:
this endpoint will give you stackers/addresses for a given signing_key /extended/v2/pox/cycles/{cycle_number}/signers/{signer_key}/stackers
 https://stacks-blockchain-api.vercel.app/#tag/Proof-of-Transfer/operation/get_pox_cycle_signer_stackers

Regarding last vote slot:
It sounds like there is some confusion here. What does this mean? @andresgalante can you elaborate here?

Regarding # addresses stacking:
From Matt:
I think this might be a property we can add to the /extended/v2/pox/cycles/{cycle_number} endpoint -- 
[@rafael](https://hiropbc.slack.com/team/U02A4BLB3FF)
 what do you think?

**Comment by andresgalante** [comment]
The last vote seems to have been taken during the design phase from Solana's dashboard https://solanabeach.io/validators, which was mentioned as a resource [here](https://github.com/hirosystems/explorer/issues/1248#issuecomment-1883296471).

We can remove it.
