### ISSUE TITLE
List of pool members is empty for Fast Pool

### ISSUE THREAD

**Issue by friedger** [hirosystems/stacks-blockchain-api#1973]
**Describe the bug**
List of delegating pool members is empty for Fast Pool

**To Reproduce**
1. Visit https://api.mainnet.hiro.so/extended/v1/pox3/SP21YTSM60CAY6D011EZVEVNKXVW8FVZE198XEFFP.pox4-fast-pool-v3/delegations
2. See no result

**Expected behavior**
All delegatees should be accessible

**Additional context**
For xverse pool, there are some pool members listed: https://api.mainnet.hiro.so/extended/v1/pox3/SPXVRSEH2BKSXAEJ00F1BY562P45D5ERPSKR4Q33/delegations

**Comment by zone117x** [comment]
@friedger did you intend to use `pox3` in the url? There are entries for `pox4`: https://api.mainnet.hiro.so/extended/v1/pox4/SP21YTSM60CAY6D011EZVEVNKXVW8FVZE198XEFFP.pox4-fast-pool-v3/delegations

**Comment by smcclellan** [comment]
Closing as this may be resolved by the above comment.
