### ISSUE TITLE
Update burn-blocks endpt. in client lib

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/stacks-blockchain-api#1981]
Update burn-blocks endpt. in client lib to include new data
```

 "avg_block_time": 0,
 "total_tx_count": 42
```

Slack context: https://hiropbc.slack.com/archives/C03UFUA5Q65/p1715900265004569

**Comment by zone117x** [comment]
Can you ensure you are using version v7.11.0-beta.5 or later? These haven't made it into a stable release yet.

**Comment by smcclellan** [comment]
This should be resolved with the latest release. Please reopen if this is still an issue.
