### ISSUE TITLE
Ensure API support of OrderIndependentMultisigSpendingCondition

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1984]
New transaction wire format implemented in https://github.com/stacks-network/stacks-core/pull/3710

**In Scope**
* Add unit test for the new wire format
* Resolve any ingestion issues that arise

**Comment by zone117x** [comment]
Deserialization support was implemented in https://github.com/hirosystems/stacks-encoding-native-js/pull/18
This repo needs a unit test that ingests this type of tx ensure everything works correctly.

**Comment by smcclellan** [comment]
I've updated this ticket to include the creation of the unit test & resolution of any ingestion problems.

**Comment by zone117x** [comment]
We can generate these txs in a naka env and use a tsv replay to test cc @janniks
