### ISSUE TITLE
Investigate BTC testnet/regtest faucet functionality

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1988]
The new regtest-based testnet needs a BTC faucet. There is already code in the API that provides this:
https://github.com/hirosystems/stacks-blockchain-api/blob/1a916392add4f93e6321618d183d347f7b9a38ba/src/api/routes/faucets.ts#L85-L87

Need to make sure it still works (hasn't been touched in years) and help devops with configuring it.

**Comment by smcclellan** [comment]
@CharlieC3 Is this going forward?

**Comment by CharlieC3** [comment]
@smcclellan There's a related devops issue with more context here:
https://github.com/hirosystems/devops/issues/1702

**Comment by zone117x** [comment]
Faucet is live. Any additional work to be tracked in the above devops issue
