### ISSUE TITLE
Add signer geolocation to GET /extended/v2/pox/cycles/:cycle_number/signers/:signer_key

### ISSUE THREAD

**Issue by BLuEScioN** [hirosystems/stacks-blockchain-api#1989]
The explorer is adding a world map to the signers page that will show where all the signers are located around the world. In order to build this we would need to add the signers geolocation to the GET /extended/v2/pox/cycles/:cycle_number/signers/:signer_key endpoint
https://www.figma.com/design/31q1g27k69z1yXb6r6vrRD/Stacks-Explorer-Working-File?node-id=7980-57690&m=dev

**Comment by zone117x** [comment]
Endpoint for fetching signer geo-ip implemented in another repo
