### ISSUE TITLE
Add property for estimated balance to balances endpoint

### ISSUE THREAD

**Issue by markmhendrickson** [hirosystems/stacks-blockchain-api#2035]
As discussed [here](https://github.com/hirosystems/stacks-blockchain-api/issues/2026), Leather would benefit from an `estimated_balance` property in addition to the `balance` as returned by the `balances` endpoint for a given Stacks address.

This estimated balance would subtract the total of all outbound transfers from its confirmed balance for a given address.

Leather currently calculates such a balance through two separate queries and a final calculation:

1. fetch balance from `api.hiro.so/extended/v1/address/<address>/balances`
2. fetch pending txs from `api.hiro.so/extended/v1/tx/mempool?address=<address>&limit=50`
3. do calculation: `availableBalance = balance - sum of all outbound transaction amounts`

**Comment by smcclellan** [comment]
Thank you for filing this, @markmhendrickson! I'd like us to separate this into two tickets:
1. The first will capture this new available balance estimation, and add it to a new endpoint.
2. The second will add this new field to the existing endpoint.
The primary reason for this is that the first item is an easy green light, without complication. We can move ahead with the implementation there. The second item requires quite a bit more consideration and maintenance burden around performance and pagination, and therefore would move slower through our development process.

Would implementing the first item, the new endpoint, in the near term be helpful on your end?

**Comment by markmhendrickson** [comment]
Thanks @smcclellan, I suppose step 1 by itself may give us a minor benefit of simplifying our code. However, step 2 would have the most impact by helping us cut down on the number of API queries we generate substantially.

**Comment by rafaelcr** [comment]
@markmhendrickson we are planning on adding the `estimated_balance` key to the balances response, however, we first need to adjust the Etag generation logic a bit to make it be account specific instead of chain tip block height specific (as it is today) so we don't run into any caching issues when wallet users call this endpoint. We'll keep you updated on the work here.

**Comment by wmnonstx** [comment]
@rafaelcr what adjustments are made to "estimated_balance" compared to available balance. 

In Leather we've been accounting for outgoing STX, all pending STX fees for example. 

On the wishlist were any STX transfers for contract calls (which will not always be obvious) but could be deduced from the post-conditions. They would have to be very explicit "transfer exactly xxx STX" adjusting based on "transfer no more than..." or "no less then..." could lead to to much or to small an adjustment.

**Comment by 314159265359879** [comment]
@rafaelcr what adjustments are made to "estimated_balance" compared to available balance.

In Leather we've been accounting for outgoing STX, all pending STX fees for example.

On the wishlist were any STX transfers for contract calls (which will not always be obvious) but could be deduced from the post-conditions. They would have to be very explicit "transfer exactly xxx STX" adjusting based on "transfer no more than..." or "no less then..." could lead to to much or to small an adjustment.

**Comment by rafaelcr** [comment]
@314159265359879 it's the confirmed balance plus any inbound or outbound STX from unconfirmed transactions in the mempool. We don't go so far as to look into post conditions or contract calls though

**Comment by markmhendrickson** [comment]
Bump @314159265359879
