### ISSUE TITLE
automatically mark mempool transactions with conflicting nonces as failed

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#2041]
The API returns a bunch of mempool transactions that are impossible to mine given that they conflict with other **confirmed** transactions from the same senders with the same nonce, so they end up being stuck for days (until they get pruned after 256 blocks). For example, this transaction with nonce `4461` is still pending:

<img width="1267" alt="Screenshot 2024-08-02 at 22 33 06" src="https://github.com/user-attachments/assets/13d8124c-bdd1-404c-8329-3138ff13d558">

However, that sender STX address already has a confirmed transaction with the same nonce (in this case a coinbase, but the same happens with any tx type):

<img width="908" alt="Screenshot 2024-08-02 at 22 34 20" src="https://github.com/user-attachments/assets/8f6dc462-f361-4dd0-bf28-c969f531106b">

These stuck transactions can cause user confusion but they most definitely affect the fee estimation algorithms. (I'm not sure why the Stacks node does not drop them automatically.)

* We should add logic to the API that upon a tx confirmation, it checks the mempool table for txs from that sender with that nonce and marks them as failed or pruned.

**Comment by smcclellan** [comment]
@zone117x for feedback.

**Comment by zone117x** [comment]
> We should add logic to the API that upon a tx confirmation, it checks the mempool table for txs from that sender with that nonce and marks them as failed or pruned.

This makes sense to me. The only thing to be careful about is "restoration" / un-pruning txs during re-orgs when necessary, otherwise it can give the appearance of txs "disappearing", when they are not included in a canonical block and are also pruned from the mempool.
