### ISSUE TITLE
Additional status k/v to show stacks-core proxy status

### ISSUE THREAD

**Issue by wileyj** [hirosystems/stacks-blockchain-api#2046]
in `src/api/routes/status.ts`, it looks like the status endpoint that reports:
```
$ curl -sL localhost:3999/extended/v1/status | jq -r
{
  "server_version": "stacks-blockchain-api v7.13.1-beta.1 (beta:b9843a71f)",
  "status": "ready",
  ...
```

is only reporting the status of the DB connection. 

it would be nice to have another k/v with the stacks-node proxy status, in case there's some issue where the http server is running, but no blocks are being emitted to the event observer. 

someting like this is what i'm thinking of:
```
$ curl -sL localhost:3999/extended/v1/status | jq -r
{
  "server_version": "stacks-blockchain-api v7.13.1-beta.1 (beta:b9843a71f)",
  "status": "ready",
  "stacks-proxy": "ready",
  ...
```

**Comment by zone117x** [comment]
> in case there's some issue where the http server is running, but no blocks are being emitted to the event observer.

@wileyj is this the root issue you're hoping to help by adding to the `/status` endpoint? The communication architecture is:
* a stacks-node sends http requests to an API http server (the event-observer, usually at `STACKS_CORE_EVENT_PORT=3700`)
* an API http server (`STACKS_BLOCKCHAIN_API_PORT=3999`) proxies RPC (`/v2/*`) requests to an optionally configured stacks-node (`STACKS_CORE_RPC_HOST`)

The RPC proxy and the event-observer are separate systems where one can be configured and working while one may have something wrong. So adding a status value for the RPC proxy is not a good signal for the status of the event-observer.

**Comment by wileyj** [comment]
maybe - in this specific case, the proxy was "working" but no data was being returned (i.e. the `/v2` endpoint requests were failing) if i remember correctly.
since the backend server was inaccessible, we were relying on that `status: ready` k/v from the API for system readiness - only to realize later that it wasn't the stacks-node that was ready. 

limited information about the backend stacks-core service - i think it was stalled, so it was alive, just not progressing or accepting requests. 

accepted that this may not be worth doing, just thought it would be nice to have in cases like we encountered. 

@moodmosaic @bowTiedRadone - anything to add here?

**Comment by moodmosaic** [comment]
@zone117x, if adding an additional status key/value isn't feasible, could you confirm if this check suffices?

```js
const url = new URL("/extended", STACKS_CORE_RPC_HOST).toString();
const response = execSync(`curl -s ${url}`).toString();
const data = JSON.parse(response);

const isStatusReady = data.status === "ready";
const isChainTipValid = data.chain_tip &&
  typeof data.chain_tip.block_height === "number" &&
  typeof data.chain_tip.block_hash === "string" &&
  typeof data.chain_tip.index_block_hash === "string" &&
  typeof data.chain_tip.burn_block_height === "number";

return isStatusReady && isChainTipValid;
```

**Comment by zone117x** [comment]
@moodmosaic it depends on what exactly you're testing for. 

> i think it was stalled, so it was alive, just not progressing or accepting requests.

In this case, you'd need to query over time the stacks-node RPC `/v2/info` and the API's `/extended` to check that block heights are increasing.

**Comment by zone117x** [comment]
Closing this issue as I don't think there's anything we can do in this repo to help this situation. But let me know otherwise.
