### ISSUE TITLE
Rosetta API validation with rosetta-cli

### ISSUE THREAD

**Issue by fdmirza** [hirosystems/stacks-blockchain-api#207]
**Is your feature request related to a problem? Please describe.**
We are working on implementation of rosetta-apis. For validation of req/res, we are using [rosetta-cli](https://github.com/coinbase/rosetta-cli). When I start the validation of data API with `check:data` command, I need to make some transactions (send_token, deploy_contract etc) for the rosetta-cli to confirm the responses and reconciliation of account balances. For making the transactions, I am using commands from [cli-blockstack](https://github.com/blockstack/cli-blockstack), and executing them using `child_process` in my test-injections. Is it possible to use the code functions from cli-blockstack directly in this project to make transaction or it has to be done via CLI commands executions for now?

gist: https://gist.github.com/fdmirza/bc8bb206a3c1540a154ece230c5cbfb0

**Comment by zone117x** [comment]
Yes, you should be able to write tests within this repo that use similar code to those in cli-blockstack js commands from that script. There are already similar usages with `fetch` and the `stacks-transactions.js` lib to interact with the core node.

**Comment by zone117x** [comment]
@fdmirza I setup a test suite for rosetta in this PR https://github.com/fariedt/stacks-blockchain-api/pull/2, and left a related comment here https://github.com/blockstack/stacks-blockchain-api/pull/221#issuecomment-685775942.

I think the `rosetta-cli` should probably be ran within docker like the other services. Let me know if you need any help configuring that.

**Comment by zone117x** [comment]
Some additional guidance on how I think the rosetta-cli should be used for testing:

Now that [latest Rosetta PR](https://github.com/blockstack/stacks-blockchain-api/pull/221) includes a jest test suite for end-to-end rosetta testing, I think `rosetta-cli` should be ran either A) within jest, or B) as a new package.json script. E.g. `npm run test:rosetta-cli`. 

The test should be runnable locally and not operating system dependent. For example, it shouldn't require linux or the golang toolchain. I think a new dockerfile might be the best approach.

**Comment by fdmirza** [comment]
@zone117x Created a new dockerfile and running rosetta-cli within container. I am having trouble is figuring out the end conditions. Rosetta-cli config has json field for end-conditions where we can specify index (block-height upto which we want validation), tip (when the tip is reached, specify tip_delay), and reconciliation (float takes 0.0 to 1.0). Please guide me what makes more sense to you that what it should have as ending conditions.
Also, for my test transactions I do some STX transfer transactions, contract deploy and call contract functions in my ts test file. I notice that some (1 or 2) of the transactions fails during the process due to BadNonce and it happens at random in no particular order. I tried adding some delays in the transactions but that didn't help. Any thoughts on it? Thanks

**Comment by zone117x** [comment]
> Also, for my test transactions I do some STX transfer transactions, contract deploy and call contract functions in my ts test file. I notice that some (1 or 2) of the transactions fails during the process due to BadNonce and it happens at random in no particular order. I tried adding some delays in the transactions but that didn't help. Any thoughts on it? Thanks

Await for the next block to allow nonce to increment. For example like this: https://github.com/blockstack/stacks-blockchain-api/blob/2afc27c43e53b20913b29f7dc99ae758a5d756de/src/tests-rosetta/api.ts#L138-L140

> Please guide me what makes more sense to you that what it should have as ending conditions.

Are there examples of good rosetta end-conditions from bitcoin and ethereum implementations?

**Comment by fdmirza** [comment]
@zone117x Both ethereum and bitcoin uses
`"end_conditions": {
   "reconciliation_coverage": 0.95
  }`

**Comment by zone117x** [comment]
Can we do something similar for our end-conditions?

**Comment by zone117x** [comment]
Related to rosetta maintenance work, cc @rafaelcr

**Comment by smcclellan** [comment]
Closing as not under maintenance.
