### ISSUE TITLE
ConflictingNonceInMempool error thrown incorrectly

### ISSUE THREAD

**Issue by bilalanees98** [hirosystems/stacks-blockchain-api#2085]
**Describe the bug**
Broadcasting a transaction using the StacksJs `broadcastTransaction` function yields a `conflictingNonceInMempool` error even though transaction is broadcast.

**Context**
In my application I am creating and broadcasting multiple transactions sequentially in a cron job. Transactions are created with locally specified nonce values. At the start of every cron job local wallet nonce information is updated via this endpoint: https://api.testnet.hiro.so/extended/v1/address/{principal}/nonces and all subsequent broadcasts use `localNonce++`.
Any gaps in nonces are filled by high fee, dummy transactions. The cron job run every 5 mins.

**To Reproduce**
The problem has been difficult to reproduce. It shows up when I attempt to broadcast 50+ transactions (I maintain multiple wallets) in a single cycle.

**What happens**
Occasionally, during the broadcast of a transaction the API/function returns a `conflictingNonceInMempool` error, but upon checking the transaction on the API after a few minutes its found that the transaction with the same txid was broadcast with the correct nonce (the locally calculated value) and it even confirms.

Originally I thought this was a local issue (as in, in my code) but after lots of tinkering and logging I am sure this is originating from elsewhere.

**Expected behavior**
The API should not return an error if the broadcast was successful.

**Screenshots**
Attaching some logs from my application for the transaction: `0x3b57e388e2c5a1994143766497d9c0ae256e10a3579236a344b99e464320d1b2`

![Screenshot 2024-09-24 at 3 46 18 PM](https://github.com/user-attachments/assets/de9f7b10-6b2a-4eeb-8a4e-1a0d198f5d92)

**Some other examples**

- 0x9651928f4da2aecae514f40207adb62eccf71aa04ae5c9ce0da7a9e4ab32ed11
- 0x762ffbbfce4adddc5ce4c1263e978068d660e19bb0eebfdf93e15954fcd36b50

**Frequency**
Out of 450 broadcasts, there were 9 instances of this behavior.

**Comment by zone117x** [comment]
Is your issue primarily with the stacks-node [`POST /v2/transactions`](https://github.com/stacks-network/stacks-core/blob/master/docs/rpc-endpoints.md#post-v2transactions) RPC endpoint behavior? If so, it might make more sense to open this issue in in the core repo https://github.com/stacks-network/stacks-

**Comment by bilalanees98** [comment]
Got it, opening one there: https://github.com/stacks-network/stacks-core/issues/5229. Closing this one.
