### ISSUE TITLE
Get user balances at historic block not working

### ISSUE THREAD

**Issue by radicleart** [hirosystems/stacks-blockchain-api#2099]
**Describe the bug**

The api call to [get user balances](https://docs.hiro.so/stacks/api/accounts/balances) at block height is broken.

**To Reproduce**

1. Go to 'https://api.hiro.so/extended/v1/address/SP3N4AJFZZYC4BK99H53XP8KDGXFGQ2PRSQP2HGT6/balances?until_block=160000'
2. See error
```
"statusCode": 400,
"error": "Bad Request",
"message": "can't handle both 'unanchored' and 'until_block' in the same request"
```

I tried explicitly setting unanchored but get same response; https://api.hiro.so/extended/v1/address/SP3N4AJFZZYC4BK99H53XP8KDGXFGQ2PRSQP2HGT6/balances?until_block=160000&unanchored=false

**Expected behavior**
User balances returned

**Comment by zone117x** [comment]
Good catch! Aiming to get a fix in for next release.

**Comment by radicleart** [comment]
> Good catch! Aiming to get a fix in for next release.

How often are releases @zone117x? This is for the sBTC community vote which is due to go live on the 14th - is before then ?

**Comment by zone117x** [comment]
The fix for this issue has been deployed.
