### ISSUE TITLE
Types for new API client aren't working.

### ISSUE THREAD

**Issue by janniks** [hirosystems/stacks-blockchain-api#2109]
The intended way of using the new `openapi-fetch` client, doesn't work yet; making it hard for developers to transition.

Issue: The `generated/schema` and `types` files are only shipped in `src/` but not in the `lib/` dir, which is used by node (and correctly so).

---

Ref: https://discord.com/channels/621759717756370964/1288837893581832265/1292097445693755393

---

Potential further issue: It doesn't seem like the `params` (e.g. path txid) are type specified in the generated spec either. So fixing the above issue might still leave developers confused about how to add the `opts` object correctly (as well as the `path` {} patterns).

**Comment by friedger** [comment]
Also '"@stacks/blockchain-api-client"' has no exported member 'OperationResponse'.ts
