### ISSUE TITLE
Q: BNS V2 Support

### ISSUE THREAD

**Issue by dantrevino** [hirosystems/stacks-blockchain-api#2165]
What is the status of the BNSv2 API update?  Will BNSv1 still be supported.  I've looked at recent releases and do not see any explicit mentions of BNSv2 support, nor do I see any branches that mention BNSv2.  Developers need to understand how names will be supported.

If I've missed some update, somewhere, a link would be appreciated.

Dan

**Comment by diwakergupta** [comment]
@dantrevino while there has been some discussion around BNS v2 support in the Hiro API, I don't have anything concrete to share at this time.

I would suggest reaching out to Rena or Don at Trust Machines: https://x.com/trustmachinesco/status/1841544611766145437

**Comment by dantrevino** [comment]
Thank you @diwakergupta
