### ISSUE TITLE
Websocket API always returns empty events

### ISSUE THREAD

**Issue by CyrusVorwald** [hirosystems/stacks-blockchain-api#2167]
I think there is a bug in the websocket API. When subscribing to address transactions using address_tx_update, the response includes event_count. Even if event_count is greater than 0, It seems to always return empty events: [] array in the transaction data. This can be reproduced by monitoring contract call transactions that emit events via the websocket API.

**Comment by zone117x** [comment]
Events are not included in the transaction object. The number of events are often too large to reasonable fit. You can use the [`/extended/v1/tx/events`](https://stacks-blockchain-api.vercel.app/#tag/Transactions/operation/get_filtered_events) endpoint to fetch and filter/paginate through transaction events.
