### ISSUE TITLE
Stacks.js Monorepo integration

### ISSUE THREAD

**Issue by agraebe** [hirosystems/stacks-blockchain-api#296]
Let's figure out how to add the client library to the stacks.js monorepo. This goal should ideally include both an integration into the monorepo but also the being released in the same package scope.

Based on initial convos in discord, we have the following options:

1. Generation code inside the monorepo, fetching the OpenAPI.yaml form this repo. This would make the `network` package build more complicated
2. The `network` package could take the generated client lib as a dependency. This would require only moving the non-generated parts to the monorepo
3. Move the OpenAPI.yaml file to the monorepo and this project would fetch the file for docs generation

@yknl and @zone117x - let's continue the conversation in this issues

**Comment by agraebe** [comment]
@yknl - what needs to be discussed as a preparation for this work in a few sprints?

**Comment by asimm241** [comment]
@agraebe What is the status of this?

**Comment by agraebe** [comment]
oh, let's keep this in the icebox for now. thanks for checking

**Comment by sabbyanandan** [comment]
I'd love to be educated on the reasoning behind the client library interop and packaging with `stacks.js`. From what I understand, `stacks.js` continues to be a standalone method in which developers can interact with Stacks blockchain, and are _not_ directly dependent on the API scaffolding. Is this not the case?

**Comment by zone117x** [comment]
@sabbyanandan correct, the network operations in stacks.js are generally related to the stacks blockchain, and not the API endpoints from this repo (with some one off exception around BNS iirc)

**Comment by smcclellan** [comment]
Closing as this hasn't generated traction & definition of the work. We can reopen/revisit in the future.
