### ISSUE TITLE
[@stacks/blockchain-api-client] Add typescript types to TransactionsApi.getTransactionById from 

### ISSUE THREAD

**Issue by pradel** [hirosystems/stacks-blockchain-api#312]
**Is your feature request related to a problem? Please describe.**

TransactionsApi.getTransactionById is currently returning the typescript type `object`.
See https://github.com/blockstack/stacks-blockchain-api/blob/master/client/src/generated/apis/TransactionsApi.ts#L113

**Describe the solution you'd like**

To be more accurate it should return the correct `Transaction` type.

**Describe alternatives you've considered**

For now I am typing it manually.

**Comment by zone117x** [comment]
This is a known issue due to a bug in the openapi-generator tool. As a work around, you use use the `Transaction` type from the [`@blockstack/stacks-blockchain-api-types`](https://www.npmjs.com/package/@blockstack/stacks-blockchain-api-types) package.

**Comment by agraebe** [comment]
can this be closed @zone117x? I see the types package is `@blockstack` - we should update that as well ( ref #194 )

**Comment by sabbyanandan** [comment]
A friendly follow-up, @zone117x. Maybe the `@blockstack` API-type meets the original ask after all — would you agree? If so, we can close it.
