### ISSUE TITLE
Generate more accurate btc StackStxOp tx

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#415]
See https://github.com/blockstack/stacks-blockchain-api/pull/414#discussion_r564097195_

An address used for the stack-stx function arg list recreation needs first output address of the bitcoin transaction. However, this requires more info from the stacks-node event.

**Comment by agraebe** [comment]
is this still relevant (with the mentioned PR merged in)?

**Comment by zone117x** [comment]
Yeah, the txs generated by the API for this are still incorrect. Per Aaron's comment, we need more info from the stacks-node for these events.

**Comment by agraebe** [comment]
do we have an equivalent issue in the stacks-blockchain repo to track that request? I'd say we put this API issue in the icebox while we wait for the upstream info to be available

**Comment by zone117x** [comment]
Issue created https://github.com/blockstack/stacks-blockchain/issues/2591

**Comment by zone117x** [comment]
Closed by https://github.com/hirosystems/stacks-blockchain-api/pull/1533
