### ISSUE TITLE
Docs: Get contract map request body not documented well

### ISSUE THREAD

**Issue by agraebe** [hirosystems/stacks-blockchain-api#452]
The contract map API endpoint requires a request body (hex string) that represents the serialized value of a stacker inside a tuple clarity value. this is not documented. the code:

```
const stackerTuple = tupleCV({
    stacker: standardPrincipalCV("ST3CSKQBMDHMAC5AC4YKMTHANPYVMVWXGA80ZFGKD"),
  });

  // get map
  const map = await contractsApi.getContractDataMapEntry({
    contractAddress: "ST000000000000000000002AMW42H",
    contractName: "pox",
    mapName: "delegation-state",
    key: cvToHex(stackerTuple),
    proof: 0,
  });
```

**Comment by zone117x** [comment]
Closing since the docs for /v2 endpoints have since been moved to their core repo at https://github.com/blockstack/stacks-blockchain/blob/master/docs/rpc/openapi.yaml
