### ISSUE TITLE
Rosetta api validation tests with rosetta-cli

### ISSUE THREAD

**Issue by noumanahmads** [hirosystems/stacks-blockchain-api#537]
The tests should build and run the rosetta-cli docker-container. It should perform some test transactions (transfer, deploy contract, etc), and then validate the resulting output from rosetta-cli.

These tests are already implemented [here](https://github.com/fariedt/stacks-blockchain-api/tree/feat/tests-rosetta-cli) but failing. 
Changes would be required once the rosetta updates are done.

More details [here](https://github.com/blockstack/stacks-blockchain-api/pull/239)

**Comment by agraebe** [comment]
@noumanahmad001 are you working on this already or not yet?

**Comment by noumanahmads** [comment]
@agraebe not yet.
