### ISSUE TITLE
Store contract-call function ABI json in tx table

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#579]
Contract-call tx metadata like the function ABI json should be stored in the tx table for `contract-call` tx types.

Currently the db controller has to perform an additional query for `contract-call` txs to transform the `DbTx` row data into a useful transaction API response object. This introduces transactional consistency bugs due to being two independent sql transaction queries. It's a bottleneck for several areas of the API that need to perform a series of db queries when the `DbTx` objects should be good enough to transform synchronously. 

Affected code:
https://github.com/blockstack/stacks-blockchain-api/blob/37bc66c6b5f9e8a687026810d9b32f2ae104787d/src/api/controllers/db-controller.ts#L651-L678

Additionally, mempool tx parsing just omits this contract-call data for performance and transactional consistency reasons: 
https://github.com/blockstack/stacks-blockchain-api/blob/37bc66c6b5f9e8a687026810d9b32f2ae104787d/src/api/controllers/db-controller.ts#L470-L484

**Comment by zone117x** [comment]
Need to create an issue in the stacks-blockchain repo to request this in the event emitter payload

**Comment by asimm241** [comment]
@zone117x what's the status on this?

**Comment by zone117x** [comment]
I'm moving this to a P4 since this issue hadn't caused serious problems. Also, I don't think we'll be able to get the stacks-node event emitter changes that I last mentioned. 

We could look into adding the contract-call function ABI to the DbTx and DbMempoolTx interfaces, and see if it's reasonable for the related postgres queries to include that data. That would avoid needing to performing ABI lookup queries later on in the parsing code.
