### ISSUE TITLE
Stop using sudo in follower.Dockerfile

### ISSUE THREAD

**Issue by LNow** [hirosystems/stacks-blockchain-api#588]
**Is your feature request related to a problem? Please describe.**
User starting services inside container should not have root privileges nor be member of sudoers group.
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user

**Describe the solution you'd like**
Modify `stx-rosetta.Dockerfile` and `follower.Dockerfile` in such way, that services inside containers will be started by plain user without sudo privilage.

**Comment by LNow** [comment]
This is how `follower.Dockerfile` would look without `sudo`:

```Dockerfile
### Build blockstack-core-sidecar API
FROM node:14-alpine as build
WORKDIR /app
COPY . .
RUN apk add --no-cache --virtual .build-deps alpine-sdk python git openjdk8-jre
RUN echo "GIT_TAG=$(git tag --points-at HEAD)" >> .env
RUN npm config set unsafe-perm true && npm install && npm run build && npm prune --production

### Fetch stacks-node binary
FROM blockstack/stacks-blockchain:2.0.11.0.0-stretch as stacks-node-build

### Begin building base image
FROM ubuntu:focal

SHELL ["/bin/bash", "-c"]

### Install utils
RUN apt-get update
RUN apt-get install -y curl pslist

### Install nodejs
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

### Set noninteractive apt-get
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

### stacky user ###
# see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
RUN groupadd -r -g 33333 stacky \
    && useradd -l -r -u 33333 -g stacky -md /home/stacky -s /bin/bash -p stacky stacky
ENV HOME=/home/stacky
WORKDIR $HOME

### Setup stacks-node
COPY --chown=stacky:stacky --from=stacks-node-build /bin/stacks-node stacks-node/
ENV PATH="$PATH:$HOME/stacks-node"

#### Copy stacks-node mocknet config
COPY ./stacks-blockchain/Stacks-mocknet.toml ./

### Setup stacks-blockchain-api
COPY --chown=stacky:stacky --from=build /app stacks-blockchain-api
RUN printf '#!/bin/bash\ncd $(dirname $0)\nnpm run start\n' > stacks-blockchain-api/stacks_api \
  && chmod +x stacks-blockchain-api/stacks_api
ENV PATH="$PATH:$HOME/stacks-blockchain-api"
EXPOSE 3999

### Install Postgres
RUN apt-get install -y postgresql-12 postgresql-contrib-12

### Setup Postgres
# Borrowed from https://github.com/gitpod-io/workspace-images/blob/master/postgres/Dockerfile
ENV PATH="$PATH:/usr/lib/postgresql/12/bin"
ENV PGDATA="/home/stacky/.pgsql/data"
RUN mkdir -p ~/.pg_ctl/bin ~/.pg_ctl/sockets \
  && printf '#!/bin/bash\n[ ! -d $PGDATA ] && mkdir -p $PGDATA && initdb -D $PGDATA\npg_ctl -D $PGDATA -l ~/.pg_ctl/log -o "-k ~/.pg_ctl/sockets" start\n' > ~/.pg_ctl/bin/pg_start \
  && printf '#!/bin/bash\npg_ctl -D $PGDATA -l ~/.pg_ctl/log -o "-k ~/.pg_ctl/sockets" stop\n' > ~/.pg_ctl/bin/pg_stop \
  && chmod +x ~/.pg_ctl/bin/* \
  && chown -Rh stacky:stacky ~/.pg_ctl/
ENV PATH="$PATH:$HOME/.pg_ctl/bin"

### Clear caches
RUN apt-get clean && rm -rf /var/cache/apt/* /var/lib/apt/lists/* /tmp/*

### Setup service env vars
ENV PG_HOST=127.0.0.1
ENV PG_PORT=5432
ENV PG_USER=stacky
ENV PG_PASSWORD=postgres
ENV PG_DATABASE=postgres

ENV STACKS_CORE_EVENT_PORT=3700
ENV STACKS_CORE_EVENT_HOST=127.0.0.1

ENV STACKS_EVENT_OBSERVER=127.0.0.1:3700

ENV STACKS_BLOCKCHAIN_API_PORT=3999
ENV STACKS_BLOCKCHAIN_API_HOST=0.0.0.0

ENV STACKS_CORE_RPC_HOST=127.0.0.1
ENV STACKS_CORE_RPC_PORT=20443

### Startup script & coordinator
RUN printf '#!/bin/bash\n\
MAINNET_ID=0x00000001\n\
MOCKNET_ID=0x80000000\n\
[ $1 = "mocknet" ] && STACKS_CHAIN_ID="${MOCKNET_ID}" || STACKS_CHAIN_ID="${MAINNET_ID}"\n\
export STACKS_CHAIN_ID\n\
trap "exit" INT TERM\n\
trap "kill 0" EXIT\n\
echo Your container args are: "$@"\n\
tail --retry -F stacks-api.log stacks-node.log 2>&1 &\n\
while true\n\
do\n\
  pg_start\n\
  stacks_api &> stacks-api.log &\n\
  stacks_api_pid=$!\n\
  if [ $1 = "mocknet" ]; then\n\
    stacks-node start --config=/home/stacky/Stacks-mocknet.toml &> stacks-node.log &\n\
  else\n\
    stacks-node mainnet &> stacks-node.log &\n\
  fi\n\
  stacks_node_pid=$!\n\
  wait $stacks_node_pid\n\
  echo "node exit, restarting..."\n\
  rkill -9 $stacks_api_pid\n\
  pg_stop\n\
  rm -rf $PGDATA\n\
  sleep 5\n\
done\n\
' >> run.sh && chmod +x run.sh

USER stacky
ENTRYPOINT ["/home/stacky/run.sh"]

CMD ["/home/stacky/run.sh"]
```

It is also possible to reduce size of final images down to ~800Mb by reorganizing code a little bit.

**Comment by agraebe** [comment]
hey @LNow - this might be an old docker file. @wileyj to chime in.

It would be fantastic if you could create a PR with your suggestions. Is that possible?

**Comment by wileyj** [comment]
rosetta dockerfile has been updated : https://github.com/blockstack/stacks-blockchain-api/blob/master/stx-rosetta.Dockerfile

I'll take a look at the follower dockerfile, but that might be something that can be removed entirely since it should be built from https://github.com/blockstack/stacks-blockchain/blob/master/Dockerfile

**Comment by agraebe** [comment]
pinging @zone117x to continue with the discussion

**Comment by zone117x** [comment]
@wileyj yes I'd appreciate help with getting `follower.Dockerfile` updated, do you still have time to help with that?

**Comment by wileyj** [comment]
> @wileyj yes I'd appreciate help with getting `follower.Dockerfile` updated, do you still have time to help with that?

Sure. I'll look it over, but is there reason you can think of where it needs to differ from [stacks-blockchain Dockerfile](https://github.com/blockstack/stacks-blockchain/blob/master/Dockerfile) ?

To be clear, the updated [rosetta Dockerfile](https://github.com/blockstack/stacks-blockchain-api/blob/master/stx-rosetta.Dockerfile) should supersede the [follower Dockerfile]( https://github.com/blockstack/stacks-blockchain-api/blob/master/follower.Dockerfile)

at most, i'd argue we do some renaming and delete the no longer needed files

**Comment by wileyj** [comment]
re: docker-compose files - we can document/link to the [docker-compose repo ](https://github.com/blockstack/stacks-local-dev)marvin and I have been working on, it seem like it would be able to take over for the existing docker-compose files.

**Comment by zone117x** [comment]
The `follower.dockerfile` creates the `blockstack/stacks-blockchain-api-standalone` image, used for the quick start in the readme:

> A self-contained Docker image is provided which starts a Stacks 2.0 blockchain and API instance.
> 
> Ensure Docker is installed, then run the command:
> 
> ```
> docker run -p 3999:3999 blockstack/stacks-blockchain-api-standalone
> ```
> 
> Similarity, a "mocknet" instance can be started. This runs a local node, isolated from the testnet/mainnet:
> 
> ```
> docker run -p 3999:3999 blockstack/stacks-blockchain-api-standalone mocknet
> ```

It looks like the rosetta one could replace it, but the readme instructions would need tweaked?

----

> docker-compose files - we can document/link to the docker-compose repo marvin and I have been working on, it seem like it would be able to take over for the existing docker-compose files.

The docker-compose files in this repo are actually used for development of the API, not intended for production or external usages.  
https://github.com/blockstack/stacks-blockchain-api/blob/22e9a4f64f093fd9982dde570e18278b65e4b934/package.json#L24-L28

But yeah it sounds useful to link to the https://github.com/blockstack/stacks-local-dev repo for those that want to use that setup.

**Comment by wileyj** [comment]
I see, thanks!
the follower  dockerfile *can* be replaced by the rosetta file (functionally, they're the same - they just achieve the results in a slightly different manner). 

if the docker-compose files are used for local development, and you still want to keep them here - i'd propose we move them to a different directory at the very least. 

i see what you're saying about the package.json - i'd like to say we can get rid of these files, but without using a submodule or requiring extra steps, it may not be a good idea to delete these files. but, no reason we can't organize it a bit better, and try to get some parity since we keep that other repo's docker-compose files up to date.

**Comment by wileyj** [comment]
@zone117x pushed a branch (above)  that should clean the docker footprint up a bit, but it may cause some issues with existing services (vercel check failed for example). 
locally testing, everything seems to work on my end - curious what you think of these changes, if this goes a little too far etc.

**Comment by zone117x** [comment]
@wileyj seems like a good change to me, want to open a PR for it?
I think we'd also need to update the `quick start` readme instructions.

**Comment by wileyj** [comment]
> @wileyj seems like a good change to me, want to open a PR for it?
> I think we'd also need to update the `quick start` readme instructions.

I can take a look sure, add that to the branch. good call on the docs/readmes, i'll have to double-check that (particularly the docs.stacks.co pages for the API).
