### ISSUE TITLE
Handle re-orgs for the ft/nft metadata tables

### ISSUE THREAD

**Issue by asimm241** [hirosystems/stacks-blockchain-api#639]
**Describe the bug**
There are forking scenarios that aren't handled by the queries against the ft_metadata and nft_metadata tables.

See details here : https://github.com/blockstack/stacks-blockchain-api/pull/576#discussion_r664776323

**Comment by asimm241** [comment]
@zone117x do we need to add `microblock_hash, microblock_sequence, microblock_canonical` to these tables as well in addition to `canonical`. ?

**Comment by zone117x** [comment]
Correct

**Comment by sabbyanandan** [comment]
A lot of rich dialog and commentary at https://github.com/hirosystems/stacks-blockchain-api/pull/576, which attempts to address the said bug(s). Not entirely clear whether we are kosher with the improvements or what is pending. 

Perhaps @asimm241, if you could clarify what remains, it would help very much. 🙏🏽

**Comment by asimm241** [comment]
@sabbyanandan I'm not sure but I think this should be closed now.  We decided to work on it after the  #743
but then It was decided that we are not going to implement #743. So this issue should be closed now.

**Comment by asimm241** [comment]
I have verified the code that this PR has already merged in
https://github.com/hirosystems/stacks-blockchain-api/pull/576. So no need to worry. We can just close it

**Comment by sabbyanandan** [comment]
Thanks for checking and the follow-up, @asimm241.

**Comment by zone117x** [comment]
#743 is unrelated to this task which I believe is still outstanding

**Comment by rafaelcr** [comment]
Deprecated by #1222
