### ISSUE TITLE
Endpoint for contracts that implement a given trait

### ISSUE THREAD

**Issue by aulneau** [hirosystems/stacks-blockchain-api#649]
I was speaking with @zone117x and I think it'd be great if we had an endpoint that would expose all contracts that implement a specific trait. I personally think there are many instances where someone might want to get a list of contracts that all implement a trait, for example all contracts that implement the stacking pool trait, or all sip 10 contracts.

> aulneau
> is there a way to get a list of all contracts that implement a certain trait?
>
>mattl
> hmm. no endpoints at the moment, but I think it would be possible to implement, at least for contracts that explicitly implement a trait, like with this syntax (impl-trait 'STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6.nft-trait.nft-trait)
but I think contracts can implicitly implement a trait, as in they don't have to specify that impl-trait but they will still be treated as a contract with that trait if the correct functions are implemented
in that case, I think maybe the client could POST the trait JSON ABI, and I could write some interesting postgres json queries to find those contracts

**Comment by friedger** [comment]
There was already a discussion here for `stacks-blockchain`: https://github.com/blockstack/stacks-blockchain/issues/2382

If filter by json abi works that would be cool!

**Comment by zone117x** [comment]
@aulneau let me know if you think this should be bumped in priority.
