### ISSUE TITLE
Add partial text matching to search endpoint

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#650]
There's a handful of cases where it would be useful for the search endpoint to be able to return results for partial text matches. Some examples: a contract name, token name, truncated hex IDs (some products show first ~6 chars of a block or tx hash similar to git short-hashes). 

The associated sql columns just need a special index type to allow fast partial matching.

**Comment by sabbyanandan** [comment]
It'd be very useful indeed, yes! Performance, however, is a paramount concern as you're indirectly alluding to it via indexes. 😃

**Comment by sabbyanandan** [comment]
We will revisit this once we have a demand for such an endpoint.
