### ISSUE TITLE
Bug: `tx_index` likely no longer a logical ordering of transactions

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#662]
`tx_index` is likely no longer a logical ordering of transaction is it was intended, see https://github.com/blockstack/stacks-blockchain/issues/2668#issuecomment-847010900 -- likely needs fixed in core then API can be updated to use it.

**Comment by asimm241** [comment]
@zone117x what is the status of this, is this fixed in the core?

**Comment by zone117x** [comment]
AFAIK core still has the issue described in the referenced comment, so this isn't actionable in the API codebase.

I've recently seen different API instances getting different transaction ordering from the event payloads received from core, so that non-determinism needs addressed there.

**Comment by asimm241** [comment]
@zone117x I have tried to fix this issue here: blockstack/stacks-blockchain#2906.

**Comment by zone117x** [comment]
PR https://github.com/stacks-network/stacks-blockchain/pull/2906 has merged and scheduled for the next release of the stacks blockchain. This issue can be tackled in the API once that happens.

**Comment by asimm241** [comment]
@zone117x This PR is released in the [latest](https://github.com/stacks-network/stacks-blockchain/releases/tag/2.05.0.1.0) release of stacks-blockchain.

**Comment by zone117x** [comment]
@asimm241 in that case a the API should be updated to use the stacks-node provided `tx_index` rather than inferring the value which is error prone.

**Comment by asimm241** [comment]
@zone117x API is already using tx_index returned from the node message:
 https://github.com/hirosystems/stacks-blockchain-api/blob/cd0c8aef94b4eda9cb045e93f9aa730f400821fc/src/datastore/common.ts#L1063
 
 https://github.com/hirosystems/stacks-blockchain-api/blob/cd0c8aef94b4eda9cb045e93f9aa730f400821fc/src/event-stream/core-node-message.ts#L167

**Comment by asimm241** [comment]
The microblocks also uses the same tx_index returned from the stacks-blockchain.
