### ISSUE TITLE
Empty events array in address transaction history endpoint 

### ISSUE THREAD

**Issue by yknl** [hirosystems/stacks-blockchain-api#668]
The events array for transactions from the `/extended/v1/address/${stxAddress}/transactions)` endpoint seems to be empty even though the events count is showing non-zero. 

For example:
Querying `https://stacks-node-api.stacks.co/extended/v1/address/SPR7RRXN8ZRXPNAFKPN2TB84J7T1RMZRGWQQV7P3/transactions`

The transaction with ID `0x32ac0d3cf8cb08b1e9f5bd2509c10b6ad46d955b1cac269a8f19d332ca090a93`
shows that there are 2 events, but the events array is empty.

Querying the transaction endpoint directly shows the correct events.
`https://stacks-node-api.stacks.co/extended/v1/tx/0x32ac0d3cf8cb08b1e9f5bd2509c10b6ad46d955b1cac269a8f19d332ca090a93`

**Comment by zone117x** [comment]
Transaction events are only returned for the tx specific endpoint, and are paginated. Historically all events were returned for all txs in every endpoint, but that resulted in sql queries and JSON responses becoming way too large. In certain cases like the genesis transactions, the results would be several megabytes in size. 

If you happen to be looking for STX transfer related events, see the endpoint `https://stacks-node-api.stacks.co/extended/v1/address/SPR7RRXN8ZRXPNAFKPN2TB84J7T1RMZRGWQQV7P3/transactions_with_transfers`.

**Comment by yknl** [comment]
Ok makes sense. But maybe the empty events array should be removed from the response to avoid confusion.
