### ISSUE TITLE
OpenAPI spec: Add linting rules

### ISSUE THREAD

**Issue by agraebe** [hirosystems/stacks-blockchain-api#745]
It seems like it is possible to [lint YAML files](https://stoplight.io/open-source/spectral/). We could use this to ensure that the OpenAPI spec includes all mandatory fields and follows best practices guidelines. 

These guidelines would become more clear once we did a manul review of the current file, likely in the next quarter.

cc @pgray-hiro

**Comment by zone117x** [comment]
@agraebe this was closed by https://github.com/hirosystems/stacks-blockchain-api/pull/882 right?

**Comment by agraebe** [comment]
correct!

**Comment by followmisha** [comment]
**BE COOL**
