### ISSUE TITLE
Add documentation and examples for the socket-io client library

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#786]
We currently have a [docs page setup for our WebSockets client](https://blockstack.github.io/stacks-blockchain-api/client/index.html), but it doesn't mention anything about the new socket-io implementation (which AFAIK we plan on supporting more in the future).

We should either add a section to this document that covers socket-io or replace it altogether to encourage new developers to use the newer client library.

**Comment by agraebe** [comment]
fully agreed! apart from the references, we should also:
-  create some sample code for most important use cases
- add a guide inside the documentation (cc @pgray-hiro)

@zone117x do you think Tintash can help with the references and/or the sample code creation? or would this be better handled by you/Rafael?

**Comment by zone117x** [comment]
@kyranjamie made an RxJS library for this feature when it was implemented during the hackathon. Perhaps that is a good starting pointing / reference?

**Comment by rafaelcr** [comment]
Great example of a community-written article (on websockets but the contents for socket.io would be practically the same) https://www.eriksuniverse.com/stacks-blockchain-api-architecture-websocket-message-flow.html
