### ISSUE TITLE
subscribe to anchor blocks or microblocks via websocket

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/stacks-blockchain-api#815]
**Is your feature request related to a problem? Please describe.**
I have an app that creates swaps that expire on a certain blockheight for this I need to periodically check if there's a new block. 

**Describe the solution you'd like**
I'd like to have a way to subscribe to anchor block updates with the websocket and preferably also microblock updates. So Everytime there's a new anchor block or microblock a message would be triggered. I could update my app db and go fetch the block contents if I'm interested in them.

**Describe alternatives you've considered**
I'm currently querying get_block_list with limit=1 every minute.

**Comment by rafaelcr** [comment]
@pseudozach this is resolved, it will be available in the next API release.
