### ISSUE TITLE
A heartbeat for web sockets

### ISSUE THREAD

**Issue by PUN-app** [hirosystems/stacks-blockchain-api#820]
Please give web sockets a heart beat.  Ideally every 5 seconds, but could be as long as 15 seconds.  

This permits keep alive, health check, and can spawn recovery on the client side.  

@agraebe I could blog on a breakdown on how current clients handle web sockets pub/sub today in the browser to help create a better use case to drive requirements if that helps.

**Comment by rafaelcr** [comment]
@PUN-app this feature is now merged to `develop`, it will be available to use in our next release.
