### ISSUE TITLE
Inconsistency of API database transaction recording (and unclear dedup logic)

### ISSUE THREAD

**Issue by BowTiedArcticWolf** [hirosystems/stacks-blockchain-api#844]
**Describe the bug**
Seems that API database has some missing transactions (also dedup logic is not clear)

**To Reproduce**
Stacks punks should have only 10000 punks minted. When I try to recover this number from the database I have some trouble reconciling the number of transactions.

The following SQL query should yield exactly 10000:
```
# select count(*)  from txs 
  where contract_call_contract_id = 'SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.stacks-punks-v3' 
  and contract_call_function_name = 'mint' and status = 1;
 count 
-------
 10506
(1 row)
```

The table txs has multiple transactions recorded for the same tx_id:
```
# select count(*) from (select tx_id, count(*) from txs group by tx_id having count(*) > 1) dups;
 count 
-------
 54070
(1 row)
```

so if I dedup by block_height I get less than 10000:
```
# CREATE OR REPLACE VIEW txs_tmp
AS
 SELECT * FROM (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY tx_id ORDER BY block_height DESC) 
    FROM public.txs 
 ) dedup WHERE row_number = 1;

# select count(*)  from txs_tmp 
   where contract_call_contract_id = 'SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.stacks-punks-v3' 
   and contract_call_function_name = 'mint' and status = 1;
 count 
-------
  9535
(1 row)
````

**Expected behavior**
The number of successfully minted punks must be 10000

**Comment by zone117x** [comment]
Like most blockchains, Stacks has forks. Anything monitoring and collecting chain data in realtime must account for anchor re-orgs, and (in the case of Stacks) orphaned microblocks.

Modify your queries to only include canonical results, e.g.
```sql
select count(*)  from txs 
  where contract_call_contract_id = 'SPJW1XE278YMCEYMXB8ZFGJMH8ZVAAEDP2S2PJYG.stacks-punks-v3' 
  and contract_call_function_name = 'mint' and status = 1
  and canonical = true and microblock_canonical = true
```

```sql
select count(*) from (
  select tx_id, count(*) from txs group by tx_id, canonical, microblock_canonical 
  having count(*) > 1 and canonical = true and microblock_canonical = true) dups
```

**Comment by zone117x** [comment]
Oops, didn't mean to close this right away! Let me know if you have any more questions/concerns, or if you still are finding anything that looks like a discrepancy. There have been re-org handling logic bugs in the past and there could certainly be more. But so far no evidence of that.

**Comment by BowTiedArcticWolf** [comment]
Thank you for your comprehensive clarification (pun!)

Interesting, so I see how to dedup, but there are still not 10k punks minted, only 9533. Probably they were pre-minted - I will check the contract.

Just to be clear, is the same logic apply to nft_events, stx_events, and ft_events?

**Comment by zone117x** [comment]
Correct
