### ISSUE TITLE
Error reading contract ABI

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#850]
Seeing a critical error in parsing tx responses:
`/extended/v1/tx/0x8407751d1a8d11ee986aca32a6459d9cd798283a12e048ebafcd4cc7dadb29af`

```
TypeError: Cannot read property 'functions' of null
    at parseContractCallMetadata (/app/src/api/controllers/db-controller.ts:996:35)
    at /app/src/api/controllers/db-controller.ts:925:27
    at Array.forEach (<anonymous>)
    at parseContractsWithDbTxs (/app/src/api/controllers/db-controller.ts:922:13)
```

The contract ABI json object is null here: https://github.com/hirosystems/stacks-blockchain-api/blob/285632a983f2ae83d4f6250c339898dda75bb14e/src/api/controllers/db-controller.ts#L995

Seems like this bug was introduced in https://github.com/hirosystems/stacks-blockchain-api/pull/722

@MHassanTariq can you take a look?

**Comment by MHassanTariq** [comment]
Sure, I'll look into it.

**Comment by MHassanTariq** [comment]
@zone117x the `abi` is [required](https://github.com/hirosystems/stacks-blockchain-api/blob/develop/src/datastore/common.ts#L232) in `DbSmartContract`. Therefore, I ignored this edge case. 
I will put a check for `abi` here. Thanks for pointing it out!

**Comment by asimm241** [comment]
@zone117x The `abi` is not supposed to be null here and this endpoint does not always fail doesn't this means the issue is not on the API side?

**Comment by zone117x** [comment]
Here's some db data for the smart contract referenced by the above tx `0x8407751d1a8d11ee986aca32a6459d9cd798283a12e048ebafcd4cc7dadb29af`:

```sql
SELECT canonical, microblock_canonical, encode(tx_id, 'hex') tx_id, (abi = 'null') has_abi
FROM smart_contracts
WHERE contract_id = 'SP3YK7KWMYRCDMV5M4792T0T7DERQXHJJGGEPV1N8.pg-mdomains-v1'
```
```
 canonical | microblock_canonical |                              tx_id                               | has_abi 
-----------+----------------------+------------------------------------------------------------------+---------
 t         | t                    | 668142abbcabb846e3f83183325325071a8b4882dcf5476a38148cb5b738fc83 | f
 t         | t                    | ab599004a2c4b5a11010b90ee44dfbdac4ec6c8c673f8feed3fb78026625e10e | t
 t         | t                    | 76496849991130ca5a08a4f16e7f24f98a039daaecf36f59f12b65ad31196ef4 | t
(3 rows)
```

There are three txs that attempted to deploy the contract, and only one succeeded and has an `abi`.

Can also verify by checking the `status` of the associated txs:
```sql
select canonical, microblock_canonical, status, encode(tx_id, 'hex') tx_id from txs
where tx_id in (select tx_id from smart_contracts where contract_id = 'SP3YK7KWMYRCDMV5M4792T0T7DERQXHJJGGEPV1N8.pg-mdomains-v1')
```
```
 canonical | microblock_canonical | status |                              tx_id                               
-----------+----------------------+--------+------------------------------------------------------------------
 t         | t                    |      1 | 668142abbcabb846e3f83183325325071a8b4882dcf5476a38148cb5b738fc83
 t         | t                    |     -1 | 76496849991130ca5a08a4f16e7f24f98a039daaecf36f59f12b65ad31196ef4
 t         | t                    |     -1 | ab599004a2c4b5a11010b90ee44dfbdac4ec6c8c673f8feed3fb78026625e10e
(3 rows)
```

All but one have `status: -1` (`abort_by_response`)

**Comment by asimm241** [comment]
That's interesting @MHassanTariq Thanks for the insight.
