### ISSUE TITLE
Issues related to sponsored transactions

### ISSUE THREAD

**Issue by hstove** [hirosystems/stacks-blockchain-api#857]
I've been playing with sponsored transactions, and I've noticed a few bugs related to how the API handles these transactions:

The biggest issue is probably related to fees, and how balances are effected. I'm not sure what the "root" payload is for sponsored transactions, but it appears that I can set two things:
- sender spending condition fee
- sponsor spending condition fee

What happens is the "sender fee" is picked up by the API as the "fee", even though this fee has no effect. The "sponsor fee", a different value, is not picked up by the API. Downstream, an effect is that the sender's balance is updated (using the void fee), and the sponsor's balance is not effected.

I first noticed this because I ended up with an account with a negative balance (according to the API). Core node APIs reflect balances as expected.

The secondary issue is related to nonces. The sponsor's nonce is not picked up, so the usual nonce APIs are incorrect for that principal. This isn't the end of the world, as the sponsor is running some backend service and can keep track of it. It would be really great to have _some_ index of this in the future, though.

Here is a [STX address with a negative balance](https://explorer.stacks.co/address/SPY3T5EAGZQYCG3294CYSQGZB6CADZX9V17C0XNB?chain=mainnet). The first and only transaction from that account is sponsored, but these bugs are unrelated to whether the account had any balance before. 

The [sponsor](https://explorer.stacks.co/address/SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE?chain=mainnet) of that transaction has an incorrect balance from the API. The 'sponsor fee' was 0.1 STX, and you can see there is that discrepancy between the explorer / API and the [core node /v2/accounts](https://stacks-node-api.stacks.co/v2/accounts/SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE) response.

To repro, just follow the example in the [stacks.js README](https://github.com/blockstack/stacks.js/tree/master/packages/transactions#sponsoring-transactions).

**Comment by zone117x** [comment]
Thanks for the detailed report! Sponsored transactions haven't been given much attention. The sample addresses you provided should help us fix this pretty easily.
