### ISSUE TITLE
Event Replay TSV grows with frequent restarts

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#862]
**Describe the bug**
I've noticed the TSV file grows pretty rapidly when the API undergoes frequent restarts (once every hour or so). Right now a "healthy" TSV file will be about 1.9GB for the current state of the blockchain. After running an API which gracefully exits and restarts once every hour for 2 weeks, the TSV has grown to 42.4GB.

**To Reproduce**
1. Run the API and configure it to export to TSV.
2. Restart the API once every hour for a week or two and observe the TSV unnaturally grow in size

**Expected behavior**
The TSV file should only increase in size due to the blockchain progressing, in a slow pattern which matches that of an API which does not undergo frequent restarts.

API version `0.71.0`.

**Comment by CharlieC3** [comment]
It seems the postgres database is also growing at the same rate along with the TSV file. The disk of the pg database is roughly the same size as the TSV file. And if the large TSV file is deleted and the API's `export-events` function is called to create a new TSV file, the resulting new TSV file will be the same large size (>40GB) as it were before.

This seems to indicate that the problem may not reside in what is written to the TSV file, but rather the content that an API node receives and writes to the DB. Not sure if this would indicate an issue with the stacks-node however, but it may be possible.

**Comment by zone117x** [comment]
@CharlieC3 and I think we have this solved. It appeared to be an issue with termination signals not being sent correct from k8s to the API process, causing non-graceful force kills which can end up with in-progress sql commits being dropped and other issues. The deployment has been updated and so far seems to be working as expected.

**Comment by CharlieC3** [comment]
I'm fairly confident the issue has been resolved. Our snapshot API deployment has been getting restarted frequently throughout this week and its TSV is still 2.3 GB. A `pg_dump` of the database is only 1.1 GB.

To give some context for posterity, it was failing because I was launching an additional shell in the API's docker container, then launching the API within that shell. It was a necessity for the time being some other tasks needed to be ran before launching the API, but it inadvertently causes OS signals to not propagate to the API process. Removing the additional shell and just letting the container launch the API directly, with its default docker `CMD` directive, fixes the shutdown issue.

Thanks for the help on this @zone117x! Closing this issue.

**Comment by CharlieC3** [comment]
This seems to still be occurring despite seeing graceful shutdowns in the API.

**Comment by CharlieC3** [comment]
This is now fixed and can be closed. Thanks for checking @rafaelcr!
