### ISSUE TITLE
v2/fees/transaction endpoint is missing on mocknet

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/stacks-blockchain-api#865]
please bump stacks-blockchain version to `2.05.0.0.0` or at least `2.0.11.4.0`. Currently when running mocknet instance with this command
>docker run -p 3999:3999 blockstack/stacks-blockchain-api-standalone mocknet

the api doesn't have `v2/fees/transaction` endpoint which hiro web wallet looks for to build fees.

I hope it's as easy as changing this line?
https://github.com/hirosystems/stacks-blockchain-api/blob/master/stacks-blockchain/docker/Dockerfile#L1

**Comment by rafaelcr** [comment]
I believe @wileyj had this bump in progress on this branch https://github.com/hirosystems/stacks-blockchain-api/compare/develop...feat/docker-cleanup
Could we take this opportunity to move to `2.05.0.0.0` @wileyj ? Let me know if I can help

**Comment by pseudozach** [comment]
@rafaelcr I don't see the stacks-blockchain version being changed in that PR.
https://github.com/hirosystems/stacks-blockchain-api/blob/feat/docker-cleanup/stacks-blockchain/docker/Dockerfile#L1
this is still the old version that doesn't have this endpoint right? so it won't help.

**Comment by rafaelcr** [comment]
@pseudozach you're right, good catch. we'd only updated it in one Dockerfile

**Comment by pseudozach** [comment]
is this resolved? I'm still not getting a response for /transaction endpoint on `docker pull blockstack/stacks-blockchain-api-standalone:0.71.2` or `latest`.

**Comment by rafaelcr** [comment]
we're working on a release as we speak https://github.com/hirosystems/stacks-blockchain-api/pull/877 @pseudozach

**Comment by pseudozach** [comment]
I'm confused about this comment, 0.71.2 doesn't have this right?
https://github.com/hirosystems/stacks-wallet-web/issues/2010#issuecomment-985982106
