### ISSUE TITLE
Possibility to run DB schema migrations on startup

### ISSUE THREAD

**Issue by wileyj** [hirosystems/stacks-blockchain-api#870]
During a schema change for a new release, the only upgrade path outside of wiping data and resyncing from genesis is to replay the events file. 
This capability isn't widely known/enabled and when it's not run prior to upgrading, the errors are a bit misleading (it appears like there is an issue in the postgres db):
```
{
  "error": "error: column \"execution_cost_read_count\" does not exist",
  "stack": "error: column \"execution_cost_read_count\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
  "errorTag": "567978f0-2131-45a0-8f8d-ee9920caba81"
}
```

Ideally, what I'd like to see happen is that for schema changes, when the API is upgraded - during startup a migration script is run to adjust the DB schema and optionally to run the replay event file if it exists (it might make sense to enable this event file by default).

**Comment by zone117x** [comment]
The db schema migrations (files under `src/migrations/*`) _are_ ran automatically on startup, however, it's pretty frequent, historically at least, that the schema changes add new data that there is nothing in the db to migrate from. In other words, it hasn't been typical that we do something like rename a column or change the formatting of a column, or other types of schema changes where a seamless sql migration is actually possible.

For example the error posted above, missing `execution_cost_read_count` cost column, can't be migrated without just setting all existing rows to `0` or `null`.

As frustrating as it can be, in those case the only possible upgrade path is via event-replay or re-sync. 

There is certainly room for improvement here, for example the error message / failure mode is super unhelpful. And we don't always know/remember to update the CHANGELOG manually when this condition happens (https://github.com/hirosystems/stacks-blockchain-api/issues/871).

Another thing we can do is cut a `1.0` release of the API, and start following semver for these situations.

**Comment by zone117x** [comment]
> during startup ... optionally to run the replay event file if it exists

This could be helpful once we have a system in place to better track _when_ we need to do this. But I'd be concerned with the length of time this process could take. For example, if the `stacks-node` emitter isn't shutdown, I think it could end up in a bad state. @CharlieC3 @wileyj do we know if the `stacks-node` can spin on event emission retrying for hours at a time without bad things happening?

**Comment by CharlieC3** [comment]
> do we know if the stacks-node can spin on event emission retrying for hours at a time without bad things happening?

I haven't seen an issue from this before. I've scaled down APIs over multiple days while its stacks-node emitter continued to run, and it was able to resume operations as normal once the API was scaled back up.

> Another thing we can do is cut a 1.0 release of the API, and start following semver for these situations

Looking at the commit message convention and github workflow steps, I think we're already following semantic versioning for this repo?

**Comment by wileyj** [comment]
I had a feeling i wasn't going to like the answer here, but it's understandable. 
I wonder if there's something we could do outside of the API codebase to help alleviate this (kind of like v1's fast-sync feature).  
I'll think on that idea a bit, but for now this issue can be closed.

**Comment by CharlieC3** [comment]
> Doesn't `0.*` indicate "beta, don't expect semver compatibility", or am I thinking of something else?

Sem Ver has general suggestions about when to release `1.0.0` or what version to start at, but the release guidelines can be followed at any point; there's no hard requirements. [More info here.](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)

**Comment by zone117x** [comment]
It sounds like we should cut a `1.x` so we also have the ability to use typical semver comparisons in code to more easily catch breaking schema changes like mentioned at https://github.com/hirosystems/stacks-blockchain-api/issues/871#issuecomment-986937608

**Comment by zone117x** [comment]
@wileyj 
> I'll think on that idea a bit, but for now this issue can be closed.

👍 
We can track the related improvements in https://github.com/hirosystems/stacks-blockchain-api/issues/871 for now
