### ISSUE TITLE
Automatically add "event replay or genesis sync required" note to CHANGELOG when necessary

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#871]
For every new API release, we have to manually determine whether or not users would need to perform an event replay or full genesis sync to use the newer version (if anything from the DB changes). Furthermore, we have to add this note to the CHANGELOG by hand to let them know.

Ideally, we could set a rule to the CHANGELOG generator that detects changes in the `/src/migrations` directory to add this note automatically.

**Comment by wileyj** [comment]
#870

**Comment by CharlieC3** [comment]
This can be completed by using the [semantic-release/exec plugin](https://github.com/semantic-release/exec). Adding an `exec` entry between [these two lines](https://github.com/hirosystems/stacks-blockchain-api/blob/master/package.json#L78-L79) which runs a script or command would take care of it.

**Comment by smcclellan** [comment]
`semantic-release` has been implemented, so this is no longer needed.
