### ISSUE TITLE
Expose events-only tx endpoint

### ISSUE THREAD

**Issue by aulneau** [hirosystems/stacks-blockchain-api#875]
Hi there!

Currently when i'm working with transaction data, (eg fetching all transactions for a given principal), none of the events data is included in the transaction object. As such I need to do a secondary fetch for each transaction to the `/extended/v1/tx` endpoint to grab only the events.

I was thinking it'd be really helpful to have an endpoint at something like `/extended/v1/tx-events` that could take either a single `tx_id`, or an array of `tx_ids`.

Curious what you all think, or if there is a better solution!

**Comment by rafaelcr** [comment]
Hi @aulneau , could you give me an example on the type of events you're looking for? I believe we already have some endpoints that could help here but IIRC they're specific to certain event types

**Comment by aulneau** [comment]
@rafaelcr sure!

Here is an example: https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.marketplace-v4/transactions

When you fetch the transactions for a given principal, you can see this is a response that has events (see event_count), but they are not included in this response.

```json
{
      "tx_id": "0x1bfa0b6a0ff4944f3faae78e6445ca3b5bf00cd9e91657504cf8b52727c12153",
      "nonce": 142,
      "fee_rate": "5000",
      "sender_address": "SP2Q1SZSETS27AZ9FE0BH6C6B7MVC25E4N6C2VE7D",
      "sponsored": false,
      "post_condition_mode": "deny",
      "post_conditions": [
        {
          "type": "non_fungible",
          "condition_code": "sent",
          "principal": {
            "type_id": "principal_contract",
            "contract_name": "marketplace-v4",
            "address": "SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S"
          },
          "asset": {
            "contract_name": "bitcoin-monkeys",
            "asset_name": "bitcoin-monkeys",
            "contract_address": "SP2KAF9RF86PVX3NEE27DFV1CQX0T4WGR41X3S45C"
          },
          "asset_value": {
            "hex": "0x0100000000000000000000000000000988",
            "repr": "u2440"
          }
        }
      ],
      "anchor_mode": "any",
      "is_unanchored": false,
      "block_hash": "0x85f472adf2a4d5020e21794eb029a28b19b8d47954ade97796f7c7a4d9eb437c",
      "parent_block_hash": "0x1fd6b585e3cfaa409f6e2225c6efaada9302d5591d016ef8c5daf21000cb5657",
      "block_height": 41507,
      "burn_block_time": 1639501089,
      "burn_block_time_iso": "2021-12-14T16:58:09.000Z",
      "parent_burn_block_time": 1639500907,
      "parent_burn_block_time_iso": "2021-12-14T16:55:07.000Z",
      "canonical": true,
      "tx_index": 49,
      "tx_status": "success",
      "tx_result": {
        "hex": "0x0703",
        "repr": "(ok true)"
      },
      "microblock_hash": "",
      "microblock_sequence": 2147483647,
      "microblock_canonical": true,
      "event_count": 1,
      "events": [],
      "execution_cost_read_count": 10,
      "execution_cost_read_length": 45934,
      "execution_cost_runtime": 93241,
      "execution_cost_write_count": 2,
      "execution_cost_write_length": 85,
      "tx_type": "contract_call",
      "contract_call": {
        "contract_id": "SPNWZ5V2TPWGQGVDR6T7B6RQ4XMGZ4PXTEE0VQ0S.marketplace-v4",
        "function_name": "unlist-asset",
        "function_signature": "(define-public (unlist-asset (tradables trait_reference) (tradable-id uint)))",
        "function_args": [
          {
            "hex": "0x0616a6a7a70f41adbe8eae708ed7ec2cbf41a27218200f626974636f696e2d6d6f6e6b657973",
            "repr": "SP2KAF9RF86PVX3NEE27DFV1CQX0T4WGR41X3S45C.bitcoin-monkeys",
            "name": "tradables",
            "type": "trait_reference"
          },
          {
            "hex": "0x0100000000000000000000000000000988",
            "repr": "u2440",
            "name": "tradable-id",
            "type": "uint"
          }
        ]
      }
    }
```

As such, I need to do a secondary fetch to the `tx` endpoint to get all events for this transaction. There is a lot of duplicate data being returned, where as i'd much prefer to just fetch the events for a given tx_id.

Lmk if you need more info!

**Comment by rafaelcr** [comment]
I see, thanks for the explanation @aulneau . So if I understand correctly, you're not necessarily looking for only one particular event type, right? Rather, all event types related to one particular `tx_id` or principal.

We don't have an event like that right now, but I believe we could create one where you filter out events by type, tx_id, principal, etc. Our worry, however, is that the query will be a very heavy one because we want to avoid returning all events and paginating as that would result in a massive query.

We could make this new endpoint to always be constrained to the last N events, for example, or so that it always requires a filter parameter so operations get much smaller. We could use a materialized view for this purpose, cc @zone117x in case you have more thoughts here.

Do you think something like this could work @aulneau ? Maybe it would solve #883 as well

**Comment by aulneau** [comment]
> We don't have an event like that right now, but I believe we could create one where you filter out events by type, tx_id, principal, etc.
> ...
> We could make this new endpoint to always be constrained to the last N events, for example, or so that it always requires a filter parameter so operations get much smaller.

Yeah, I think pagination is totally fine and should be the case! A paginated, multi-purpose "tx events" endpoint where you can filter by type, principal, tx_id, etc would be amazing and def solve #883 too

**Comment by sabbyanandan** [comment]
Hi, @aulneau! https://github.com/hirosystems/stacks-blockchain-api/pull/1027 is close to getting merged; if you could try out the latest commit from the PR and let us know your thoughts, we would appreciate it.
