### ISSUE TITLE
Refactor all usages of `router.getAsync(...)` to `asyncHandler`

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#878]
https://github.com/hirosystems/stacks-blockchain-api/blob/8d6738817ee88f924ca964319fa125f0b725a4a6/src/api/async-handler.ts

Creating this issue from comment at https://github.com/hirosystems/stacks-blockchain-api/pull/834#discussion_r762938701

We've been using `router.getAsync` for all of the API routes. This function is an Express extension provided by the [`@awaitjs/express` lib](https://www.npmjs.com/package/@awaitjs/express). However, the `router.getAsync(<route>, handler1, handler2, handler3...)` function has incorrect/bugged behavior when given multiple router handler functions. It executes both synchronously at the same time, breaking the ability for the handlers to control the route flow based on the order in which they are specified.

Additionally, the `@awaitjs/express` lib is incorrectly typed. The `router.*Async(...)` functions incorrectly expect a `void` (synchronous) handler rather than a promise, which has forced this repo to disable the `@typescript-eslint/no-misused-promises` eslint rule, which could have prevent numerous bugs and PR review change-requests.

A better alternative has been implemented in [`src/api/async-handler.ts`](https://github.com/hirosystems/stacks-blockchain-api/blob/8d6738817ee88f924ca964319fa125f0b725a4a6/src/api/async-handler.ts) which can be used like:
* Before: `router.getAsync('/', async (req, res) => { ... })`
* After: `router.get('/', asyncHandler(async (req, res) => { ... })`

A cursory look shows we have ~60 usages. The refactor is pretty simple, but it tends to result in many LOC changes due to indentation changes, so it ends up being a bit disruptive to other PRs currently in-flight.

**Comment by followmisha** [comment]
**@diwakergupta @lgalabru**
