### ISSUE TITLE
Implement http cache-control for mempool-sensitive routes

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#879]
Follow up to https://github.com/hirosystems/stacks-blockchain-api/pull/834#issuecomment-986670782

Many of the endpoints can check the mempool, which means a "state hash" of the mempool needs to be used in conjunction with the chain-tip. This can be done with a query like
```sql
SELECT digest(
(
    SELECT array_agg(tx_id)
    FROM (
        SELECT tx_id
        FROM mempool_txs
        WHERE pruned = false
        ORDER BY receipt_time DESC
    ) m
)::text, 'sha256')
```
Could also be a materialized view that is refreshed on mempool table updates. Note: this is not memory-friendly query as this concats all the mempool txids at once rather than stream/aggregate the rows, but the mempool table is small enough now to not cause a problem (yet). The latest version of pg has an aggregator function (`bit_xor`) that could be used with something like:
```sql
select bit_xor(tx_short_id)
from (
    SELECT ('x' || encode(tx_id, 'hex'))::bit(64)::bigint tx_short_id
    FROM mempool_txs
    WHERE pruned = false
    ORDER BY receipt_time DESC
) m
```
However, google cloud has not yet released support for pg14 -- should be easy enough to refactor the query once available.

**Comment by CharlieC3** [comment]
@zone117x PG14 is now being used.

**Comment by zone117x** [comment]
@rafaelcr can I assign this to you?

**Comment by rafaelcr** [comment]
Depends on #1059
