### ISSUE TITLE
Endpoint to get all events of certain type

### ISSUE THREAD

**Issue by aulneau** [hirosystems/stacks-blockchain-api#883]
Similar to https://github.com/hirosystems/stacks-blockchain-api/issues/875 (maybe could be added as a param to that endpoint), being able to fetch a paginated list of all events (not specific to a tx_id) of a given event_type would be very helpful.

**Comment by rafaelcr** [comment]
Thanks @aulneau, could you give us a bit more context on what use case you need this endpoint for? We'd like to figure out the best way to solve this and/or what additional data we'd need to return on this new endpoint

**Comment by aulneau** [comment]
@rafaelcr sure thing! I would like to be able to fetch data for all "stx_lock" events, or data for all "smart_contract_log" where x = y. Ideally I'd also be able to search for all events where principal Z is a participant. eg "all smart_contract_log events where principal z was a participant in the transaction"

There are really limitless use cases for this kind of querying. Lmk if i can provide more information.
