### ISSUE TITLE
socket.io logs all blocks by default

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/stacks-blockchain-api#897]
Hi,
Is it possible to disable default logging of socket.io block contents? it's very noisy in application logs.

`connect` and `disconnect` is good to have but contents of all blocks I think should be left to the client to log them or not.

https://github.com/hirosystems/stacks-blockchain-api/blob/043f04538cc0044312a0e8deaa74e4a3731c69f9/client/src/socket-io/index.ts#L116

**Comment by rafaelcr** [comment]
Fixed on https://github.com/hirosystems/stacks-blockchain-api/pull/884
