### ISSUE TITLE
Add FT (SIP 10) endpoints

### ISSUE THREAD

**Issue by wbnns** [hirosystems/stacks-blockchain-api#923]
**Is your feature request related to a problem? Please describe.**
At present it's difficult for developers and integrators to query contract data in a uniform way. This makes it more difficult to build out platforms and middleware on Stacks. When we recently launched XBTC on Okcoin, they were querying the Stacks explorer, which provides information that is divergent from the SIP 10 standard and lead to confusion[1][2].

**Describe the solution you'd like**
Adding endpoints for SIP 10 (fungible token standard) read-only functions like `get-name`, `get-symbol`, `get-total-supply` will make it easier to build out platforms that are incorporating fungible tokens from Stacks.

[1] https://github.com/hirosystems/explorer/issues/603
[2] https://github.com/hirosystems/explorer/issues/604

**Comment by zone117x** [comment]
Those contract functions can be called with the RPC endpoint [`POST /v2/contracts/call-read/[Stacks Address]/[Contract Name]/[Function Name]`](https://github.com/blockstack/stacks-blockchain/blob/master/docs/rpc-endpoints.md#post-v2contractscall-readstacks-addresscontract-namefunction-name).

The API sql db does not have this data, and the stacks-node does not emit this data through the event observer. So this request is not actionable for this repo.

**Comment by wbnns** [comment]
@zone117x 

Heya! Ok, understood. Thanks so much for taking a look, here. Happy holidays!
