### ISSUE TITLE
Pagination seems broken on `extended/v1/tx/block_height/42041`

### ISSUE THREAD

**Issue by Jamil** [hirosystems/stacks-blockchain-api#924]
For blocks with a large number of transactions, the pagination returns the same transaction ID multiple times, when setting offsets. Try iterating through this block with offset in multiples of `96` or `200`; you never get all the transactions in the block, and some are duplicated.

**Comment by Jamil** [comment]
Related: number of transactions per block is different in `https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/block_height/42041` (shows a list of 987 transactions, or, after deduplication, 872 transactions). This is different from the `total: 870` returned by the `/tx/block_height` endpoint.

**Comment by zone117x** [comment]
Thank you for the detailed report. Verified the issue, working on a fix.

**Comment by zone117x** [comment]
@Jamil the two bugs you identified have been fixed in the `develop` branch. Note that the Hiro API deployment won't include these fixes until after the holidays.
