### ISSUE TITLE
`/extended/v1/block/by_height` is returning duplicate tx_ids

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#948]
Example: https://stacks-node-api.mainnet.stacks.co/extended/v1/block/by_height/42882
Appearing twice: `0xdd14b762603db082bb823f66b3d139da4c2204b55719f9b4ae2b2194af8f0c0f`, `0x12fdb920c97bf301709aafc97771020be7c0a177eeee78482ed631b694f4e030`

This could be due to non-canonical txs and/or a table relationship that is not filtering for canonical correctly.

**Comment by zone117x** [comment]
Looks like a dupe issue, already fixed in develop https://github.com/hirosystems/stacks-blockchain-api/pull/931

**Comment by rafaelcr** [comment]
@zone117x you're right, thanks 👍
