### ISSUE TITLE
Rosetta /account/balance call is returning an incremented nonce one block too early

### ISSUE THREAD

**Issue by kmur911** [hirosystems/stacks-blockchain-api#955]
**Describe the bug**
For these two transactions ([1](https://explorer.stacks.co/txid/0xe2a56741db5ea3bad7b50cd9df544ff60d64a94f13eecc433c779076cbf440dd?chain=testnet) [2](https://explorer.stacks.co/txid/0x65b5488940c36e91536f7057b14a892faabc10a2868fea57750f3fb582b172dd?chain=testnet)) we've seen the `/account/balance` call return the incremented nonce one block before the transaction was finalized.

For example, for the [first](https://explorer.stacks.co/txid/0xe2a56741db5ea3bad7b50cd9df544ff60d64a94f13eecc433c779076cbf440dd?chain=testnet) the explorer shows that the transaction landed (incrementing the nonce from 173->174) in block #21499. However, when calling `/account/balance` and getting back the result for block #21498, it returned a nonce of 174, when it should only have returned that at block #21499. It's worth pointing out that the returned balance at block #21498 was correct (i.e it didn't factor in the balance change from the transaction), it's only the nonce that seems to have been incremented one block prematurely.

For the [second](https://explorer.stacks.co/txid/0x65b5488940c36e91536f7057b14a892faabc10a2868fea57750f3fb582b172dd?chain=testnet) the explorer shows that the transaction landed (incrementing the nonce from 0->1) in block #26289. However, when calling `/account/balance` and getting back the result for block #26288, it returned a nonce of 1, when it should only have returned that at block #26289. Same as before, the balance at #26288 was correct (9.174474 STX), it didn't factor in the balance change from the transaction, it's only the nonce that seems to have been incremented one block prematurely.

**To Reproduce**
It's hard to reproduce this issue because it's intermittent, not happening for every account we control. However it is only happening on accounts where we're generating outgoing transactions, so I'm wondering if the node which broadcasts the transaction is jumping the gun on the nonce increment by 1 block. For example, we run 4 stacks nodes, and alternate between them when fetching `/account/balance` information. I wonder if we broadcast the transaction through one node, would the nonce returned by that node's `/account/balance` call increment by 1 a block earlier than the other nodes?

**Expected behavior**
`/account/balance` for all nodes should only return the incremented nonce at the block height in which the transaction is finalized for all nodes

**Comment by rafaelcr** [comment]
Thanks for the report. From an initial quick look, it seems this issue could be more about the Stacks node than the API, since that endpoint makes an RPC to the Stacks node to get the nonce and other account information. We'll keep looking and get back ASAP. cc @zone117x @CharlieC3

**Comment by zone117x** [comment]
@rafaelcr yep you're right. That route queries postgres for info specific to a given block (if provided in the POST request), _except_ for the nonce fetch which unconditionally fetches "latest" from the stacks-node:
https://github.com/hirosystems/stacks-blockchain-api/blob/7a314437717e62aeaeb34d11de653364e1476acf/src/api/routes/rosetta/account.ts#L66-L70


```ts
// BAD: queries stacks-node for account info at block tip, ignoring any specified request block
const accountInfo = await new StacksCoreRpcClient().getAccount(accountIdentifier.address);
const nonce = accountInfo.nonce ?? 0;
```

We have an existing query `db.getAddressNonces(...)` to determine account nonce from the pg data which I think we can use instead. However, it needs a modification to support querying for a given block height. Seems relatively straightforward. I'll open a PR soon.

**Comment by kmur911** [comment]
Thank you both for the quick turnaround! @rafaelcr @zone117x
