### ISSUE TITLE
validate socket.io topic subscriptions

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#958]
we ocasionally get socket.io subscriptions to invalid topics like `stacks-node-api-green-address-transaction:[object Object]}`, `stacks-node-api-green-transaction:null`, `stacks-node-api-green-address-transaction:undefined}`. We should add validation to make sure all topics are well formed when connecting.

**Comment by rafaelcr** [comment]
@MHassanTariq exactly, we'd have to add that topic validation both on connect and subscribe. For example, if we receive a topic with the value `address-transaction:xxxxx`, we'd have to validate that `xxxxx` is a valid STX address and reject the subscription if it isn't.

We do have [tests for sockets](https://github.com/hirosystems/stacks-blockchain-api/blob/master/src/tests/socket-io-tests.ts#L22).

**Comment by MHassanTariq** [comment]
Makes sense. Thanks a lot!
