### ISSUE TITLE
Database connection errors after DB restart

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#960]
**Describe the bug**
The API logs errors on what seems to be all database interactions after a scenario where the database connection is severed (e.g. database restarts), and then re-established. Despite these errors logged, the API is still reporting 200-level status codes and is able to perform reads/writes to the database.

Below log snippets may be out of order, but meant to roughly show what's going on:

```
{"level":"error","message":"Error sending PgNotifier notification of type: microblockUpdate Client has encountered a connection error and is not queryable","stack":"Error: Client has encountered a connection error and is not queryable\n    at /app/node_modules/pg/lib/client.js:563:27\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)","timestamp":"2022-01-05T18:43:18.878Z"}
...
{"level":"error","message":"Error sending PgNotifier notification of type: addressUpdate Client has encountered a connection error and is not queryable","stack":"Error: Client has encountered a connection error and is not queryable\n    at /app/node_modules/pg/lib/client.js:563:27\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)","timestamp":"2022-01-05T18:54:53.457Z"}
...
{"level":"error","message":"Error sending PgNotifier notification of type: txUpdate Client has encountered a connection error and is not queryable","stack":"Error: Client has encountered a connection error and is not queryable\n    at /app/node_modules/pg/lib/client.js:563:27\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)","timestamp":"2022-01-05T18:54:53.645Z"}
...
# Still returns 200 status codes though despite errors
{"req":{"url":"/new_mempool_tx","headers":{"host":"my-api-host.com:3700","content-length":"642","date":"Wed, 05 Jan 2022 18:48:00 GMT","content-type":"application/json"},"method":"POST","httpVersion":"1.1","originalUrl":"/new_mempool_tx","query":{}},"res":{"statusCode":200},"responseTime":17,"level":"http","message":"HTTP POST /new_mempool_tx","timestamp":"2022-01-05T18:48:00.619Z"}
```

**To Reproduce**
1. Run an API + stacks-node + database
2. Restart the database
3. Observe API logs. It should log to severed connection, re-connect once the database boots back up, and continue printing error logs on every subsequent database interaction.

**Expected behavior**
Once the database connection is re-established, the API should not encounter any further database errors.

API Version: `1.0.4`

**Comment by rafaelcr** [comment]
@CharlieC3 After digging into this, I noticed the issue is that our `PgNotifier` class keeps a single pg client active throughout the whole session to monitor and send LISTEN/NOTIFY messages, while the regular API code opens and closes clients on demand when it needs to query the DB. This is why the API can recover gracefully but the notifier stops working (unfortunately yes, this means all socket messages stop working).

I'll write a PR to fix this.

Note: I wasn't really able to replicate this locally. I tried with the mocknet but couldn't get the client to produce the same error.

**Comment by zone117x** [comment]
Does P2 still make sense for this issue?

**Comment by CharlieC3** [comment]
> Does P2 still make sense for this issue?

@zone117x I think so, since a DB restart causes socket messages to stop working according to @rafaelcr.

**Comment by rafaelcr** [comment]
To be clear, I'm not 100% sure that is the case @CharlieC3 since the library does reconnect locally. If possible, I'd like to test this in a mainnet pod to reproduce and figure out the next steps.

**Comment by rafaelcr** [comment]
@CharlieC3 just helped me test on a mainnet pod and we can confirm the socket.io/websocket connections do break when this error occurs, unfortunately
