### ISSUE TITLE
API is returning incorrect sequence number after update to v1.0.5

### ISSUE THREAD

**Issue by kmur911** [hirosystems/stacks-blockchain-api#961]
**Describe the bug**
I believe this is related to the fix shipped in https://github.com/hirosystems/stacks-blockchain-api/releases/tag/v1.0.5.

After updating the node api to v1.0.5 (redeploying using an existing node snapshot), making the call to /account/balance with the following POST body
```
{
  "network_identifier": {
    "blockchain": "stacks",
    "network": "testnet"
  },
  "account_identifier": {
    "address": "ST3XNSE77C2J2EJ7ESVXHTG3904C7GRNKH4CCM85K"
  },
  "block_identifier": {
    "hash": "0x74b6f26700ae744d2f4a21965424d65b1c74214ba48a33bae30f78605ef6ff9a",
    "index": 27041
  }
}
```

I'm getting the response
```
{
    "block_identifier": {
        "index": 27041,
        "hash": "0x74b6f26700ae744d2f4a21965424d65b1c74214ba48a33bae30f78605ef6ff9a"
    },
    "balances": [
        {
            "value": "120",
            "currency": {
                "symbol": "STX",
                "decimals": 6
            }
        }
    ],
    "metadata": {
        "sequence_number": 0
    }
}
```
even tho address [ST3XNSE77C2J2EJ7ESVXHTG3904C7GRNKH4CCM85K](https://explorer.stacks.co/address/ST3XNSE77C2J2EJ7ESVXHTG3904C7GRNKH4CCM85K?chain=testnet) has a nonce of 1 and has since [this](https://explorer.stacks.co/txid/0x603328f0d593786a31763db97814158a8d9d6535ebdad332f3810b6c24c4a0e9?chain=testnet) transaction in block 26650 3 days ago.
I wonder if the switch away from using the live nonce to pulling it from the local node db has exposed some inconsistency with how the nonces are tracked in the db for historical blocks?

**To Reproduce**
1. Update node to api v1.0.5
2. Make the POST to /account/balance with the body above
3. Verify that it returns the incorrect nonce

**Expected behavior**
The nonce should be 1 for this address (this issue is happening for multiple addresses, I've just included one for simplicity).

**Desktop (please complete the following information):**
stacks-blockchain-api v1.0.5
stacks-blockchain node 2.05.0.0.0

**Comment by zone117x** [comment]
Can you confirm what nonce value you are expecting? E.g. should it be the _next_ nonce value that should be used in subsequent transactions after the given block? If so, this should just be an off-by-one bug.

**Comment by kmur911** [comment]
This is an address which hasn't generated a transaction since block 26650. I'm querying its nonce at block 27041 and getting back 0, when it should be 1 according to the explorer.  So in this case I just need it to accurately return the _current_ nonce (i.e as you say, the next nonce that should be used in subsequent transactions). So all addresses should initialize by returning nonce 0, then if a transaction with nonce 0 finalizes in a block, starting at that block that address should return nonce 1, and so on.

**Comment by zone117x** [comment]
@kmur911 ty, working on another hotfix, looks like a simple off-by-one. Do you have any addresses that have over 1 or 2 nonces to also test with?

**Comment by kmur911** [comment]
Yup, STX36MN2TXCMCFNVSWB6HQGJZ36W0Q9ER6ZEYERC should return [95](https://explorer.stacks.co/address/STX36MN2TXCMCFNVSWB6HQGJZ36W0Q9ER6ZEYERC?chain=testnet), and is currently returning 94
