### ISSUE TITLE
optimize `count(*)` query performance

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#974]
We currently use count queries with a few filters to retrieve the `total` rows for some endpoints with a large number of results (get block list, get tx list, etc.).

Some examples:
```sql
SELECT COUNT(*)::integer
FROM txs
WHERE canonical = true AND microblock_canonical = true AND block_height <= $1

SELECT COUNT(*)::integer total
FROM microblocks
WHERE canonical = true AND microblock_canonical = true

SELECT COUNT(*)::integer
FROM blocks
WHERE canonical = true
```

However, these queries are becoming very heavy (as reported by @CharlieC3 's PgHero tool) due to the fact that [postgres can't really optimize them too much using indexes](https://www.cybertec-postgresql.com/en/postgresql-count-made-fast/), so we have to come up with a way to retrieve this information in a much more performant way.

One option is to create a new table or materialized view that maintains counts for the largest tables (txs, events, blocks, etc.) at specific block heights so we can query it much quicker.

**Comment by zone117x** [comment]
@rafaelcr I've marked this as P2 as this issue seems more important than most other issues at P3. Let me know if you think otherwise.
