### ISSUE TITLE
Pin exact package.json dependencies

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#975]
We're currently using `^x.y.z` versioning (any version in the same major range) in `package.json`. We've ran into a few issues in the past with deps not following semver completely. We're also prone to breakage from other js-ecosystem idiosyncrasies, e.g. catching a human-readable string in an `Error` objects due to common lack of proper error handling in many libraries. 

We should pin all dependencies to exact versions, e.g. `x.y.z` rather than `^x.y.z`. 

The repo already has bots setup to report dependency vulnerability / security related issues, so no need to worry there.

**Comment by MHassanTariq** [comment]
Please let me know if there is anything remaining regarding this issue. Otherwise, I think we can close it. Thanks!
@zone117x @rafaelcr
