### ISSUE TITLE
Should use `varchar(n)` in place of text

### ISSUE THREAD

**Issue by aulneau** [hirosystems/stacks-blockchain-api#976]
many columns are of `text` type, where indexes don't really work with that format. I've found performance improvements for changing columns that hold Stacks addresses to VARCHAR(256). This allows indexes to work (or work better). Other fields could be varchar too, such as contract names, etc. Whatever the limit in clarity is can be reflected here too.

**Comment by zone117x** [comment]
Thank you for the debugging and data @aulneau! This kind of help is much appreciated.

In this case, I'm curious of the real-world performance differences around `text` type vs `varchar(n)`. The postgres docs https://www.postgresql.org/docs/12/datatype-character.html state:
> There is no performance difference among these three types, apart from increased storage space when using the blank-padded type, and a few extra CPU cycles to check the length when storing into a length-constrained column. While character(n) has performance advantages in some other database systems, there is no such advantage in PostgreSQL; **in fact character(n) is usually the slowest of the three because of its additional storage costs. In most situations text or character varying should be used instead.**

**Comment by rafaelcr** [comment]
Closing as stale for now
