### ISSUE TITLE
what happened to the client library documentation?

### ISSUE THREAD

**Issue by dantrevino** [hirosystems/stacks-blockchain-api#979]
**Describe the bug**
Documentation for the client library used to be available.  Now its gone?  Maybe? Was it re-published somewhere else? 

**To Reproduce**
1. look for client library docs

**Expected behavior**
I used to be able to find the link to the docs from github.

**Screenshots**

**Console log**
If applicable, add console log to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by friedger** [comment]
See hirosystems' github page: https://hirosystems.github.io/stacks-blockchain-api/

**Comment by dantrevino** [comment]
This is the api documentation, but not the client library docs.  Or am I missing a link somewhere?  I dont see it.

**Comment by dantrevino** [comment]
thx @diwakergupta
