### ISSUE TITLE
feat: Dashboards on Hiro Explorer

### ISSUE THREAD

**Issue by gregorycoppola** [hirosystems/stacks-blockchain-api#984]
Other projects have dashboards that I sometimes use to learn things about the Stacks chain, especially the mempool dashes.

We have some dashes in private mode, but we should consider adding dashes to our public product, because users look at these dashes, and so do I.

https://stacksonchain.com/dashboards
https://stacksdata.info/

Maybe we can make even better dashes with our knowledge of the Stacks chain and what is important.

**Comment by sabbyanandan** [comment]
We will revisit this when we have demand for such a DevEx.
