### ISSUE TITLE
Add support for postgres read replicas

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#990]
**Is your feature request related to a problem? Please describe.**
I'd like support added for postgres read replicas. This is different than the API's read-only mode, where an API only accepts HTTP traffic and does not write to the Postgres database. The API in read-only mode will still attempt to perform a SQL LISTEN command on the backend Postgres database at bootup. If read replicas are being used, LISTEN will fail on them and cause the API to crash.

**Describe the solution you'd like**
Support for read replicas should ensure any SQL commands which require a db primary, be directed to the primary. While other compatible commands (pretty much everything else when running a read-only API) is directed to a different URL which includes the read-replicas.

This can be achieved by storing the primary and read-replica URLs in two different ENV variables, and choosing the appropriate URL depending on the action being performed.

See [this page](https://www.postgresql.org/docs/12/hot-standby.html) for certain SQL actions which will cause errors in a read replica.

**Comment by zone117x** [comment]
@CharlieC3 any idea of the data replication latency? One potential issue with hooking LISTENs to the primary is that the follow up queries against the replica might fail if the data is not yet available.

**Comment by aulneau** [comment]
this is great news, was just going to come make this issue 🙏
